### ISSUE TITLE
Font support for smaller size (low resolution screens, or resized browser – graphs)

### ISSUE THREAD

**Issue by andreas1974** [UtilitechAS/amsreader-firmware#380]
**Describe the bug**
Adjacent numbers get on top of each other, which is very hard to read on a phone with small screen.
A attach a screen shot from a Sony Xperia X Compact (Android), where this problem is shown.

![Sony XPeria X Compact Screenshot](https://user-images.githubusercontent.com/998258/207288474-919126e0-dbf4-4302-b1f1-a6497f8b0fcb.PNG)

I notice a similar effect just resizing my Chrome web browser on Windows below a certain width. I attach two screen shots from my computer as well. One slightly problematic and one normal:

Too narrow:
![Chrome on Computer screen, sized to small](https://user-images.githubusercontent.com/998258/207292291-aa2ac069-d2d1-4633-8a05-1da605558921.JPG)

Normal:
![Chrome on Computer screen, sized to large enough](https://user-images.githubusercontent.com/998258/207292296-75760f40-5253-4fbd-9ec2-d39431bc9d6e.JPG)

Perhaps every other number could be shown higher up and every other lower down? Or allow shrinking to an even smaller font size, on the graphs that are affected.

Bästa hälsningar
Andreas

PS Vi är så nöjda med detta gränssnitt och familjemedlemmarna tittar på elanvändningen och graferna med priser flera gånger varje dag! Tack för ett gediget arbete! DS

**Comment by ArnieO** [comment]
Hej Andreas,
Tack for gode ord! 😃 

Thank you for your feedback and comments, but there will be no more adjustments on the graphical layout on firmware v2.1.x, as we are about to change the graphics library for v2.2 which is currently out for beta testing, please see: https://github.com/gskjold/AmsToMqttBridge/discussions/370 

It would be great if you could test the latest beta test version and see if it works better for you - and participate in the discussions on that thread.

**Comment by gskjold** [comment]
Definitely issues on smaller screens with the beta versions as well, but it will be addressed

**Comment by gskjold** [comment]
Graphs in v2.2 have improved in later patches which I consider to be good enough for mobile screens
