### ISSUE TITLE
Energy price per hour unit

### ISSUE THREAD

**Issue by kng** [UtilitechAS/amsreader-firmware#401]
The price reported is in EUR (or whatever is set in the ENTSO-E) and should be in unit/kWh instead ?
![bild](https://user-images.githubusercontent.com/5262110/212840353-99d6d912-e439-4952-a892-7db59da038a9.png)

This is set in HA Energy dashboard:
![bild](https://user-images.githubusercontent.com/5262110/212843739-fdcc4e94-27fe-4560-96d4-0b313ec1a213.png)

**Comment by ArnieO** [comment]
I'm not sure I understand your comment. 
If you go to Config/Entso-E you can choose currency. Did you select EUR there?
![image](https://user-images.githubusercontent.com/10295178/212875953-24dbf6c8-86cd-4955-8bc7-f8c5c59981d3.png)

**Comment by kng** [comment]
It's not whether it is SEK or EUR, but SEK/kWh or EUR/kWh.

**Comment by kng** [comment]
To clarify, the price is fetched in currency/MWh as seen [here](https://github.com/gskjold/AmsToMqttBridge/blob/master/src/entsoe/EntsoeApi.cpp#L64-L65), then converted to currency/kWh. This unit should be carried over to the unit presented over [ha](https://github.com/gskjold/AmsToMqttBridge/blob/master/src/mqtt/HomeAssistantStatic.h#L45)/json etc

**Comment by gskjold** [comment]
Any chance you could test if this is ok in latest build in #370 ?

**Comment by kng** [comment]
Yes, it's up and running 2.2 beta and after switching the currency and rebooting it is no longer complaining.
![bild](https://user-images.githubusercontent.com/5262110/214127815-2fb5ce43-c583-458e-a829-96577bfc5af5.png)

![bild](https://user-images.githubusercontent.com/5262110/214127597-c9457606-4b55-408e-a71a-5c76932bf07d.png)
