### ISSUE TITLE
Time and date off / ntp not working?

### ISSUE THREAD

**Issue by Lin4fun** [UtilitechAS/amsreader-firmware#413]
**Describe the bug**
The time and date is off, looks like there is something wrong with ntp import. This was also the case in version 2.1.7, now upgraded to 2.2.0. I have now issues with other devices in the network using ntp service from no.pool.ntp.org. 
Time sone is set to Europe/oslo, NTP server no.pool.ntp.org. Also tried setting IP of ntp pool aswell a local running ntp service and through dhcp.
Shown date is 28.00.23 time started at 18.00

**Screenshots**
![Config](https://user-images.githubusercontent.com/27723379/215281761-d04d6c17-c233-4d97-94b9-07c0bc9952d4.jpg)
![Main](https://user-images.githubusercontent.com/27723379/215281764-650432df-fa0d-4f7a-9fdf-05606e72eab9.jpg)

**Hardware information:**
 - Country: Norway
 - Meter: Kamstrup
 - Encryption enabled: no
 - AMS reader: Pow-U+

**Relevant firmware information:**
 - Version: 2.1.7 & 2.2.0
 - MQTT: yes
 - MQTT payload type: [e.g. JSON]
 - HAN baud and parity: 2400 8N1
 - ENTSO-E API enabled: yes

**Comment by ArnieO** [comment]
Unknown problem, the default setting has always worked well on my router - and we should expect to have heard other users reporting this.
Could it be a setting in your router or firewall that gives you these problems?

**Comment by gskjold** [comment]
I've been running no.pool.ntp.org and the "obtain from DHCP" option unchecked for the last day now, seems to work fine here... Not sure what else to test to be honest, but I'll circle back to this if I can think of anything

**Comment by atian888** [comment]
I am new to this AMSreader. Running vs 2.2.2 and get timelabel as "01.00.1970 01:13". 
Testet no.pool.ntp.org as well without success.

**Comment by ArnieO** [comment]
This is my setting - that works for me:
![image](https://user-images.githubusercontent.com/10295178/215985450-030f16bf-4bfd-4ec2-a77a-0634178fa034.png)

**Comment by atian888** [comment]
Strange, but today the date/time was normal (!)... Maybe some delay somewhere... 
Chip: esp32s2
Device: Pow-U+

**Comment by Lin4fun** [comment]
Seems to work fine now after upgrade to 2.2.5
