### ISSUE TITLE
Webpage broken after update to 2.2.0

### ISSUE THREAD

**Issue by stone17** [UtilitechAS/amsreader-firmware#414]
**Describe the bug**
Webpage only shows top header (Status of HAN, ESP and so on), but no graphs or anything else.
It is possible to manually navigate to /configuration.
MQTT still sends all info about power consumption.

The console in the browser shows this error:
VM91:1 Uncaught (in promise) SyntaxError: Bad escaped character in JSON at position 361

Seen this behavior on 2 devices.

**To Reproduce**
Upgrade from 2.1.17 to 2.2.0 on ESP32-S2-MINI-1

**Expected behavior**
Webinterface keeps working as on 2.1.17

**Screenshots**
![image](https://user-images.githubusercontent.com/3457521/215285499-7923d8b1-fdd4-4cfa-916f-09d24c34c19c.png)

**Hardware information:**
 - Country: Sweden
 - Meter: Dont know
 - Encryption enabled: Dont know
 - AMS reader: ESP32-S2-MINI-1
 - M-bus adapter (if applicable): NA

**Relevant firmware information:**
 - Version: 2.2.0
 - MQTT: yes
 - MQTT payload type: JSON
 - HAN GPIO: GPIO18?
 - HAN baud and parity: 115200 8N1 inverted
 - Temperature sensors: NA
 - ENTSO-E API enabled: no

**Comment by gskjold** [comment]
Sounds like a invalid character in data.json, could you get me the content of that?

**Comment by stone17** [comment]
how do i fetch the json?

**Comment by gskjold** [comment]
Go to the network tab in the developer tools and you can click on the file and go to the response tab

**Comment by stone17** [comment]
{"im":20000,"om":0,"mf":16,"i":546,"e":0,"ri":0,"re":160,"ic":1934.300,"ec":0.004,"ric":8.929,"rec":524.765,"u1":225.00,"u2":226.80,"u3":228.90,"i1":1.00,"i2":1.20,"i3":0.50,"f":0.00,"f1":0.00,"f2":0.00,"f3":0.00,"v":0.000,"r":-72,"t":-127.00,"u":9089,"m":114040,"em":1,"hm":1,"wm":1,"mm":1,"me":0,"p":null,"mt":255,"ds":0,"ea":{"x":1.8,"p":[1.52,2.07,2.01,1.74,1.50],"t":5,"h":{"u":0.02,"c":0.00,"p":0.00,"i":0.00},"d":{"u":14.71,"c":0.00,"p":0.00,"i":0.00},"m":{"u":352.64,"c":0.00,"p":0.00,"i":0.00}},"pr":"","he":0,"ee":0,"c":1674932510,"a":true}

**Comment by gskjold** [comment]
Hum weird, looks totally find... What if you click on the error message in the console, does it expand to the problem in question?

**Comment by stone17** [comment]
![image](https://user-images.githubusercontent.com/3457521/215286578-c801abd8-e666-46c5-ba61-b4423d79f809.png)

**Comment by msasdk** [comment]
I have the exact same issue.

**Comment by stone17** [comment]
In this view it is highlighting a backslash when i click on the error.

**Comment by gskjold** [comment]
So the slash in the model number breaks sysinfo.json, got it... That's a bummer... Too bad this didn't show up in testing. I will make some adjustments

**Comment by gskjold** [comment]
Here is a test build. Unplug the device from the meter and hit reset so that the model number is cleared. Unzip the attached file and then go to the info page and upload the firmware.bin file

This is for ESP32-S2, did both of you have the same chipset?
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/10528092/esp32s2.zip)

**Comment by gskjold** [comment]
Hang on, I made a mistake in the code...

**Comment by gskjold** [comment]
Here we go: 
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/10528098/esp32s2.zip)

**Comment by stone17** [comment]
After flashing your zip file, it works again. It does want to update to 2.2.0 though.

**Comment by gskjold** [comment]
Yeah, all beta firmware will show the upgrade link to the latest version. I will publish this update soon

**Comment by stone17** [comment]
No worries, thanks a lot for the quick support :)

**Comment by msasdk** [comment]
I'm on regular ESP32 and 2.2.1 still does not work unfortunately.

**Comment by gskjold** [comment]
Navigate to /sysinfo.json and /data.json on your device and attach the content in a new issue

**Comment by msasdk** [comment]
sysinfo
{"version":"v2.2.1","chip":"esp32","chipId":"c4ef","mac":"24:0A:C4:05:EF:C4","apmac":"24:0A:C4:05:EF:C5","board":203,"vndcfg":true,"usrcfg":true,"fwconsent":1,"hostname":"ams","booting":false,"upgrading":false,"net":{"ip":"192.168.1.49","mask":"255.255.255.0","gw":"192.168.1.1","dns1":"192.168.1.1","dns2":"0.0.0.0"},"meter":{"mfg":255,"model":"\\253868807_B","id":""},"ui":{"i":0,"e":0,"v":0,"a":0,"r":0,"c":0,"t":0,"p":0,"d":0,"m":0,"s":0},"security":0}

data
{"im":11085,"om":0,"mf":16,"i":1237,"e":0,"ri":0,"re":249,"ic":9125.513,"ec":0.001,"ric":2.346,"rec":1827.630,"u1":229.40,"u2":230.20,"u3":234.10,"i1":0.40,"i2":4.10,"i3":1.20,"f":0.00,"f1":0.00,"f2":0.00,"f3":0.00,"v":0.000,"r":-63,"t":-127.00,"u":1337,"m":224372,"em":1,"hm":1,"wm":1,"mm":1,"me":0,"p":null,"mt":255,"ds":2,"ea":{"x":5.0,"p":[1.51,7.33,1.65,7.30,7.28],"t":10,"h":{"u":0.21,"c":0.00,"p":0.00,"i":0.00},"d":{"u":9.78,"c":0.00,"p":0.00,"i":0.00},"m":{"u":421.18,"c":0.00,"p":0.00,"i":0.00}},"pr":"10Y1001A1001A47J","he":0,"ee":0,"c":1674938872,"a":true}

**Comment by gskjold** [comment]
Sort of looks like the same issue, but shouldnt happen... if you are in chrome, press F12 to open developer tools, check console to see if there are errors like the screenshot earlier in this thread

**Comment by msasdk** [comment]
![image](https://user-images.githubusercontent.com/13538204/215290879-de6d05ea-1df9-4d1a-88cf-5a528b11fe11.png)

**Comment by msasdk** [comment]
This is what 2.2.0 looked like (firefox)
![image](https://user-images.githubusercontent.com/13538204/215290940-50b19a83-29b7-4e23-9df4-f2892876bef9.png)

**Comment by gskjold** [comment]
Are you able to go to configuration? Check if all gui elements are set as hidden. If so, you need to enable some of them. Normal config:

![Screenshot_20230128_220727_Chrome](https://user-images.githubusercontent.com/4446828/215291153-a726e91b-cbb6-41e9-bf2d-05d142eaef42.jpg)

**Comment by msasdk** [comment]
Yep sorry about that :) 
All good now.

**Comment by gskjold** [comment]
Sweet! Good to hear
