### ISSUE TITLE
Monthly-cost error after upgrade from 2.1.6 to 2.2.1

### ISSUE THREAD

**Issue by atle-dahlman** [UtilitechAS/amsreader-firmware#415]
The monthly cost error after the update.  Illustrated below with an image from Home assistant.

![image](https://user-images.githubusercontent.com/101756371/215335917-d682c184-b0a1-4a8a-a525-757c5152730c.png)

**Comment by gskjold** [comment]
Sorry it disappeared on you. v2.2 have gone through extensive testing before release and this has never happened. Might be a edge case around loading and saving.

**Comment by atle-dahlman** [comment]
The funny thing is that it just didn't get reset.  If so the daily and monthly cost should be the same.  It's not.
![image](https://user-images.githubusercontent.com/101756371/215337647-0755f323-27dc-4855-9f00-8ebed3e0a42f.png)

**Comment by gskjold** [comment]
Found the issue, it incorrectly divided the stored value for month by 100..
