### ISSUE TITLE
Kamstrup omnipower vcc

### ISSUE THREAD

**Issue by majskolven** [UtilitechAS/amsreader-firmware#416]
Hi,
I have a kamstrup omnipower connected to a nodemcu esp8266. I am trying to power this through the HAN port vcc pin. Vcc and gnd from HAN is connected to VIN and gnd on the nodemcu board. I also use a 1000uf 10v capacitor (nodemcu did not boot without it). Data- out on HAN connected to gpio 13 on the nodemcu.

With micro-usb and a powerbank to power the board everything works as expected, i get all the readings from the meter.
But with above setup it only boots up and no data is recieved. 
Any idea what might be wrong? Maybe some configuration needed?

//Robin

**Hardware information:**
 - Country: Sweden 
 - Meter: Kamstrup
 - Encryption enabled no
 - AMS reader: Nodemcu esp8266
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.1.15
 - MQTT:yes
 - MQTT payload type: Home assistant
 - HAN GPIO: gpio13
 - HAN baud and parity: 2400 8N1
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [yes/no]

**Comment by ArnieO** [comment]
I can think of a few potential pitfalls:
- If your Nodemcu board consumes too much, the power output from the Kamstrup could shut down temporarily.
- The power output of the Kamstrup is nominal 4,15V. Maybe the voltage regulator on the Nodemcu board is not able to regulate down this voltage correctly, as it is lower than the 5V from a power bank or external power. Check which regulator is used

In both cases: Check/measure if the 3.3V voltage on the Nodemcu is actually 3,3V when powered from the meter.
