### ISSUE TITLE
Circular graphs

### ISSUE THREAD

**Issue by mnorrelund** [UtilitechAS/amsreader-firmware#417]
Thanx for your work. Her some graphical hickups from chrome & firefox browser - no zoom level:
![image](https://user-images.githubusercontent.com/120026374/215493875-1fd87829-d942-4506-9690-a951c8528c15.png)
![image](https://user-images.githubusercontent.com/120026374/215493968-9383fa1d-b556-446f-ac0a-5d48e27b8fed.png)
![image](https://user-images.githubusercontent.com/120026374/215494042-9505055c-30eb-4362-a14b-32df6b546254.png)
last one is as expected. Red/green? I have solarpannels attached

**Comment by gskjold** [comment]
Thank you! Fix will be included in next patch

**Comment by ArnieO** [comment]
> last one is as expected.

Not quite. The graph should be scaled according to your installed maximum production power. Please check that you have provided correct value for your installation here:
![image](https://user-images.githubusercontent.com/10295178/215517449-30e8ac76-aaab-4d94-98a0-9edf84b12087.png)

**Comment by gskjold** [comment]
Scaling is broken in current version...

**Comment by ArnieO** [comment]
> Scaling is broken in current version...

💡
