### ISSUE TITLE
Version shown inconsistently in GUI

### ISSUE THREAD

**Issue by henriklund** [UtilitechAS/amsreader-firmware#423]
**Describe the bug**
Inconsistency in GUI between reported versions for download.

**To Reproduce**
1. Install v2.2.3
2. Await v2.2.4 (frontpage and Device Information are in sync
3. Await v2.2.5 (frontpage now shows v2.2.5 while Device Information shows links for v2.2.4)

**Expected behavior**
Same versions shown

**Screenshots**
![image](https://user-images.githubusercontent.com/8402745/216267445-9146f541-65d7-4073-8d21-889ff0ec3bc0.png)

**Hardware information:**
- Country: DK
- Meter: Kampstrup
- Encryption enabled: yes
- AMS reader: Pow-K ESP8266
- M-bus adapter (if applicable): N/A
- Relevant firmware information:

**Version: 2.2.3**
- MQTT: yes
- MQTT payload type: JSON
- HAN GPIO: GPIO3 (according to configfile)
- HAN baud and parity: 2400 8N1
- Temperature sensors: N/A
- ENTSO-E API enabled: yes (although ESP8266 does not provide possibility to enter ENTSO-E API key)
- 
**Additional context**
N/A

**Comment by ArnieO** [comment]
I confirm having seen the same. There is certainly something here.
