### ISSUE TITLE
Webpage stuck with "Loading configuration" when selecting configuration page

### ISSUE THREAD

**Issue by michaelsidenius** [UtilitechAS/amsreader-firmware#424]
**Describe the bug**
After update to 2.2.5 selecting the confíguration cock wheel, the configuration webpage is stuck with a message in a white box saying "Loading configuration". The configuration page is shown dimmed below. Refresh does not help
Normal operation including MQTT otherwise.

**To Reproduce**
Select the confíguration cock wheel

**Expected behavior**
The configuration page is shown as normal

**Screenshots**

**Hardware information:**
 - Country: Denmark
 - Meter: Kampstrup
 - Encryption enabled yes
 - AMS reader: ESP8266

**Relevant firmware information:**
 - Version: 2.2.5
 - MQTT: yes
 - MQTT payload type: HomeAssistant
 - HAN GPIO: GPIO16
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: NA
 - ENTSO-E API enabled: no

**Additional context**

**Comment by gskjold** [comment]
Please go to the system info tab and download the configuration. Open the file with a text editor and check if there are any strange characters.

You can also check http://<my-ip-or-host>/configuration.json

**Comment by michaelsidenius** [comment]
Thanks!
My Curency setting seems to be bad, when inspecting the JSON config: 

> "p":{"e":false,"t":"","r":"10YDK-2--------M","c":"DKKu�?�","m":1.000},

I cant download the settings. How can I edit it on-line? By uploading a corrected JSON file?

**Comment by gskjold** [comment]
On /status you can download configuration as file, and then edit and re-upload it on the same page. This page should still work even though your configuration page is broken. If not, there is a HTML-only fallback page on /firmware where you can also upload config.

**Comment by gskjold** [comment]
If you cannot download config from /status, the you can download with the following url: /configfile.cfg?iw=true&im=true&ie=true&it=true&ih=true&ig=true&id=true&in=true&is=true&ic=true

**Comment by michaelsidenius** [comment]
Thanks, the last URL did the trick. However my Kampstrup Authentication key got shortened so I had to re-enter it, but I am back up.
Once again thank you!

**Comment by michaelsidenius** [comment]
Solved

**Comment by gskjold** [comment]
Good to hear! Thank you for poiting out issue with the authentication key, I found the problem where it got shortened.
