### ISSUE TITLE
Entsoe API endpint discontinued

### ISSUE THREAD

**Issue by Glomma** [UtilitechAS/amsreader-firmware#431]
Just registered, and found this note:

> Dear Transparency Platform users,
> 
> The legacy REST API endpoint (https://transparency.entsoe.eu/api)  is planned to be discontinued on 14.02.2023.
> 
> As communicated on 03.08.2022, please switch to the new REST API endpoint (https://web-api.tp.entsoe.eu/api) as soon as possible to avoid integration problems.
> 
> Many thanks!
> 
> Kind regards,
> 
> Transparency Platform team

---
https://transparency.entsoe.eu/api is used in EntsoeApi.cpp

**Comment by gskjold** [comment]
Thanks for the heads up! I cannot find any communication from Entsoe, so I guess this must have been lost to a spam folder...

Updated endpoint in code, scheduling new release at the end of the week
