### ISSUE TITLE
Read meter registers on startup

### ISSUE THREAD

**Issue by rogerthn2019** [UtilitechAS/amsreader-firmware#437]
**Is your feature request related to a problem? Please describe.**
I'm using `curl --silent http://192.168.C.D/data.json  | awk -F "," '{print $4,$5,$8,$9 ...`
to update some Domoticz devices, including Accumulated import and export and those values are 0 after a restart

**Describe the solution you'd like**
Read meter registers at startup unless there is a trick to read those before next hour change?

**Describe alternatives you've considered**
Force reading of meter registers

**Additional context**
![image](https://user-images.githubusercontent.com/57598997/218272638-faecffd8-03ed-4881-8246-568382349400.png)

**Comment by gskjold** [comment]
This is a one way communication where meter push data on a schedule. Pulling data is not an option

**Comment by rogerthn2019** [comment]
OK, make sense.
