### ISSUE TITLE
Tariff peaks wrong?

### ISSUE THREAD

**Issue by Hacsnysted** [UtilitechAS/amsreader-firmware#440]
Only 1 peak hour per day show up in peaks
I had 3 peaks occurred the same day but only the hour with highest value show up in tariff peaks

**Comment by gskjold** [comment]
This is per design. As far as I know, this is what all norwegian grid operators use for their calculation

**Comment by Hacsnysted** [comment]
Thank you. I misunderstood the new tariff peaks model.
Closing this issue the
