### ISSUE TITLE
Does not reboot properly when changing to Static IP

### ISSUE THREAD

**Issue by ArnieO** [UtilitechAS/amsreader-firmware#442]
**Describe the bug**
When adding Static IP on an operating device, it is stuck on "Rebooting" without proceeding. 

**To Reproduce**
On an operating device without static IP:
1. Enter static IP parameters
2. Click on 'Save'
3. Device is stuck on greyed-out screen:
![image](https://user-images.githubusercontent.com/10295178/218318701-3763842a-5fa4-4044-ad73-d3d13cb0f97c.png)

4. After a manual Reset of the board, the static IP does not work.
5. Re-entering AP mode, verify static IP parameters are registered correctly
6. Reboot - and static IP address is still unreachable. 

**Expected behavior**
Reboot with reload of GUI

**Hardware information:**
 - Country: Norway
 - Meter: Test jig
 - Encryption enabled: no
 - AMS reader: Pow-U

**Relevant firmware information:**
 - Version: 2.2.7
 - MQTT: no
 - HAN GPIO: GPIO16
 - HAN baud and parity: 2400 8N1
 - ENTSO-E API enabled: no

**Additional context**

**Comment by kaihp** [comment]
I did not see this problem in version 2.2.23/24 (maybe it is already fixed?)
I did have problems with v2.2.23 not being able to stay up for more than 24h, which I'll report seperately.
