### ISSUE TITLE
Tariff thresholds

### ISSUE THREAD

**Issue by Ainnerst** [UtilitechAS/amsreader-firmware#443]
Higher Tariff thresholds

Is it possible to increase the maximum number for tariff thresholds from 255 to 500?
In Norway the maximum threshold is per now above 500kW
![Skjermbilde 2023-02-12 202041](https://user-images.githubusercontent.com/125216109/218332355-d4316194-c172-4279-9f46-5084e56e5e4e.jpg)

**Comment by gskjold** [comment]
Have not really though of this as an issue, most people are not up at that level :) But yes, I understand the need for this as there are a few companies out there who can reach that level
