### ISSUE TITLE
no Pin selection GPIOs in newer Version on WEMOS (upgrade from 2.2.3 to 2.2.7)

### ISSUE THREAD

**Issue by etzisim** [UtilitechAS/amsreader-firmware#444]
**Describe the bug**
I can not select the GPIO HAN Pins after Upgrade
no HAN connectn on my ESP8266

**To Reproduce**
I use the HAN interface on GPIO5 on my WEMOS D1 mini, after the Upate i just can use UART0 or UART2
after the Downgrade i had to select the GPIO5 in the settings again

**Hardware information:**
 - Encryption enabled [yes]
 - AMS reader: ESP8266 with TTL MBUS adapter

**Additional context**

**Comment by gskjold** [comment]
Fixed in 2.2.8
