### ISSUE TITLE
Wrong vaules displayed for some fields, after upgrade of firmware

### ISSUE THREAD

**Issue by IRQNMI** [UtilitechAS/amsreader-firmware#445]
**Describe the bug**
After upgrading firmware, the Meter total and "Real time calculation" for Consumption and Cost are showing wrong values (Starts at 0). The values are not saved before upgrade, nor recovered after upgrade. Recovers at "full hour".

**To Reproduce**
1. Take note of Meter total and "Real time calculation" for Consumption and Cost at the field Hour.
2. Upgrade firmware
3. Meter total and "Real time calculation" for Consumption and Cost at field Hour starts at 0 and counting. 

**Expected behavior**
Before firmware upgrade the active hour Consumption and Cost are saved and reloaded after upgrade.
Or the GUI should indicate that the vaules are "missing" until recover happends (at full hour) - showing values like '------'.

**Screenshots**
Before upgrade:
![before](https://user-images.githubusercontent.com/118473168/218340079-110cefdd-f610-4521-ab76-594bf69fbceb.JPG)

After upgrade:
![after](https://user-images.githubusercontent.com/118473168/218340086-4ddc65d2-f692-4786-ae78-2889cc004498.JPG)

**Hardware information:**
 - Country: Norway
 - Meter: Kamstrup
 - Encryption enabled: no
 - AMS reader: Pow-K+ / esp32s2

**Relevant firmware information:**
 - Version: 2.2.x

**Additional context**
Upgraded now from 2.2.7 to 2.2.8 
Happend on every 2.2.x upgrade done

**Comment by ArnieO** [comment]
I agree - it is a good proposition to show a placeholder for "accumulated" until next whole hour is passed, and the value is refreshed. 

(Note to Danish users, at least those on Kamstrup meters: You will not see this issue, as your meter reports accumulated value in all payloads.)
