### ISSUE TITLE
Wrong display of import value with multiplicator

### ISSUE THREAD

**Issue by Ainnerst** [UtilitechAS/amsreader-firmware#448]
**Describe the bug**
When watt is multiplied by 100 it displays a random value for import but sometimes display correct value. If multiplicator is set to 1 it shows ''correct'' value

**To Reproduce**
Set multiplicators for watt  and A to 100

**Expected behavior**
Show correct value after multiplication

**Screenshots**
![Skjermbilde 2023-02-14 105115](https://user-images.githubusercontent.com/125216109/218713799-d9fb6b42-174c-4a2f-871b-37a7ba3147d9.png)
![Skjermbilde 2023-02-14 105145](https://user-images.githubusercontent.com/125216109/218713807-49c508df-6599-412d-af5c-c1d1f21413eb.png)
![Skjermbilde 2023-02-14 114858](https://user-images.githubusercontent.com/125216109/218713982-35a0c951-5621-47d4-9c1d-b9cc72873d6e.png)

**Hardware information:**
 - Country: Norway
 - Meter: Kaifa MA304T4
 - Encryption enabled no
 - AMS reader: Pow-U, esp32s2

**Relevant firmware information:**
 - Version: 2.2.8
 - MQTT: no
  - HAN baud and parity: 2400 8E1
 - Temperature sensors no
 - ENTSO-E API enabled: yes

**Comment by ArnieO** [comment]
Are you then comparing with the value on the LCD screen of your Kaifa meter?
In an installation with many thermostats, the power value will fluctuate quite a bit between subsequent readings.

**Comment by Ainnerst** [comment]
> Are you then comparing with the value on the LCD screen of your Kaifa meter? In an installation with many thermostats, the power value will fluctuate quite a bit between subsequent readings.

Yes, and if i set multiplicator back to 1 the value is stable.

**Comment by ArnieO** [comment]
> Yes, and if i set multiplicator back to 1 the value is stable.

OK, interesting. I tried to change my multiplier to 100 but did not see anything strange. 
Could it be an overflow error here, @gskjold ?

**Comment by gskjold** [comment]
Strange indeed. I will have to look into this, but I cannot say I have seen this before.

May I ask what kind of installation you have that require a 100 multiplier? Is it a meter with current transformer? Kaifa with NVE format should be supported out of the box. But I see you have set a 200A main fuse, so I assume this is not a normal house? :)

**Comment by gskjold** [comment]
> > Yes, and if i set multiplicator back to 1 the value is stable.
> 
> OK, interesting. I tried to change my multiplier to 100 but did not see anything strange. Could it be an overflow error here, @gskjold ?

Indeed, exactly what it is! Obviously need to do something about that.

**Comment by Ainnerst** [comment]
> 

if I change both watt and amp, it happends more frequently than only changing watt.

**Comment by Ainnerst** [comment]
> Strange indeed. I will have to look into this, but I cannot say I have seen this before.
> 
> May I ask what kind of installation you have that require a 100 multiplier? Is it a meter with current transformer? Kaifa with NVE format should be supported out of the box. But I see you have set a 200A main fuse, so I assume this is not a normal house? :)

Yes, this is a meter with a current transformer, and it is an installation at my workplace where we plan to implement some smart regulation programming to better control different  loads. The 100 multiplier is necessary to account for the current being measured by the transformer.

**Comment by Ainnerst** [comment]
I forgot to add that the history for energy use last 24h looks like this ( i assume its the same issue)
![Skjermbilde 2023-02-14 194400](https://user-images.githubusercontent.com/125216109/218829019-07d4dac8-4b40-4baf-a3e8-0937c7e528bc.png)

**Comment by gskjold** [comment]
Are you comfortable flashing and running a beta?

Make sure you have necessary multiplier on both watt and kwh to get the correct values in the bar chart.

[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/10736117/esp32s2.zip)

**Comment by gskjold** [comment]
I see now that you have 100 on all the multipliers, which sort of makes sense, but check that the kwh display in AMS matches what is displayed on the meter. I know that in some cases the meter adjusts for kwh reading and no multiplier is necessary

**Comment by Ainnerst** [comment]
> I see now that you have 100 on all the multipliers, which sort of makes sense, but check that the kwh display in AMS matches what is displayed on the meter. I know that in some cases the meter adjusts for kwh reading and no multiplier is necessary

Yes, I havent checked that since the numbers are all over the place atm.

**Comment by Ainnerst** [comment]
> Are you comfortable flashing and running a beta?
> 
> Make sure you have necessary multiplier on both watt and kwh to get the correct values in the bar chart.
> 
> [esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/10736117/esp32s2.zip)

not so comfortable with flashing, but can have a look at it when I'm back at work tomorrow

**Comment by gskjold** [comment]
Connect USB power to Pow-U, unzip the attached file, go to status page and click "Select firmware file for upgrade", select "firmware.bin" and click upload. After a little while it should reboot with version "1f5a04e". Note that beta firmware will always claim that latest stable is a newer firmware.

![Screenshot from 2023-02-15 07-36-08](https://user-images.githubusercontent.com/4446828/218964508-6e7f9af1-30ec-4deb-8c8d-d1edca23ef09.png)
![Screenshot from 2023-02-15 07-36-23](https://user-images.githubusercontent.com/4446828/218964507-bf34e92b-4df6-4ec5-9757-6506561b1dd0.png)
![Screenshot from 2023-02-15 07-36-34](https://user-images.githubusercontent.com/4446828/218964505-61d89e12-3d95-475c-aedc-23720fd8e755.png)
![Screenshot from 2023-02-15 07-36-46](https://user-images.githubusercontent.com/4446828/218964503-7288b645-36ec-49a1-a349-90bb23733ccb.png)
![Screenshot from 2023-02-15 07-37-49](https://user-images.githubusercontent.com/4446828/218964499-af934c9f-2889-4e0b-b55f-bd127bf55d1a.png)

**Comment by Ainnerst** [comment]
> 

That looks alot better :) Both Import value and energy use last 24 hours are looking good! Thanks!

**Comment by gskjold** [comment]
Awesome! Will be included in a future patch, but I have yet to decide the release date for that patch. In any case, you just run this beta until 2.2.9 is released

**Comment by spinehead** [comment]
Hi, I experience the same sympthoms in my installation (also workplace use, 400A main breaker) 
Can I use the same beta firmware for my reader?

Hardware information:

Country: Norway
Meter: Aidon 6540
Encryption enabled no
AMS reader: Pow-U, esp8266 (GPIO12)

Relevant firmware information:
Version: 2.2.8
MQTT: no
HAN baud and parity: 2400 8E1
Temperature sensors no
ENTSO-E API enabled: yes

**Comment by gskjold** [comment]
Attached is a ESP8266 version of the latest snapshot which includes this fix. Unzip and install the same way as above.

[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/10790511/esp8266.zip)
