### ISSUE TITLE
2.2.8 / ESP32 does not fetch prices

### ISSUE THREAD

**Issue by tronde-ams** [UtilitechAS/amsreader-firmware#456]
FW2.2.8 / Norway / Aidon 3p it / ESP32 / MQTT
No new prices with own api key. I see this even after re-boot.
<img width="561" alt="with key" src="https://user-images.githubusercontent.com/97398751/219693233-f874b851-137a-4b16-ab7c-da69579d2737.png">

Without key, but activated prices, I see this with error message.
![without key](https://user-images.githubusercontent.com/97398751/219693456-f5636fe9-4e42-4c4c-b9a2-d11dc3e1f64a.jpg)

Trouble at ENTSO-E or something else?

**Comment by gskjold** [comment]
Seems like entso-e has some trouble. No data for any of my entso-e based applications. I suspect they have some migration issues after terminating the old endpoint on tuesday, the price publications have been unstable for the last few days

**Comment by tb205gti** [comment]
Same issue here, lacking price data since yesterday. No errormessages, just no prices

**Comment by tronde-ams** [comment]
Seems to be a problem at ENTSO-E, so I close this issue.
