### ISSUE TITLE
Import and export values on top of each other

### ISSUE THREAD

**Issue by SirJMD** [UtilitechAS/amsreader-firmware#462]
**Describe the bug**
Import and export values are jumbled together.

**To Reproduce**
Have a meter with export enabled.
Same behaviour in Chrome, Edge and Internet Explorer on Win10 as well as Chrome on Android.

**Expected behavior**
Readable import and export values.

**Screenshots**
![image](https://user-images.githubusercontent.com/10008798/220562078-18ccc003-2c73-4c52-8631-73b7e6d85760.png)

**Hardware information:**
 - Country: Denmark
 - Meter: Kamstrup
 - Encryption enabled: Yes
 - AMS reader: Pow-K+

**Relevant firmware information:**
 - Version: v2.1.17

Apart from that, AMS Reader is awesome!

**Comment by gskjold** [comment]
Thank you for your feedback. The graphs have been replaced in v2.2 series firmware, so this should not be a problem anymore. There could be other issues though, so feel free to provide some feedback after testing the latest release :)

**Comment by SirJMD** [comment]
> Thank you for your feedback. The graphs have been replaced in v2.2 series firmware, so this should not be a problem anymore. There could be other issues though, so feel free to provide some feedback after testing the latest release :)

I got a prompt to update prior to posting this bug report, but it seems like you have to manually update the firmware. That fixed it though :)
