### ISSUE TITLE
Clicking the configuration button doesn't load the configuration

### ISSUE THREAD

**Issue by shadowano** [UtilitechAS/amsreader-firmware#468]
**Describe the bug**
Clicking the configuration cog icon opens a small popup "Loading configuration". This is it. I see the configuration fields in the background, but the layover doesn't hide so I can't change anything. 

![image](https://user-images.githubusercontent.com/3582807/222154384-1bcf49b1-044a-4fb5-9343-2d7277c6fe19.png)

There are a lot of errors in the console when browsing the page
![image](https://user-images.githubusercontent.com/3582807/222155696-cb216f9e-1224-49c4-812c-374a17bd774a.png)

Error happening when clicking the configuration button:
![image](https://user-images.githubusercontent.com/3582807/222155846-dccc4da4-23c6-4587-a69b-086d01cb6d4d.png)

Browser: Version 110.0.5481.104 (Official Build) (64-bit), also tested Edge Version 110.0.1587.57 (Official build) (64-bit)
OS: Windows 11
Same happens on Android Phone using Chrome. 

**Hardware information:**
 - Country: Norway
 - Meter: Aidon
 - Encryption enabled no
 - AMS reader: Pow-U, ESP32

**Relevant firmware information:**
 - Version: v2.2.8

**Comment by gskjold** [comment]
Wild guess, maybe an illegal character in the config. Would check configuration.json

**Comment by shadowano** [comment]
I downloaded the configuration file and opened in Notepad++ and there looks to be some strange characters in entsoeArea and entsoeCurrency. I haven't configured Entsoe, or I have disabled it at some point before upgrading to version 2.x

Should I change these values and reupload config? I guess I need to also get my secrets downloaded before uploading

![image](https://user-images.githubusercontent.com/3582807/222734089-1264a90f-4de3-4a8a-95c7-564833c90abb.png)

**Comment by gskjold** [comment]
Yes, fix and reupload. No need to include secrets, it will only update items included in the config file and leave all other as is.

**Comment by shadowano** [comment]
thanks, that fixed it:)
