### ISSUE TITLE
Rename Status>Configuration

### ISSUE THREAD

**Issue by sirtet** [UtilitechAS/amsreader-firmware#471]
Just updated to 2.2.8...
The new UI looks very nice, thanks and congrats.

One little suggestion:
The __Configuration__ Block confused me for a moment, i would rename it to __Load/Save Configuration__ or __Configuration File__ or something more specific, that makes clear this is not about the Configuration, but to load/save it.

**Comment by ArnieO** [comment]
Thank you for your feedback. Good point, I agree! 
Something like **_Save/Load configuration_** would be far better.

**Comment by gskjold** [comment]
Going for "Backup & restore"
