### ISSUE TITLE
Warning in HA about "Unit of measurement" ('C' vs '°C')

### ISSUE THREAD

**Issue by michaelsidenius** [UtilitechAS/amsreader-firmware#478]
**Describe the bug**
In HA log I get the following warning:

> Entity sensor.ams_d015_temp (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement '**C'** which is not a valid unit for the device class ('temperature') it is using; expected one of ['°F', 'K', '**°C']**; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

**To Reproduce**
Run AMS READER with HA MQTT format

**Expected behavior**
No warning in HA log

**Screenshots**
N/A

**Hardware information:**
 - Country: DK
 - Meter: Kampstrup
 - Encryption enabled yes
 - AMS reader: ESP8266
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.2.8
 - MQTT: yes
 - MQTT payload type: HA
 - HAN GPIO: UART2
 - HAN baud and parity: 2400 8N1
 - Temperature sensors: **NONE**
 - ENTSO-E API enabled: no

**Additional context**

**Comment by gskjold** [comment]
Unit for temperature was changed to °C a long time ago, but I see that the sensor config is not published on the later versions
