### ISSUE TITLE
Inconsistency between recommended ESP8266 voltage in wiki and code

### ISSUE THREAD

**Issue by kimsey0** [UtilitechAS/amsreader-firmware#483]
I'm getting a red ESP indicator at 2.89V on my ESP8266. This surprised me, since [the wiki](https://github.com/UtilitechAS/amsreader-firmware/wiki/Dashboard-overview) indicates that the recommended range for ESP8266 is 2.8V - 3.5V. However, the code actually seems to require a voltage between 3.1V and 3.5 for a green indicator. Should the wiki or the code be adjusted?

https://github.com/UtilitechAS/amsreader-firmware/blob/938f9f69d1d47c0db55944ffa946a2fe4342f074/lib/SvelteUi/src/AmsWebServer.cpp#L345-L354

**Comment by gskjold** [comment]
Looking at the code, ESP32 and ESP8266 voltage have been swapped, will fix for next patch
