### ISSUE TITLE
Unable to disable encryption in settings

### ISSUE THREAD

**Issue by kibuan** [UtilitechAS/amsreader-firmware#487]
**Describe the bug**
When removing the "Meter is encrypted" tick in the settings, and then push save you get the "Saving configuration" message and then the front page loads. But when I reopen the settings page the "Meter is encrypted" is still ticked. It doesn't madder if I remove the encryption keys before I remove the tick.

**To Reproduce**
1. Go to 'Settings'
2. Enable encryption and insert encryption keys
3. Save
4. Go to 'Settings'
5. Disable encryption
6. Save
7. Go to 'Settings'
8. Confirm that encryption has not been disabled

**Hardware information:**
 - AMS reader: ESP 8266

**Relevant firmware information:**
 - Version: v2.2.9

**Comment by dbeinder** [comment]
As a workaround, you can enter 0 as the key, this will disable encryption.
