### ISSUE TITLE
Feature request: Indicate reset/reboot reason on "info" page.

### ISSUE THREAD

**Issue by ArnieO** [UtilitechAS/amsreader-firmware#491]
**Is your feature request related to a problem? Please describe.**
It is sometimes useful to know why the microcontroller reboots. ESP32 can detect this. 
See https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/reset_reason.html

**Describe the solution you'd like**
I propose to indicate reason for last reboot on the "info" page, I assume the "Device information" tile is a good place for it.

**Describe alternatives you've considered**
None...

**Comment by simenovrebo** [comment]
This would be great if it gets implemented. I see a lot of reboots after replacing a POW-U (ESP8266) with POW-U (ESP32-S2) and would like to reduce that number. The old one could have months of uptime and now I'm lucky if I get two days.
