### ISSUE TITLE
Stoped getting HAN data at 23:00 2023-03-21

### ISSUE THREAD

**Issue by franksemi** [UtilitechAS/amsreader-firmware#494]
Hi, im in Denmark. I have the Pow-K+ on my Kamstrup meter (Kamstrup DK-8660 Omnipower Three-phase meter) and it have been running without a glitch for around 6 month.

Last night at exact 23:00 it stoped getting HAN data.

Tried if I could see anything with the debug telnet, but I get the same information: "No HAN data received last 30s"

I'm running firmware v2.2.9 now and I didn't change any settings at all. I was running firmware v2.2.8 the last month, and this morning I noticed the issue. So I tried update to v2.2.9, but that didn't fix the issue.

gpk60 encryption_key and gpk61 authentication_key is still in the setting and I look through everything else.

Anyone else experienced this and have an idea what goes on?

Cheers,
Frank

![Screenshot 2023-03-22 at 19 22 32](https://user-images.githubusercontent.com/22641138/227005834-c7edc183-1516-471c-974c-ccef75777576.png)
![Screenshot 2023-03-22 at 17 15 45](https://user-images.githubusercontent.com/22641138/227005907-6349303f-d640-407a-ad8c-9bb491030f0c.png)
![Screenshot 2023-03-22 at 17 17 48](https://user-images.githubusercontent.com/22641138/227005933-42f26636-d487-4bbe-b529-c2fd59ada24d.png)

**Comment by ArnieO** [comment]
Hi Frank, 

Thank you for very thorough error report!
My guess is that your meter needs a reboot, as it seems to have stopped sending data.
Based on your report, I assume the blue blinking has also stopped; the blue part of the RGB LED of the Pow-K is directly connected to the incoming data signal. 

There is in principle two ways to reboot the meter:

1. Contact your grid company and request a remote reboot. 
2. Turn off the main fuse for a short while (I would do 30 seconds, just to be sure). The disadvantage is that power is cut, and several appliances might need to be reset (clocks etc).

We hear about these cases from time to time - meters that need restarts. 
It is uncommon but it happens.

**Comment by ArnieO** [comment]
Good to hear your meter is now running again!

And thank you for kind words! Stability is due to a combination of very well-written code (@gskjold here) and a design that takes properly into account the power management including a huge super capacitor to ensure voltage is stable while the ESP transmits on Wifi. We have both been working on the HW and firmware things over the last 2-3 years, so it has taken time and efforts to get where we are today.
