### ISSUE TITLE
Wrong future price, probably related to DST switch

### ISSUE THREAD

**Issue by cmock** [UtilitechAS/amsreader-firmware#496]
**Describe the bug**
Today, the "future energy price" (no API key) for tomorrow 23:00 is given as -157€/kWh. The prices for the hours up to that point look reasonable.

As this is the daylight saving time switch weekend, I guess this is related.

**To Reproduce**
Look at the Web UI

Tried rebooting and a different browser, same result.

**Screenshots**

![Screenshot_20230325_165732](https://user-images.githubusercontent.com/2141141/227728197-af891088-4a2c-4bea-8315-da7cd0996b0a.png)

**Hardware information:**
 - Country: Austria
 - Meter: Sagemcom T210D
 - Encryption enabled yes
 - AMS reader: ESP32
 - M-bus adapter (if applicable): resistive divider

**Relevant firmware information:**
 - Version: 2.2.9
 - MQTT: yes
 - MQTT payload type: Raw (full)
 - HAN GPIO: UART2
 - HAN baud and parity: 2400 8E1
 - Temperature sensors -
 - ENTSO-E API enabled: yes (no key)

**Comment by gskjold** [comment]
Yep... If you reboot now, you will at least get rid of that rogue negative bar. Working on a fix for the clock skew that occurs in the graph.

**Comment by gskjold** [comment]
I'm leaving this screenshot here as a reference for tomorrow, have to check if the price aligns after entering DST. Price zone NO2*1.25

![Screenshot from 2023-03-25 19-15-24](https://user-images.githubusercontent.com/4446828/227734492-26b31224-e0a4-4c4d-91b5-dbf724a3da90.png)

**Comment by gskjold** [comment]
Nope, this needs more work
