### ISSUE TITLE
Only show half the labels on chart x-axis on small screens

### ISSUE THREAD

**Issue by FrankMunch** [UtilitechAS/amsreader-firmware#499]
To adapt to small screens where the labels on the graphs get on top of each other: Only use even numbers on graphs with time (future price and consumption). Only use odd nymbers on graphs with date (montly consumption).

Suggestion to record power down time: Constantly store a current timestamp, if a power down occur, create a power down event (list) using the power up timestamp (difference between the two). 
I have a reader in a cabin, I suspect power occational power breaks take place.

**Comment by gskjold** [comment]
> To adapt to small screens where the labels on the graphs get on top of each other: Only use even numbers on graphs with time (future price and consumption). Only use odd nymbers on graphs with date (montly consumption).

This is a good idea, I will look into implementing this

> Suggestion to record power down time: Constantly store a current timestamp, if a power down occur, create a power down event (list) using the power up timestamp (difference between the two). I have a reader in a cabin, I suspect power occational power breaks take place.

This would wear out the flash memory quite quickly, so I'm afraid this wont be an option.
