### ISSUE TITLE
Sky high consumption.

### ISSUE THREAD

**Issue by Spexdallas** [UtilitechAS/amsreader-firmware#500]
My consumption all of a sudden is sky high, dont know why.

**Hardware information:**
 - Country: [Sweden SE3]
 - Meter: [Kamstrup 8660]
 - Encryption enabled [no]
 - AMS reader: [Pow-k esp8266]
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [2.2.11]
 - MQTT: [yes]
 - MQTT payload type: [Homeassistant]
 - HAN GPIO: [GPIO12]
 - HAN baud and parity: [2400 8N1]
 - Temperature sensors [No]
 - ENTSO-E API enabled: [
[debug.txt](https://github.com/UtilitechAS/amsreader-firmware/files/11092649/debug.txt)
![Amsreader](https://user-images.githubusercontent.com/120919352/228323413-81c9f7bd-04e9-40c1-b64e-baf0f265152a.jpg)
no]

**Comment by gskjold** [comment]
Interesting, your consumption on the graphs seems to be really high in general, is this a large installation?

**Comment by Spexdallas** [comment]
This is a normal house with normal consumption i think, i will post a screenshot from my provider aswell.
![förbrukning](https://user-images.githubusercontent.com/120919352/228454198-bf4b1aa0-85da-44e7-89b9-d6d324025dcf.JPG)

**Comment by ArnieO** [comment]
So there is a 10x error in the daily consumption, so apparently two issues here:

- Single hourly measurement point going crazy
- 10x error 

@gskjold : We have seen some cases before where single graph points "go crazy". Could there be a rollover data type error here?

**Comment by gskjold** [comment]
Could be some rollover issue here, needs investigation. 

But also, you need a 0.1x multiplier on kwh:
![Screenshot from 2023-03-29 08-19-49](https://user-images.githubusercontent.com/4446828/228458289-2e82b23c-341b-4298-99fd-6700f5d642fe.png)

**Comment by Spexdallas** [comment]
Is there a way to reset the statistics in the pow-k? I reverted back to 2.2.10 and now it looks like i used to at least in Homeassistant.

**Comment by gskjold** [comment]
Pretty sure I have found the reason for this. Fix will be included in next patch

**Comment by Spexdallas** [comment]
Everything looks like it should now when reverted back to 2.2.10 + adding multiplier.
Will run this fw for a month and evaluate.
