### ISSUE TITLE
New meter firmware and no HAN-connection

### ISSUE THREAD

**Issue by jonthe101** [UtilitechAS/amsreader-firmware#503]
Hello,
I've been running amsreader on a Pow-K+ with a kamstrup meter for a while.
I recently got an email  from my energy company saying that they have upgraded the firmware in my energy meter:
"Your meter now has the correct firmware and is now using the P1 protocol".

Since the upgrade my ams-reader isn't getting any data from the HAN-port.
Does anyone know why this is? Is my meter now running an unsupported protocol?

**Hardware information:**
 - Country: Sweden
 - Meter: Kamstrup
 - Encryption enabled: no
 - AMS reader: Pow-K+

**Relevant firmware information:**
 - Version: 2.2.11
 - HAN baud and parity: 2400 8N1

**Comment by gskjold** [comment]
Even though data have been changed to P1, it should still be supported. I am not sure how Kamstrup meters with P1 are configured, but it could be that you need to try 115200 baud 8N1 in meter configuration. If not, change it back and do a debug session if you can: https://amsleser.no/blog/post/24-telnet-debug

**Comment by ArnieO** [comment]
These meters are supposed to be equipped with a Kamstrup HAN-P1 module. We do not know if that module inverts the data signal, so you might also need to activate "Inverted":
![image](https://user-images.githubusercontent.com/10295178/228451690-35ba1bb0-2419-4524-8b52-e6c4a60926f2.png)

Note: 
An other customer in Sweden with a Pow-K+ was not successful reading P1 protocol, he had to contact the grid company and request them to revert back to HAN-NVE protocol. The grid company can do this in the VisionAir software they use to remote control the meters:
![image](https://user-images.githubusercontent.com/10295178/228452281-97a29dc8-f4d5-4437-8276-11db81dfba11.png)
(clip from [this Kamstrup document](https://koce1-kamstrup.ocecdn.oraclecloud.com/content/published/api/v1.1/assets/CONTAAA62C8B611D4C4EB3186FD81AEE0152/native/5512-2584_EN_C1_OMNIPOWER+HAN+interface+specification.pdf?channelToken=ed241bbb18f444908a8fc9ed97ca5d5b))

**Comment by jonthe101** [comment]
Thanks for the responses. I have tried inverting the signal with no success.
I will try debugging with telnet when I get off work today 👍

**Comment by ArnieO** [comment]
> Thanks for the responses. I have tried inverting the signal with no success. I will try debugging with telnet when I get off work today 👍

And that was at baud rate 115 200 baud? The baud rate is a significant difference between P1 and the other protocols.

**Comment by jonthe101** [comment]
> > Thanks for the responses. I have tried inverting the signal with no success. I will try debugging with telnet when I get off work today 👍
> 
> And that was at baud rate 115 200 baud? The baud rate is a significant difference between P1 and the other protocols.

Yes, triend both 2400 and 115200 inverted/non inverted.

I just tried debugging throught telnet and i'm only getting:

(W) (errorBlink)(C0) No HAN data received last 30s, single blink
(D) Serving /data.json over http...
(W) (errorBlink)(C0) No HAN data received last 30s, single blink
(D) Serving /data.json over http...
(W) (errorBlink)(C0) No HAN data received last 30s, single blink
(D) Serving /data.json over http...
(W) (errorBlink)(C0) No HAN data received last 30s, single blink

Seems to be pretty quiet.. Maybe HAN is closed and need to be re-opened by the grid company?

**Comment by ArnieO** [comment]
Can you se any blue blinking on the LED? If the baud rate is 115200 it is very short - but visible. 

I am starting to suspect that the HAN port of your meter is no longer activated. They may have to re-activate it after the firmware upgrade?

**Comment by cappadanna** [comment]
Hi,

I have the same meter and my energy company just changed from HAN-NVE to HAN-P1 and all I had to do was to change baud rate to 115200

**Comment by ArnieO** [comment]
> Hi,
> I have the same meter and my energy company just changed from HAN-NVE to HAN-P1 and all I had to do was to change baud rate to 115200

Thank you very much for that very useful piece of information!

**Comment by cappadanna** [comment]
> > Hi,
> > I have the same meter and my energy company just changed from HAN-NVE to HAN-P1 and all I had to do was to change baud rate to 115200
> 
> Thank you very much for that very useful piece of information!

Well I thought since I have the same setup it would help rule out one when fault finding but ok then…

**Comment by ArnieO** [comment]
> > > Hi,
> > > I have the same meter and my energy company just changed from HAN-NVE to HAN-P1 and all I had to do was to change baud rate to 115200
> > 
> > 
> > Thank you very much for that very useful piece of information!
> 
> Well I thought since I have the same setup it would help rule out one when fault finding but ok then…

I hope you did not take that as irony from my side? 😅 

It is indeed very useful information for us, as this is the first confirmation I have seen that a Pow-K+ set to 115 200 baud will work as intended on a Kamstrup configured for HAN-P1. So it was a very sincere Thank you! 😃

**Comment by ArnieO** [comment]
> I did at the moment but now I realize I was completely wrong. So sorry about that 😞
> 
> My working setting are 115200baud, 8N1, not inverted. I am powering the p1 module with external 5v for it to work

No worries! 
But I seem to have misunderstand your setup - I thought you too have a Pow-K+?

**Comment by cappadanna** [comment]
> No worries! But I seem to have misunderstand your setup - I thought you too have a Pow-K+?

I have a slimmelezer but i have flashed it with ams-reader firmware

https://www.zuidwijk.com/product/slimmelezer-plus/

**Comment by jonthe101** [comment]
Sorry for the silence from me.
I never got it to work with the P1 protocol and had to ask them to revert back to HAN-NVE.

**Comment by ArnieO** [comment]
**UPDATE**

In order to get push data from Kamstrup Omnipower meters that are configured as P1 port, the DATA_IN pin in the 6-pin connector in the expansion bay needs to be pulled low (to GND). 

If you have a P1-configured Kamstrup, you can modify your Pow-K by soldering a small strap to the board, like this:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/46cf6064-4ac6-429b-a5c6-9db6d23a8fd4)

On the next generation Pow-K boards, we will pull the DATA_IN line to the microcontroller, so that this can be handled without such modification being needed. Next generation will be in sale somewhere this autumn/winter (when current stock is depleted). The product description will be updated to clarify this.

**Comment by StarkJohan** [comment]
No need for a pull down resistor?

**Comment by ArnieO** [comment]
> No need for a pull down resistor?

No, after having studied the internals of a HAN-P1 module we have concluded that it should not be necessary. 
This has been tested by a customer in Sweden, and it is working. 
It might be necessary to increase the reception buffer size due to the short duration between datagrams (1 second). 
Newest firmware versions has an option for selecting larger buffer:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/62a8059e-4126-4b57-8c73-c58d8676174a)
