### ISSUE TITLE
Feature request: Tooltip on Up time

### ISSUE THREAD

**Issue by rogerthn2019** [UtilitechAS/amsreader-firmware#504]
**Is your feature request related to a problem? Please describe.**
Not a problem but it would be nice to see boot time.

**Describe the solution you'd like**
Tooltip YYYY-MM-DD HH:MM:SS on Up time
![image](https://user-images.githubusercontent.com/57598997/228450317-adc7801b-a276-41e1-a569-bb799f1ab0c0.png)

**Comment by gskjold** [comment]
Nice, I like the idea

**Comment by ArnieO** [comment]
Potentially quite useful for debugging!
Maybe better than tooltip would be to add boot time here?
![image](https://user-images.githubusercontent.com/10295178/228456011-f0c69c53-4e89-4bd4-a430-ca8d013acf52.png)

**Comment by gskjold** [comment]
> Maybe better than tooltip would be to add boot time here?

Agree on this one
