### ISSUE TITLE
Sensors lacking state

### ISSUE THREAD

**Issue by varmforsm** [UtilitechAS/amsreader-firmware#508]
After installing AMS 2.2.11 there seems to be a problem in the state of the sensors when it reports data to HA. For a number of sensors, it is reporting that a blank ('') state is not allowed. Seems to have happened after installing 2.2.11 yesterday.

**To Reproduce**
0. Prerequisite: Running the Pow-K+ in integration with HA.
1. Go to 'Developer Tools'
2. See list of errors regarding state of sensors (see "Screenshots" below). 

Looking at the code in your repo, it looks like this is an intentional change, so - am I supposed to correct something on my side?
https://github.com/UtilitechAS/amsreader-firmware/commit/0178dc41845bdb19601ab905bb482ceba42768aa (search for "Current hour used", for example).

**Expected behavior**
Didn't expect any errors after the upgrade.

**Screenshots**
![image](https://user-images.githubusercontent.com/4803267/229087690-188e3d8f-5245-4f64-9aad-7ac4e649d364.png)

**Hardware information:**
 - Country: Sweden
 - Meter: Kamstrup
 - Encryption enabled: No
 - AMS reader: Pow-K+, HAN port reader for Kamstrup meters

**Relevant firmware information:**
 - Version: 2.2.11
 - MQTT: Yes
 - MQTT payload type: HomeAssistant
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: 2400 8N1

**Comment by gskjold** [comment]
Will be fixed in next patch
