### ISSUE TITLE
Test and release of v2.2.12

### ISSUE THREAD

**Issue by gskjold** [UtilitechAS/amsreader-firmware#509]
Currenctly testing next version before release

**Comment by tronde-ams** [comment]
Date for last boot is one month off. 
![Skjermbilde (1771)](https://user-images.githubusercontent.com/97398751/229296441-1de17918-decd-4707-8979-eabbdb9a3368.jpg)

**Comment by gskjold** [comment]
Hah, funny. Will fix :)
