### ISSUE TITLE
When restoring a backup, the password is restored as both username and password

### ISSUE THREAD

**Issue by jrhansen** [UtilitechAS/amsreader-firmware#510]
With version 2.2.12 it seems that when restoring a configuration backup with secrets included, the password in the backup is restored as both the username and the password.

**Comment by ArnieO** [comment]
Huh, strange - thank you for reporting. Is this the "Security" user/password, or is it for Wifi?

**Comment by jrhansen** [comment]
No problem. I'm glad if I can help fight some bugs :)
