### ISSUE TITLE
Real time calculation Export month wrong value for the price

### ISSUE THREAD

**Issue by PerBuch54** [UtilitechAS/amsreader-firmware#511]
Real time calculation Export month wrong value for the price, the kWh looks right but thr price seems to show the day value.

**Comment by ArnieO** [comment]
Can someone else here with solar panel or wind turbine check if they see the same?

**Comment by PerBuch54** [comment]
now it shows Month 3.9 kWh 1.0 DKK, that is wrong the kWh price has not ben down to 0,25 DKK

**Comment by gskjold** [comment]
This is a precision error. Cost/income per month is stored without decimals, so the precision is lost. Need to increase the range and precision of these values

**Comment by PerBuch54** [comment]
It is counting up now, seems like the first 2 days of the month did not get included.
The month stored without decimals are ok.

**Comment by PerBuch54** [comment]
![image](https://user-images.githubusercontent.com/128969759/230087083-dcf21abc-83cc-448a-9728-78b9d6586e2f.png)

It is here, clear to se that the month are wrong.

**Comment by PerBuch54** [comment]
![image](https://user-images.githubusercontent.com/128969759/230087721-df445210-a65b-4219-ae03-797cb5648fde.png)
 It is here, clear to se that the month value are wrong.

**Comment by PerBuch54** [comment]
today before production starts Month 1.2 kWh 0.0 DKK
yesterday the day production had a DKK value. Seems like the first  two days of the month are sat to zero.

**Comment by PerBuch54** [comment]
Seems like an error in Energy use last month (kWh), the last two days say 10 and 8 KWh, less than half the real value.

**Comment by gskjold** [comment]
This is interesting, you are the second person to report such a problem. This obviously needs some investigation

**Comment by ArnieO** [comment]
> Seems like an error in Energy use last month (kWh), the last two days say 10 and 8 KWh, less than half the real value.

Did you have any (known) Wifi issues in the period? 
Do you have "Auto reboot on connection problem" activated?

**Comment by gskjold** [comment]
Checking my own data, it seems like I have a similar problem, will open new issue on this

**Comment by PerBuch54** [comment]
ArnieO no wifi problems (i am living off making wifi) "Auto reboot on connection problem" not activated.
