### ISSUE TITLE
"Real time calculation" window missing New Lines

### ISSUE THREAD

**Issue by michaelsidenius** [UtilitechAS/amsreader-firmware#514]
**Describe the bug**
The "Real time calculation" window is missing New Lines after the values. Does not align left in a column.

**To Reproduce**
Open the webpage with "Real time calculation" (Realtime) enabled

**Expected behavior**
The values in a nice left aligned culomn.

**Screenshots**
See screenshot

**Hardware information:**
 - Country: DK
 - Meter: Kampstrup
 - Encryption enabled yes
 - AMS reader: ESP8266 D1
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: e.g. 2.2.12
 - MQTT: yes
 - MQTT payload type: HA
 - HAN GPIO: UART2
 - HAN baud and parity: 2400 8N1
 - Temperature sensors: no
 - ENTSO-E API enabled: no

**Additional context**

![Screenshot from 2023-04-04 15-57-20](https://user-images.githubusercontent.com/2191937/229818478-1a959c9a-0ef9-40f4-a0ae-db666b88fd48.png)

**Comment by gskjold** [comment]
Interesting bug, will fix
