### ISSUE TITLE
After upgrading to 2.2.12 - the HAN settings in Hardware gone missing.

### ISSUE THREAD

**Issue by NAVspecialist** [UtilitechAS/amsreader-firmware#520]
After upgrading from a previous version of ams2mqtt then HAN options in the hardware settings are missing.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/33704755/230905237-c13fb880-dfb7-483c-99ea-64bf257d62d4.png">

An upgrade to the new 2.2.13 did not fix it either.

ESP8266 - generic version
Kamstrup meter in Denmark (Radius-area - DK2)
Encryption enabled and worked previously.
2400 N81 in settings (Tried to change to a higher baud speed but it gave no HAN settings.

Any good suggestions?

**Comment by ArnieO** [comment]
Which version did you upgrade from? If it was 2.1.x a factory reset might be needed. 
You can download and later upload current config and historical data from the Info screen.
