### ISSUE TITLE
Web GUI legends uses local time zone from phone / computer 

### ISSUE THREAD

**Issue by tsh1956** [UtilitechAS/amsreader-firmware#521]
**Describe the bug**
Web GUI legends reflects current local device system time on two several elements:  Future energy price (NOK) and Energy use last 24 hours (kWh)

**To Reproduce**
I am currently running the app on my laptop in  Colombia, South America. The laptop is set to local system time,  a -7 hour time difference from the AMS that currently runs in the norwegian time zone.  
To reproduce, set a different time zone on your local device, and in my case, legends shows 7 hours behind actual time in Norway. 
**Expected behavior*
The GUI should always reflect local time zone set in the settings panel.

**Screenshots**
n/a

**Hardware information:**
 - Country: [Norway]
 - Meter: [Aidon]
 - Encryption enabled [no]
 - AMS reader: [ Pow-U]
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [2.2.13]
 - MQTT: [no]
 - MQTT payload type: [ JSON]
 - HAN GPIO: [no]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [no]
 - ENTSO-E API enabled: [no]

**Additional context**
n/a

**Comment by gskjold** [comment]
Was sort of waiting for this to be pointed out, will fix :)
