### ISSUE TITLE
v2.2.13 unable to connect to SSID with special characters in it.

### ISSUE THREAD

**Issue by bjornsivertsen** [UtilitechAS/amsreader-firmware#526]
**Describe the bug**
I have a WiFi SSID with the character Ø in it, and since AMS latest update, it is unable to connect to it.
If I create another SSID without the special character, I have no issue.

When I access it locally, it shows my SSID without the Ø character, but instead a white space.

It has previously worked fine for more than 2 years.

What gives? :)

**Comment by ArnieO** [comment]
The character filter was changed, and is maybe too restrictive now. --> @gskjold?

**Comment by gskjold** [comment]
Yep, I thought I fixed this, but is still a problem. Will fix for next patch
