### ISSUE TITLE
Missing unit of measurements on two sensors exposed to Home Assistant through MQTT

### ISSUE THREAD

**Issue by bjornsivertsen** [UtilitechAS/amsreader-firmware#530]
**Describe the bug**
It appears the two sensors tqo and tqi are missing a unit of measurement, and it throws a warning

**Expected behavior**
It appears HA wants unit of measurement for Accumulated Reactive Import/Export to be either 'MJ', 'kWh', 'GJ', 'MWh', 'Wh'

**Screenshots**

**Additional context**
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:669
Integration: Sensor (documentation, issues)
First occurred: 19 April 2023 at 21:12:12 (2 occurrences)
Last logged: 19 April 2023 at 21:12:12

```
Entity sensor.ams_c23f_tqo (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kWh', 'GJ', 'MWh', 'Wh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
Entity sensor.ams_c23f_tqi (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('energy') it is using; expected one of ['MJ', 'kWh', 'GJ', 'MWh', 'Wh']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
```

**Comment by gskjold** [comment]
Thanks, the issue here is that the reactive unit would be "kvarh", which is not supported. I will look into how we should solve this
