### ISSUE TITLE
Remove download link when installed and latest version are same

### ISSUE THREAD

**Issue by henriklund** [UtilitechAS/amsreader-firmware#534]
As a suggestion, whenever the installed and the latest version are the same, the link for installing latest version should be grayed out / removed (whichever is easier to implement).
![image](https://user-images.githubusercontent.com/8402745/233799200-a832cccb-2ecf-4db5-b3e4-9a79b7573cdf.png)

**Comment by ArnieO** [comment]
Nice detail improvement request - I agree! 👍
