### ISSUE TITLE
No time/date information after 2.2.14 upgrade

### ISSUE THREAD

**Issue by tubbelino** [UtilitechAS/amsreader-firmware#536]
**Describe the bug**
After 2.2.14 upgrade NTP time/date stopped working

**To Reproduce**
Install or upgrade to version 2.2.14 on Wemos D1 mini.

**Expected behavior**
Time and date is not updated in AMSreader

**Screenshots**
![2023-04-23 15_59_09-AMS reader](https://user-images.githubusercontent.com/47715797/233845000-90b97ad1-672e-4e49-9baf-001e1389b57f.png)

![2023-04-23 15_59_47-AMS reader](https://user-images.githubusercontent.com/47715797/233845011-9818e128-cb2f-40f6-83a7-d26aeae79574.png)

**Hardware information:**
 Tested two types of Wemos D1 mini, one original and one clone.

**Relevant firmware information:**
 - Version: 2.2.14

**Additional context**
Packet sniffing shows strange DNS query output from the AMS reader, pcap file is available.
Tested with both DHCP and Static IP and different ntp servers.

![2023-04-23 16_19_27-packetcapture (4) cap](https://user-images.githubusercontent.com/47715797/233845689-34769fa1-1e94-4847-ac94-4cb0ba8b28f0.png)

**Comment by henriklund** [comment]
I had a similar experience (ie. clock not being updated) after a downgrade from a beta version (trying to troubleshoot frequent reboots) to v2.2.13. I did not think of running a WireShark to troubleshoot. Since I managed to brick the device within the same hour I had to resort to reflash the device (ESP8266). After the reflash, everything was OK.

**Comment by ArnieO** [comment]
Interesting comment @henriklund: I also went from a beta version to 2.2.14, and now have the clock error described in this thread: https://github.com/UtilitechAS/amsreader-firmware/issues/535.

**Comment by ArnieO** [comment]
I took my Pow-K out of the meter and did a factory reset - and it now does not display date/time at all.
So it looks like the date/time in the top bar is no longer from internet, but from the meter. 
![image](https://user-images.githubusercontent.com/10295178/233944892-0d22bba1-7a0a-4432-9461-dafdb8ba2795.png)

**Comment by gskjold** [comment]
Are all of you on ESP8266?

**Comment by gskjold** [comment]
After rebooting my devices, this also happens here...

**Comment by gskjold** [comment]
Test version below:

[esp32solo.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11311113/esp32solo.zip)
[esp32.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11311114/esp32.zip)
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11311115/esp8266.zip)
[esp32c3.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11311116/esp32c3.zip)
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11311117/esp32s2.zip)

**Comment by ThorAlex87** [comment]
I'll try the test version, mine has been 15 minutes late since I updated yesterday.

**Comment by tubbelino** [comment]
Test version looking good so far for me!

Wemos D1 mini (ESP8266EX)
