### ISSUE TITLE
Declare MQTT version in configuration FAQ

### ISSUE THREAD

**Issue by ruzko** [UtilitechAS/amsreader-firmware#537]
**Is your feature request related to a problem? Please describe.**
I can't find info on what MQTT client version the firmware uses. There are different options available to the broker depending on which versions connected clients are running.

**Describe the solution you'd like**
Write what MQTT version is used [here](https://github.com/UtilitechAS/amsreader-firmware/wiki/MQTT-configuration).

**Describe alternatives you've considered**
I could just live in blissful ignorance, since it does currently work. Albeit possibly not optimally.

**Additional context**
Absolutely love the hardware and firmware, I've recommended it to privacy conscious friends of mine as well.

**Comment by gskjold** [comment]
Thank you for your kind words. Sorry I am slow to update the wiki with this simple change! Updated now, currently using library implementing MQTT 3.1.1
