### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by gskjold** [UtilitechAS/amsreader-firmware#540]
There have been quite a few questions about this. Currently being implemented by one of our team members. I suspect a test version will be posted in the near future.

**Comment by ElMyggo** [comment]
Nice :-) 
(I have my own build with dark mode but its not perfect... and have to change everything if i want to install a new version...)

**Comment by gskjold** [comment]
Pull request merged. Modified to store the configuration on flash. Build attached. We are happy to get some opinions on color palette. This change will be part of the ongoing development with v2.3

[esp32.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11355956/esp32.zip)
[esp32c3.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11355957/esp32c3.zip)
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11355959/esp32s2.zip)
[esp32solo.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11355960/esp32solo.zip)
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/11355961/esp8266.zip)

**Comment by ElMyggo** [comment]
I build my own file from dev 2.3 files and flash direct from Visual studio to my test esp32 and i cant save the darkmode status, everytime i open config its disabled.. must i use your build?
![darkmode](https://user-images.githubusercontent.com/111691693/235218453-f625fc7c-a10a-45ea-a64d-5d69f8f96f06.jpg)

**Comment by gskjold** [comment]
Should definitely work building your own, but I can see that you dont have the latest commit, please update your branch and build again

**Comment by ArnieO** [comment]
Looks great! 👍

**Comment by ElMyggo** [comment]
Love the dark mode! 
but i like the combo black/orange so i use photoshop to test!
(text and number should be black when orange is the background otherwise white)
Possible to change color in config would be a blast!!

![darkmodescreen_orange](https://user-images.githubusercontent.com/111691693/235986333-82687f0c-2dab-4711-a44d-b510273780cd.jpg)

**Comment by ArnieO** [comment]
> Possible to change color in config would be a blast!!

I disagree, as the config page is already quite crowded.

**Comment by ElMyggo** [comment]
> I disagree, as the config page is already quite crowded.

Yes that's true

**Comment by spacecosmos** [comment]
Not a solution, but merely an alternative option. I use the Opera web browser on my phone and it has an option to force dark mode on all pages/sites I'm browsing. And it works (and looks) beautifully! :)

A few examples:

![SmartSelect_20230930_074138_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/39840178-3f43-4316-a938-b3e3e816d735)

![SmartSelect_20230930_074215_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/980e5756-074e-4f0a-8421-efab13235734)

![SmartSelect_20230930_072005_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/ad4b69f5-4eb3-4340-bae0-3f2a93a9185e)

Maybe an option to toggle dark mode on/off on the bar would be nice (at some point):

![Polish_20230930_080146430](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/334ba01f-ee72-4fcd-89d6-239e187e4ffd)

Keep up the good work! :)
