### ISSUE TITLE
Green color for exported energy in plots

### ISSUE THREAD

**Issue by ehorvat1** [UtilitechAS/amsreader-firmware#544]
Hi, as I work on a fork of this great project I have a easy to do suggestion to improve the energy usage plots in the WebUi.

It would be nice to have the "exported" power shown as green bars in the day/month plots.

For Rev. 2.2.15 this could be accieved by:
1) Change line 91 in file BarChart.svelte from: fill="{point.color}" 
     to: fill="{point.color2}"  
2) For dayplot:
     Insert 2 times a new line right before e.g. line 32 which reads:   color: '#7c3aed'                
     insert this:    color2: '#407038', 
     
3) For monthplot:
     Insert 2 times a new line right before e.g. line 34 which reads:   color: '#7c3aed'                
     insert this:    color2: '#407038',

Hex color code #407038 is a kind of darkish green.
And to make this consistent also the lables could be done in color2....up to you.

Kind regards and keep up this fine project, Engelbert

**Comment by gskjold** [comment]
I think we will go over the general color palette for v2.3, this is good input, thank you!
