### ISSUE TITLE
graph for energy usage in last 24 hours - not updated

### ISSUE THREAD

**Issue by KlavsKlavsen** [UtilitechAS/amsreader-firmware#546]
**Describe the bug**
live-data seems to have stopped being readable from meter?
it complains about HAN - no data last 30 seconds..
But the graphs are still showing for last 24 hours and last month.. even though no numbers have been added - so they are wrongly NOT being updated to be empty (which they really should be when no data is there).
I only realized - because the numbers kept showing that I had used power at a specific time - where I know I had not.

**Expected behavior**
If no data is received (which is my assumption of whats going on - then "last 24 hours" - should start to show EMPTY bars - for the hours where no data was received - making it much more clear when the problem started - and also that there truely is no data.

**Screenshots**
![image](https://user-images.githubusercontent.com/2737885/235087849-3c894c99-0c5f-4fe1-86ae-331ef9c1afdc.png)

**Hardware information:**
 - Country: Denmark
 - Meter: powk (is that enough info?)
 - Encryption enabled yes
 - AMS reader: Pow-K - hw purchased in ams webstore.

**Relevant firmware information:**
 - Version: 2.2.15
 - MQTT: Yes (was enabled but failing as receiver was down - have removed "server" field - which seems to be enough to disable it - so its now grey.
 - MQTT payload type: JSON
 - HAN GPIO: [e.g. GPIO5] - where do I see this?
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: none afaik
 - ENTSO-E API enabled: yes

**Additional context**
This most likely happened with a liveupdate - but I cannot tell - as the graphs cheated me for a long time (because I have a battery and my usage thus looks very much the same every day - until summer started and I started NOT charging the battery at all).

**Comment by KlavsKlavsen** [comment]
Sorry - thats my bad reading of config.. it says 8N1 already.

**Comment by ArnieO** [comment]
> Sorry - thats my bad reading of config.. it says 8N1 already.

OK, then it is something else. What do you see on the LED? 

**If there is no blue blinking each 10 seconds** there is no data from the meter. 
We see from time to time that Kamstrup meters stop transmitting, and needs a reboot. 
Not often - we have had I think around 5 customers that needed to get this done. 
In that case, two alternatives: 

1. Call the grid company and request a remote reboot
2. If your meter is behind the main fuse/breaker, open the main fuse/breaker for 30 seconds and then close it again. But I'm not sure that works in Denmark, I think the meter is often on the grid side of the main fuse/breaker.

**Comment by KlavsKlavsen** [comment]
it blinks red every few seconds.. I could try and pull it out and insert it in the meter again?

**Comment by ArnieO** [comment]
Single blinks only?
![image](https://user-images.githubusercontent.com/10295178/235125823-5b1ffcbd-2474-4ac7-a4fe-13fd5439634a.png)

**Comment by KlavsKlavsen** [comment]
single flash - yes.

**Comment by ArnieO** [comment]
See updated comment above; sorry for hitting the button before it was ready...

**Comment by ArnieO** [comment]
Your meter seems to need a reboot.

**Comment by KlavsKlavsen** [comment]
I have re-inserted it, and hopefully that helps. 

The graphs just staying with "latest data" - and hence not showing data is actually missing (even though it says its data from last 24 hours - which clearly then isn't) - is a bug - and actually caused me to not notice for a very long time.. it was not until I started wondering about why it stayed exactly the same - when I had reconf'ed charging times for my batteri that I noticed :(

**Comment by ArnieO** [comment]
The blue part of the LED is directly connected to incoming data, not controlled by the microcontroller. We made it like that so that it is a clear indicator of incoming data, independent of the firmware in the microcontroller. 

Do you not get a red warning on the main page that tells you there is an error in incoming data?

**Comment by KlavsKlavsen** [comment]
it says: HAN: No HAN data received last 30s
I was not aware that HAN data == measurements from Meter - and just because it didn't work "last 30 seconds" - doesn't mean that it won't work in the next 30s.. so I did not give it much attention - as the graphs were there (I thought).

Empty/NULL graph bars - would be a more clear indication - and also make the graph actually reflect reality :)

**Comment by ArnieO** [comment]
> it says: HAN: No HAN data received last 30s I was not aware that HAN data == measurements from Meter - and just because it didn't work "last 30 seconds" - doesn't mean that it won't work in the next 30s.. so I did not give it much attention - as the graphs were there (I thought).
> 
> Empty/NULL graph bars - would be a more clear indication - and also make the graph actually reflect reality :)

OK, understood! And I agree, there should be a stronger/clearer message when data from the meter is permanently gone. Let us see if @gskjold can improve that on next code revision!

**Comment by gskjold** [comment]
Agree, will fix in the future

**Comment by gskjold** [comment]
Next patch will clear graph values if there is no data from the meter

**Comment by KlavsKlavsen** [comment]
rebooting meter worked.

**Comment by ArnieO** [comment]
> rebooting meter worked.

Good - and thank you for giving feedback! 👍
