### ISSUE TITLE
Show fractional digits on month plot

### ISSUE THREAD

**Issue by kimsey0** [UtilitechAS/amsreader-firmware#547]
The _Energy use last month (kWh)_ currently rounds the labels to show no fractional digits. For low-usage households, this means the numbers are pretty imprecise: Does "3" mean 2.5 or 3.49? There's a 40% difference between those two numbers.

![Monthly usage graph showing numbers between 3 and 6.](https://user-images.githubusercontent.com/984760/235109892-60eb94c6-7591-48e8-ae7d-44d027c36f86.png)

I assume the reason is the limit on space for the label, but perhaps it could show a fractional digit only for numbers below 10? That is, maybe 

https://github.com/UtilitechAS/amsreader-firmware/blob/8b97544a2c7d4ecbaf3d4fa7f38b9090afe68250/lib/SvelteUi/app/src/lib/MonthPlot.svelte#L30

could change to `label: imp.toFixed(imp < 10 ? 1 : 0)`. Alternatively, it could use the new [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) API with `maximumSignificantDigits` set to 2 or 3.

There's also the option of adding a more precise value as a mouse-over text, maybe even in addition to the change above?

**Comment by ArnieO** [comment]
Thank you for the proposition - I think it is a good idea to have a minimum of two digits.
And if mouseover (with full resolution) is feasible (@gskjold ?), that would also be a nice improvement.

**Comment by gskjold** [comment]
Agree! I've just never seen single digits on days :smile:

**Comment by kimsey0** [comment]
Thanks a lot, @gskjold!
