### ISSUE TITLE
Last day of april and first day of may have wrong data in graph

### ISSUE THREAD

**Issue by gskjold** [UtilitechAS/amsreader-firmware#552]
There seems to be an error where the month graph have wrong numbers for 30.april and 1.may. For me personally, it seems that a lot of the consumption from 30.apr have been included in 1.may.

Please report any similar findings

**Comment by gskjold** [comment]
I'm realizing that it does not update values at all, and this is in fact values for 30.mar and 1.apr! Emergency release is coming soon!

**Comment by gskjold** [comment]
Keeping this open a while for new visitors who have discovered this issue. This is fixed in v2.2.16

**Comment by ArnieO** [comment]
**Note:**
The bug will lead to identical measurements being shown in the monthplot until v2.2.16 is installed, and the device has passed **_two_** midnights.

**Comment by SirJMD** [comment]
> I'm realizing that it does not update values at all, and this is in fact values for 30.mar and 1.apr! Emergency release is coming soon!

Impressively fast response! :) 2.2.16 fixed it! Well done.
