### ISSUE TITLE
Month and day usage are equal

### ISSUE THREAD

**Issue by Sommerdal-ufm** [UtilitechAS/amsreader-firmware#554]
**Describe the bug**
The same value are shown for day and month value

**To Reproduce**
1. Main panel
2. Scroll down

**Expected behavior**
Different values except 1. day of month

**Screenshots**

**Hardware information:**
 - Country: Denmark 
 - Meter: Kamstrup 
 - Encryption enabled [yes/no] yes
 - AMS reader: [e.g. Pow-U, ESP32 etc] pow-k+
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [e.g. 2.1.0] 2.1.15/16
 - MQTT: [yes/no] yws
 - MQTT payload type: [e.g. JSON] json
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [yes/no] yes

**Additional context**

**Comment by gskjold** [comment]
Could you add a screenshot please?

**Comment by ArnieO** [comment]
Yes, something is certainly wrong here!
Firmware v2.2.16:
![image](https://user-images.githubusercontent.com/10295178/235866674-6b12f831-6bf3-46ff-934b-565766a698a8.png)
![image](https://user-images.githubusercontent.com/10295178/235867033-425f2f9f-cfd9-4347-9ced-ff0671f7af5d.png)

**Comment by gskjold** [comment]
This is a side effect of issue #552, data for the graph was not updated since 30apr and is unfortunately lost. An average have been set for the three days

**Comment by Sommerdal-ufm** [comment]
Here is my observation 
![Screenshot_2023-05-03-20-48-21-19](https://user-images.githubusercontent.com/54624988/236015042-40b895d8-4b01-4a13-8f20-db20d0a4de33.jpg)

**Comment by gskjold** [comment]
Found the issue, patch will be released after some more testing
