### ISSUE TITLE
Use pricing from energi data service for home assistent 

### ISSUE THREAD

**Issue by Sommerdal-ufm** [UtilitechAS/amsreader-firmware#555]
**Is your feature request related to a problem? Please describe.**
Current and future price is lacking information, which could be obtained from
https://github.com/MTrab/energidataservice

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gskjold** [comment]
You need to provide more information on what you think is lacking

**Comment by ArnieO** [comment]
@Sommerdal-ufm 
Did you recently bought a Pow-K+? (Guessing from your name). 
If prices are missing, it might just be a configuration issue. 
You need to activate "Enable price fetch", and set your Price region, currency and optionally change the multiplier (I use 1.25 to simulate 25% moms:
![image](https://user-images.githubusercontent.com/10295178/235852054-35a1117d-3be9-4609-b3fd-ed58e30d6607.png)

**Comment by Sommerdal-ufm** [comment]
Price fetch is enabled and VAT is calculated (1.25) but I lack transport fees and charges that varies during the day.
![Screenshot_2023-05-03-20-55-18-45_dc006b6a6037a984d6a9a990658f1785](https://user-images.githubusercontent.com/54624988/236016782-3079fd59-1daa-415c-b2c3-a8e7741fb142.jpg)

**Comment by Sommerdal-ufm** [comment]
![Screenshot_2023-05-03-21-01-08-06_dc006b6a6037a984d6a9a990658f1785](https://user-images.githubusercontent.com/54624988/236017311-8cd7595f-b2a3-477c-8eea-4eb0ff581323.jpg)

**Comment by Tbnilen** [comment]
In Denmark, there are different tariffs for the transport of electricity (kWh) during the day:
2400-0600 low load
0600-1700 high load
1700-2400 peak load
The prices change during the summer/winter season (and there is a difference from electricity company to electricity company):

1/4 - 30/9 summer tarif
1/10-31/3 winter half tarif

example Andel Energi:

![image](https://user-images.githubusercontent.com/20386632/236828099-ecb9caaf-8953-4dfe-87dc-148a2ccc0ca0.png)

**Comment by ArnieO** [comment]
The transport tariffs is a highly complex subject that has been discussed in other threads. There are huge differences in tariffication models even within the same country. Our aim is that this firmware should be usable in any country - and that the price estimates should at least be usable in countries covered by Entso-E (for the energy part of the tariffs). 

We have had some fairly good suggestions on how a general setup might be done, but we have not yet gotten to the point where we can prioritize working on it.

**Comment by gskjold** [comment]
As nice as it would be to fetch grid costs from APIs, this will not be implemented in the firmware. Use custom pricing configuration added in v.2.3
