### ISSUE TITLE
Deviation between Entso-E price and hourly price per kWh in NOK

### ISSUE THREAD

**Issue by ArnieO** [UtilitechAS/amsreader-firmware#557]
**Describe the bug**
The price displayed is wrong by close to 3%

Example:
5th May, hour from 11 to 12, Price region NO1:

- [Entso-E price](https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=05.05.2023+00:00|CET|DAY&biddingZone.values=CTY|10YNO-0--------C!BZN|10YNO-1--------2&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)) is 82.06 EUR/MWh.
- Latest [exchange rate from Norges Bank](https://www.norges-bank.no/tema/Statistikk/Valutakurser/) (4tyh May) is 1 EUR = 11,8282 NOK
- Price per kWh should be 82.06 EUR/MWh * 11,8282 NOK/EUR / 1000 kWh/MWh = **0,9706 NOK/kWh**
- Using multiplicator 1,25 (moms) gives 1,21 NOK/KWh
- This user reads 1,18 NOK/kWh:
![image](https://user-images.githubusercontent.com/10295178/236431892-2949d96f-ebcb-4618-9fe6-cbb905b3659a.png)
![image](https://user-images.githubusercontent.com/10295178/236431982-350d5678-5030-47dc-86c0-60323a1a052e.png)

**Comment by gskjold** [comment]
Noted. I need to start logging the exchange rate used. Will keep an eye on this

**Comment by gskjold** [comment]
Just checked Norges Bank API (which we use) and it returns 11.5265 as exchange rate:
https://data.norges-bank.no/api/data/EXR/M.EUR.NOK.SP?lastNObservations=1&format=sdmx-json

I see that the endpoint I use returns exchange rate for the month, so I should switch to businessday which returns 11.6895:
https://data.norges-bank.no/api/data/EXR/B.EUR.NOK.SP?lastNObservations=1&format=sdmx-json

This will put us closer to the "correct" value

**Comment by gskjold** [comment]
Updated amshub for non-apikey clients and updated entso-e code in firmware for next patch for those who use api key

**Comment by ArnieO** [comment]
> I see that the endpoint I use returns exchange rate for the month, so I should switch to businessday which returns 11.6895:
https://data.norges-bank.no/api/data/EXR/B.EUR.NOK.SP?lastNObservations=1&format=sdmx-json

With that exchange rate the above quoted user example would give 1,20 NOK/kWh - which is much closer, but still not identical with Nordpool:
![image](https://user-images.githubusercontent.com/10295178/236533252-ea6e8658-1cd3-438f-898c-cce158d4a1dc.png)

Which gives:  0,97146 * 1,25 = 1,21 

But I think we can live with differences in the order of 1% due to exchange rate issues.

**Comment by nossaile** [comment]
Just for your information: Currently Pow-P1’s hourly prices for SE4 are 0.91% higher than Nordpol’s.
