### ISSUE TITLE
Over 2kA on a max 20A connection

### ISSUE THREAD

**Issue by APayerl** [UtilitechAS/amsreader-firmware#558]
**Describe the bug**
A clear description of what the bug is.
I have upgraded som my previous 2.1.14 to 2.2.17 and now my voltage and amps are not showing correctly (I hope!).
![bild](https://user-images.githubusercontent.com/6882326/236568147-c29e1318-2405-4972-bf08-2da335525580.png)
I have a 20A max and live in sweden (~230V voltage default)

**Hardware information:**
 - Country: Sweden
 - Meter: Kaifa MA304H4
 - Encryption enabled no
 - AMS reader: ESP8266
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.2.17
 - MQTT: yes
 - MQTT payload type: Home Assistant
 - HAN GPIO: GPIO4
 - HAN baud and parity: 2400 8E1
 - ENTSO-E API enabled: no

**Additional context**
I had a very similar problem at the end of this issue: #242 but I do not know what was changed to fix it then.

**Comment by gskjold** [comment]
There have been a change in the code to be more compliant with DLMS spec. Unofrtunately not all meters send well formatted data. Go to config and set multiplier for volt to 0.1 and amp to 0.001.

If you could also run a telnet verbose debug and provide the payload sent by the meter, that would be good

**Comment by gskjold** [comment]
I guess data is the same as in #242 which means there is no scaling provided with the values. There are Kaifa meters in europe that does provide scaling, but there is no good way of detecting the difference. Multiplier config is the best option

**Comment by APayerl** [comment]
Thanks for the quick response!
Unfortunatly my device is now unresponsive...
I think it could have to do with the boot limit for vcc... 
On the old firmware I always had red warning about voltage level. When I upgraded to 2.2.17 that warning went away and became green.
I then set boot limit to 3 since I have a 5V charger connected but upon restart I have lost access to my device :S Stupid mistake to make :(

At least I hope this is the case otherwise I found another bug....

Do you know any way to remove this boot limit setting without having to reflash the whole thing?

**Comment by APayerl** [comment]
I reflashed it with 2.2.17 and set the multipliers so now it works again, thanks!
