### ISSUE TITLE
ESP reports not working 

### ISSUE THREAD

**Issue by Sommerdal-ufm** [UtilitechAS/amsreader-firmware#559]
**Describe your problem**
ESP is red.
Shows no usage but reports to MQTT.
Other indicators are green.
Time shows 1970.
Unable to firmware update.
Can reboot - but ends in same state.
Can activate configuration 

**Hardware information:**
 - Country: Denmark 
 - Meter: Kamstrup 
 - Encryption enabled yes
 - AMS reader: Pow-K+
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version:. 2.2.16
 - MQTT: yes
 - MQTT payload type: home assistent 
![Screenshot_2023-05-06-08-28-07-64_40deb401b9ffe8e1df2f1cc5ba480b12]
 - HAN baud and parity: 2400 8E1
 - ENTSO-E API enabled: yes
![Screenshot_2023-05-06-08-28-07-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/54624988/236607467-db8dc430-5325-42f7-8d0d-33060de493e8.jpg)

**Comment by ArnieO** [comment]
What you report seems inconsistent with your screenclip (reports to MQTT / Other indicators are green)?
As a start, can you share a screenclip of your config page?

**Comment by Sommerdal-ufm** [comment]
![Screenshot_2023-05-06-18-27-53-37~4](https://user-images.githubusercontent.com/54624988/236636223-a4dc46c2-6698-4d5a-a63d-2ad42641f555.jpg)

**Comment by Sommerdal-ufm** [comment]
Problem solved.
Clearing browser cache did the trick.
