### ISSUE TITLE
Negative energy prices break chart layout

### ISSUE THREAD

**Issue by kimsey0** [UtilitechAS/amsreader-firmware#560]
The day-ahead prices in [Nordpool DK2](https://www.nordpoolgroup.com/en/Market-data1/Dayahead/Area-Prices/DK/Hourly/?view=table) are currently negative for some hours, and it breaks the chart layout:
![billede](https://user-images.githubusercontent.com/984760/236629260-ca98495f-7558-4424-9290-7fcba4562dbd.png)

**Comment by ArnieO** [comment]
Nice catch - this is the first time we've seen that situation. I agree; the possibility of negative prices should be taken into account in the firmware - and I guess it impacts more than only the barchart.

**Comment by ArnieO** [comment]
Just adding input on how this could look - and looking forward to seeing this more! 😅 

But PS: 
Is it negative price that somehow has broken the price fetch? Notice that x-axis labels go to 01 (ending at 23 expected), and no prices for tomorrow yet (plot taken at 18h50).
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/14054f3e-ea4d-48fc-aa07-8dd5a961129c)

**Comment by gskjold** [comment]
> Is it negative price that somehow has broken the price fetch?

Fetch isnt broken, but value at 02:00 is -0.0127 which is considered null in the code. After 02:00 prices for tomorrow will come back. I will fix all this ofc :)

**Comment by gskjold** [comment]
Or just reboot now, I have made the server return -0.0126  ;)

**Comment by gskjold** [comment]
Did some adjustments to handle negative prices better:
![Screenshot from 2023-05-16 21-57-29](https://github.com/UtilitechAS/amsreader-firmware/assets/4446828/eef0ff77-18e1-4abe-b218-cbde4c026e5d)

**Comment by ArnieO** [comment]
I happened to be awake around 2 am, and the graph was then fine (sorry, no screen dump). Maybe due to your little fix! 👍
