### ISSUE TITLE
PriceAPI: Unspecified error -1

### ISSUE THREAD

**Issue by wdpk88** [UtilitechAS/amsreader-firmware#563]
Getting this error daily. Goes away when i reboot. But comes back after a few hours. Seams the price graph screws up to. Before and after reboot:

<img width="1264" alt="Screenshot 2023-05-08 at 20 31 20" src="https://user-images.githubusercontent.com/18118381/236903517-a2f66329-d36f-45b7-ae95-52a13653e348.png">
<img width="1264" alt="Screenshot 2023-05-08 at 20 33 03" src="https://user-images.githubusercontent.com/18118381/236903527-75174aad-8744-4532-80f5-558107f16954.png">

**Comment by ArnieO** [comment]
Huh. Do you use Entso-E API key (or do you read prices from our intermediate server)?

**Comment by wdpk88** [comment]
Using a API Key

<img width="316" alt="image" src="https://user-images.githubusercontent.com/18118381/237025573-fc814cec-8667-4a3e-a128-7e5be1e860e7.png">

**Comment by gskjold** [comment]
Are you using DHCP? Could you please check DNS servers on the status page?

**Comment by wdpk88** [comment]
![IMG_0294](https://github.com/UtilitechAS/amsreader-firmware/assets/18118381/b98ab421-0f5e-4d24-9461-06f71724010f)

**Comment by ArnieO** [comment]
I too seem to have issues today:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/4c385c20-cbe8-4583-8897-ad4bcca43dab)

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/e0800c65-2460-4aac-89e5-1eb866327149)

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/5f906a50-d196-4d79-bfbb-1e71cff9e53b)
Rebooting did not help.

**Comment by gskjold** [comment]
@wdpk88 Could you go to the status page and confirm that your static DNS servers are indeed applied?
![Screenshot from 2023-05-08 09-35-25](https://github.com/UtilitechAS/amsreader-firmware/assets/4446828/5773708c-48b8-421f-841c-6ae1eae1e6d2)

**Comment by wdpk88** [comment]
![IMG_0296](https://github.com/UtilitechAS/amsreader-firmware/assets/18118381/6e12a2c0-5210-4bfa-bbe6-4bfbbcf9bf89)

**Comment by gskjold** [comment]
Yes, but also please check the actual configuration state
![Screenshot from 2023-05-10 20-35-55](https://github.com/UtilitechAS/amsreader-firmware/assets/4446828/7cd752ed-5983-4ecb-83e4-368c3ab00617)

**Comment by wdpk88** [comment]
Sorry :)

![IMG_0297](https://github.com/UtilitechAS/amsreader-firmware/assets/18118381/eb5590b7-2ba5-4068-beea-0deb4fe70f09)

**Comment by gskjold** [comment]
This aligns with feedback from a different customer, who is actually running DHCP. His DNS config has also been overwritten, but with 32.1.70.0 . I have not yet been able to identify where this corruption comes from, but I will continue searching

**Comment by ArnieO** [comment]
> This aligns with feedback from a different customer, who is actually running DHCP. His DNS config has also been overwritten, but with 32.1.70.0 . I have not yet been able to identify where this corruption comes from, but I will continue searching

Interesting. So we have reports on similar DNS corruption both with DHCP and static IP?

**Comment by gskjold** [comment]
> Interesting. So we have reports on similar DNS corruption both with DHCP and static IP?

Correct. Most likely caused by a memory corruption from somewhere in the code

**Comment by tha1971** [comment]
Hi
My dns is also getting changed after some hours ( in this case my mqtt crashed after approximately 6:45 hours)
![072EB43A-119E-4BFD-AA80-69BF76D1D571](https://github.com/UtilitechAS/amsreader-firmware/assets/8336607/94d5a536-8a41-444d-80fb-80ea2f9b9857)
![6AEBE76C-647E-489E-8442-5442F5B7DE3D](https://github.com/UtilitechAS/amsreader-firmware/assets/8336607/3b1e8484-3818-424c-b4d8-c938553f2127)

**Comment by ArnieO** [comment]
So DNS was correct but was corrupted during operation?

**Comment by tha1971** [comment]
It seams that the DNS was corrupted during operation and a reboot corrected it again

**Comment by gskjold** [comment]
The reason for this is still a mystery to me... I am wondering if this is related to how the device is configured. For those who have issues, it would be nice if you could share your full configuration with me (but without secrets). You can send it to post@utilitech.no if you prefer not to share it here.

**Comment by tha1971** [comment]
For me it looks to go down around the same time (app 1300) as it is supposed to get the new day ahead prices from entsoe

**Comment by gskjold** [comment]
Thanks, that's good information to have!

**Comment by gskjold** [comment]
Finally able to reproduce this after moving the device to my non-IoT WiFi network. I have been chasing this for hours, and boiled down the problem to a test code here: https://github.com/gskjold/esp32-wifi-problem
No idea how to fix this, so I have opened an issue with espressif: https://github.com/espressif/arduino-esp32/issues/8221

**Comment by gskjold** [comment]
Some new information could indicate that the issue is related to IPv6. Do any of you know if you have IPv6 enabled on your network? If you by any chance have Telenor as your ISP, the answer is yes. Please let me know.

**Comment by tha1971** [comment]
Hi
My isp is Stofa.
But they did some work on the network in my city recently.
I can check the ipv6 to night


tor. 18. maj 2023 08.14 skrev Gunnar Skjold ***@***.***>:

**Comment by wdpk88** [comment]
I have Telenor as ISP

**Comment by gskjold** [comment]
Added workaround, new patch soon

**Comment by oyvindhn** [comment]
Updated to from v2.2.24 to v2.2.28 today and lost all prices.  Errormessage:  PriceAPI: Connection error

A know fault?

**Comment by ArnieO** [comment]
> Updated to from v2.2.24 to v2.2.28 today and lost all prices. Errormessage: PriceAPI: Connection error
> 
> A know fault?

No. 
But due to often seen issues with Entso-E we recommend not using the Entso-E API key. Instead, leave the field open. The device will then fetch prices from our intermediary server. It is a simpler API call, and we attempt alternative price sources if Entso-E is not available/responsive.
