### ISSUE TITLE
No numeric value shown when price = 0

### ISSUE THREAD

**Issue by Nealux** [UtilitechAS/amsreader-firmware#564]
**Describe the bug**
When the energy price is actually zero no numeric value is shown.

**To Reproduce**

**Expected behavior**
A value of 0.0 should be displayed when the price is 0.0

**Screenshots**
![AM0509](https://github.com/UtilitechAS/amsreader-firmware/assets/89211671/f0870b69-b536-4d0c-8a72-6eacf3c2dcbc)
![AM05091](https://github.com/UtilitechAS/amsreader-firmware/assets/89211671/c5a8fa02-d6e2-4621-ba59-5c5e4e257dbf)

**Hardware information:**
 - Country: Sweden
 - Meter: Sagemcom
 - Encryption enabled : no
 - AMS reader: Prototype
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [e.g. 2.2.17]
 - MQTT: no
 - MQTT payload type: [e.g. JSON]
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: 115000 8N1
 - Temperature sensors No
 - ENTSO-E API enabled: yes

**Comment by gskjold** [comment]
Fixed in next patch
