### ISSUE TITLE
FW uppgrade error

### ISSUE THREAD

**Issue by sm4upt** [UtilitechAS/amsreader-firmware#569]
**Describe your problem**
FW uppgrade from v.2.2.15 to v2.2.17 fails with following error message.
Previous upgrade attempt (v2.2.17) does not match current version (v2.2.15) [0/-1]

**Hardware information:**
 - Country: [Sweden]
 - Meter: [Kamstrup 6841131BN245101092]
 - Encryption enabled [no]
 - AMS reader: ( Pow-K+, ESP32s2]
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: [2.2.15]
 - MQTT: [yes]
 - MQTT payload type: [HomeAssistant]
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [2400 8N1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [no]

**Comment by gskjold** [comment]
Please check on status page if your DNS server have been corrupted (See issue #563). If that is the case, could I get a full config file from you? post@utilitech.no
![Screenshot from 2023-05-10 20-35-55](https://github.com/UtilitechAS/amsreader-firmware/assets/4446828/c427834f-6ef3-401c-a6ab-5af42ebe9418)

**Comment by gskjold** [comment]
Excellent, this is the same problem as #563 then. Keep an eye on #563 and upgrade when that is fixed.
