### ISSUE TITLE
Future energy price value

### ISSUE THREAD

**Issue by Nealux** [UtilitechAS/amsreader-firmware#573]
When hoovering with the cursor above the staples representing the hourly prices you see a more exact figure (nice feature).
But when I get to hour 2 and later this does not work. No exact figure is displayed.
This was also a problem with the 2.2.18 release
This morning before the new prices were loaded the exact price was displayed  for all available hours (as I recall)!

1. Go to future energy price 
2. Click on hour 02 or later
**Expected behavior**
Exact price displayed for every hour.

**Hardware information:**
 - Country: [Sweden
 - Meter:Sagemcom
 - Encryption enabled no
 - AMS reader: Prototype
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version:2.2.19]
 - MQTT: no
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity:115000 8n1]yes[yes/no]

**Comment by ArnieO** [comment]
It looks fine here!
Can you provide a screenshot example, please?

**Comment by ArnieO** [comment]
If you use the delay function of Snipping tool you can capture the mouseover.
Here is my mouseover at 23h, showing correct value:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/10db459b-fa22-4132-9244-21381ad11671)

**Comment by Nealux** [comment]
Ia have screen shoots now from 01 and 02 that they dosen't really say much as the curzor is not captured..
But the problem shows up after the price has been updated for today and I hoover over hour 02:00 and all hours  that follows.
This is true today.
But tomorrow it will show the exact price until the price is updated tomorrow.
Yes strange but that is the way it is...
Screen shot with corzor hoovering over 01:00
![AMS05241](https://github.com/UtilitechAS/amsreader-firmware/assets/89211671/fcd8359b-c828-4cef-9ece-89c2afa15174)
This screen shoot with the curzor above 02:00
![AMS05242](https://github.com/UtilitechAS/amsreader-firmware/assets/89211671/45c8017a-211c-452d-bfe8-98523a00a1bf)

**Comment by ArnieO** [comment]
There might be a (strange; as you point out) problem here - but sorry: I fail to understand what you're seeing when you hover over 02. Maybe easier to make a photo with your phone?

**Comment by Nealux** [comment]
I do not see the information as shown in the first example. (-0.04 SEK). This is the information displayed when the cursor is place above the 01.00 o'clock staple.
When the cursor is is moved to the 02:00 staple no information is displayed.
This goes for all staples following the 02:00 staple.
But if I do the same thing in the morning all information is displayed.
It will work ok until the figures are updated  tomorrow.
I'm sorry that  I'm not able to explain what I see as a problem in a better. way.
![AMS05244](https://github.com/UtilitechAS/amsreader-firmware/assets/89211671/3d26cccc-8d3e-4d00-bb42-91ee02012d1d)
![AMS05245](https://github.com/UtilitechAS/amsreader-firmware/assets/89211671/e8a332b2-e559-4932-8efc-ac6a47f45cc2)

**Comment by ArnieO** [comment]
OK, I finally understood; sorry that I was a bit slow! I was confused by your first message saying " No exact figure is displayed." 
I thought the problem was precision on the figure, and didn't understand that it was missing totally. 

Thank you for reporting - we'll see if we can find the issue.

**Comment by cmock** [comment]
FWIW, I'm having the same issue, and when I inspect the HTML in the browser I see for each bar:

```
<g>
 <rect ...></rect>
 <text ...></text>
 <title>0.10 EUR</title>
</g>
```

But for the bars after 01 hrs, the whole `<title>` tag is missing.
