### ISSUE TITLE
Store `Price current hour` in Home Assistant's Long Term Statistics

### ISSUE THREAD

**Issue by kandsten** [UtilitechAS/amsreader-firmware#574]
Home Assistant has a facility for storing [Long Term Statistics](https://data.home-assistant.io/docs/statistics/); these live on indefinitely, as opposed to the recorder data that is kept for a finite number of days.

It'd be nice it the energy price that AMS reader publishes would be stored in this database as it enables other interesting uses of the data. One concrete such example: I'm the author of [a heatmap card](https://github.com/kandsten/ha-heatmap-card), looking to expand it to incorporate energy usage and price in the same heat map. The more that works out the box, the better for the user. 
 
One way to achieve it would be to modify the `Price current hour` topic data slightly:

**Current:**
```
unit_of_measurement: NNN/kWh
device_class: monetary
friendly_name: Price current hour
```

**Proposed:**
```
unit_of_measurement: NNN/kWh
device_class: monetary
state_class: total
friendly_name: Price current hour
```

Setting the `state_class` would make it fit [the requirements](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics) for getting stored into Home Assistant's LTS.

(Edit: bit tired last night, edited to proper ask)

**Comment by MrDemocracy** [comment]
I think this could be why I'm receiving this warning and why not all the statistics entities get listed on the energy dashboard:
<img width="475" src="https://github.com/UtilitechAS/amsreader-firmware/assets/23060864/4e4e413d-1850-42f9-ba36-38c2f170e8e9">
<img width="379" src="https://github.com/UtilitechAS/amsreader-firmware/assets/23060864/36341866-6433-41e0-9543-96cc6a3abe50">

**Comment by gskjold** [comment]
I see I have not commented on this before, sorry about that. I will have a closer look at a few HA related issues in the near future and have this sorted out.

**Comment by gskjold** [comment]
Apparently I did this for 2.2.22 :)
