### ISSUE TITLE
Price info

### ISSUE THREAD

**Issue by PerBuch54** [UtilitechAS/amsreader-firmware#575]
After the latest update i dont get the Future energy price Future energy price updates.

**Comment by gskjold** [comment]
If you get a price not found right now, its just entsoe missing price for tomorrow

**Comment by PerBuch54** [comment]
You are right prici info ok now

**Comment by PerBuch54** [comment]
Again! Are ENTSO-E a little unstable ?

**Comment by gskjold** [comment]
Sadly they have had several cases of missing data lately, including today...

**Comment by nossaile** [comment]
...and today too. It looks like ENTSO-E is more and more unreliably. Isn’t there any alternative supplier of spot prices?

**Comment by tha1971** [comment]
Are #580 the same problem as this, i am also missing prices with wrong date and correct time

**Comment by nossaile** [comment]
No, tha1971, this is about missing spot prices and #580 is about wrong date shown.

**Comment by gskjold** [comment]
Fallback implemented
