### ISSUE TITLE
Numbers overlap after the last update 2.2.19

### ISSUE THREAD

**Issue by evhetlan** [UtilitechAS/amsreader-firmware#577]
Numbers overlap after the last update, see picture

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/110242351/296bd6d7-74a8-41ff-a399-c68924c0b91d)

**Comment by gskjold** [comment]
Interesting, what browser is this?

**Comment by evhetlan** [comment]
Crome

**Comment by gskjold** [comment]
Ok got it, I see that this boils down to how I have tested this feature. Will fix :)

**Comment by Tbnilen** [comment]
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/20386632/5edf872b-9bf1-429e-b3c6-752f38f716ed)

safari
