### ISSUE TITLE
Better display of prices when close to zero NOK?

### ISSUE THREAD

**Issue by ThorAlex87** [UtilitechAS/amsreader-firmware#583]
**Is your feature request related to a problem? Please describe.**
Not really a big problem, but I feel like it could be improved. Prices in NOK are rounded to a single number after the decimal point,  which makes for a not so great graph when many of the future hours are close to zero. The tooltip displays the exact price, but does not help to give a great overview.

**Describe the solution you'd like**
Not sure.

**Describe alternatives you've considered**
Maybe display two digits after the decimal point? could maybe be conditional for prices under 0.1? 

**Additional context**
Screenshot
![Rare priser](https://github.com/UtilitechAS/amsreader-firmware/assets/111507745/cee35d5a-dc1e-43a6-a0da-2a0ac678cf1c)

Edit:
This morning there are two digits after the decimal point, so maybe an adjustment of when it changes is all that's needed?
![Litt mindre rare priser](https://github.com/UtilitechAS/amsreader-firmware/assets/111507745/f85126d5-0b9a-4eea-814c-1d416288f9d3)

**Comment by ThorAlex87** [comment]
I'm back to one digit too. I suspect the threshold is when there is a price above 0.05 it goes single digit, so maybe raising it up to 0.2 would avoid these situations where most prices are displayed as 0.0.

**Comment by ArnieO** [comment]
My highest now is less than 0.14 - so I think it is something else. Something for @gskjold to look into for next revision I guess.

**Comment by gskjold** [comment]
Two digits area used when there are less than 20 bars in the plot

**Comment by ThorAlex87** [comment]
Is that really necessary? On smaller screens the numbers flip vertically, so there should not be any space issues when there are many bars?
