### ISSUE TITLE
Problems with Accumulated cost calculation

### ISSUE THREAD

**Issue by ArnieO** [UtilitechAS/amsreader-firmware#587]
In case anyone else sees the same; this is now a known issue:

A customer has reported an issue with the accumulated cost estimate:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/d815e273-6f2f-481b-93a1-0f2e96b69109)

In this case it is easy to spot. 
The estimate on my own device looks reasonable for the same period, but that calculation cannot be trusted.

**Comment by rogerthn2019** [comment]
Not a major issue but checking this it looks like my fixed price is used for both Import and Export. I do have a fixed price on import and spot + 10 öre on export. Monthly average spot makes it hard for AMS reader to calculate ;-)

**Comment by gskjold** [comment]
Fixed in next patch. As for fixed price on export, created issue #590
