### ISSUE TITLE
"Future energy price" scaling wrong after network drops out and comes back

### ISSUE THREAD

**Issue by cmock** [UtilitechAS/amsreader-firmware#592]
**Describe the bug**

The new scaling for future prices introduced in 2.2.20 is wrong after a network outage. Reloading the page restores the correct behaviour.

**To Reproduce**

- Open AMS in browser
- Wait for a network dropout to occur and the connection to be restored, keep the browser window open
- See wrong scaling
- Press F5
- Scaling is correct again (until next network problem)

**Screenshots**
***Bug:***
![Screenshot_20230611_140833](https://github.com/UtilitechAS/amsreader-firmware/assets/2141141/54223d97-6667-4816-a51e-efac11465686)
***Correct:***
![Screenshot_20230611_141850](https://github.com/UtilitechAS/amsreader-firmware/assets/2141141/089d3c3d-54c2-44f6-b2ee-7da0b923b5fe)

**Hardware information:**
 - Country: Austria
 - Meter: Sagemcom
 - Encryption enabled: yes
 - AMS reader: ESP32 dev board
 - M-bus adapter (if applicable): resistive divider

**Relevant firmware information:**
 - Version: 2.2.20
 - MQTT: yes
 - MQTT payload type: Raw (full)
 - HAN GPIO: UART2
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: -
 - ENTSO-E API enabled: yes

**Additional context**

My meter is far away from my accesspoint, so the connection can be flaky at times, goes away and comes back in intervals of tens of seconds.

**Comment by ArnieO** [comment]
You're right, I see the same thing.
