### ISSUE TITLE
Loosing stored data

### ISSUE THREAD

**Issue by leakim1957** [UtilitechAS/amsreader-firmware#596]
I have v2.2.20 and last night at 01.00 all stored data both "Energy use last 24 hours" as well as "Energy use last 31 days" was lost, see picture. This is not the first time this happends. I remember at least two other occations after the HW was replaced in january.
![Skärmbild 2023-06-16 090411](https://github.com/UtilitechAS/amsreader-firmware/assets/136789493/3ff2da4a-f513-42c5-861b-f776aff6fc3c)

**Comment by gskjold** [comment]
Sounds like there could be some sort of edge case where this happens. Would have to look into that. Does your device have access to internet?

**Comment by leakim1957** [comment]
Hi Gunnar
Yes, internet access 24/7.
If there should be an internet drop out at some time, why would that erase the memory stored?

///Mikael

Från: Gunnar Skjold ***@***.***>
Skickat: den 16 juni 2023 09:08
Till: UtilitechAS/amsreader-firmware ***@***.***>
Kopia: leakim1957 ***@***.***>; Author ***@***.***>
Ämne: Re: [UtilitechAS/amsreader-firmware] Loosing stored data (Issue #596)


Sounds like there could be some sort of edge case where this happens. Would have to look into that. Does your device have access to internet?

-

**Comment by gskjold** [comment]
It shouldn't, but if it does not have internet access, it gets time from the meter which in some cases are not completely reliable, and if the time drift is too high, the data is cleared

**Comment by leakim1957** [comment]
Ok, I will check the connection.
Can you specify the time drift,  Is it seconds, minutes or hours?

**Comment by gskjold** [comment]
I've tried to find some way to reproduce this, but I have yet to succeed. Could you give me some more information:

Country:
Manufacturer and model of meter:
AMS reader hardware:

**Comment by leakim1957** [comment]
Hi Gunnar
See my answers below in red.
I would like to add that I have only had data saved for a maximum of 5 days in a row for the past few months.
Sometimes only 1 day, sometimes 2-3 days.
///Mikael BW

Från: Gunnar Skjold ***@***.***>
Skickat: den 18 augusti 2023 09:57
Till: UtilitechAS/amsreader-firmware ***@***.***>
Kopia: leakim1957 ***@***.***>; Author ***@***.***>
Ämne: Re: [UtilitechAS/amsreader-firmware] Loosing stored data (Issue #596)


I've tried to find some way to reproduce this, but I have yet to succeed. Could you give me some more information:

Country: Sweden


Manufacturer and model of meter: Sagemcom T211

***@***.***




AMS reader hardware:

***@***.***

-

**Comment by ArnieO** [comment]
@leakim1957 That did not work. You need to log into Github and write your message there.

**Comment by leakim1957** [comment]
Hope this will be better:-)

Country: Sweden

Manufacturer and model of meter: Sagemcom T211, see picture
![Skärmbild 2023-08-18 124910](https://github.com/UtilitechAS/amsreader-firmware/assets/136789493/35d5082d-c621-46c3-a6db-617d1fa6ddcc)


AMS reader hardware: See picture
![Skärmbild 2023-08-18 124718](https://github.com/UtilitechAS/amsreader-firmware/assets/136789493/97af2efb-0241-4228-a420-5e7f0cfb957b)

**Comment by ArnieO** [comment]
@leakim1957 You closed the issue - was that on purpose, or was it a mistake?

OK - you are running a Pow-P1 on a Sagemcom in Sweden. 
We have several such installations running, I don't think the hardware is an issue. 

Sounds more like some strange edge issue, probably related to other reports lately of missing/lost data. 
@gskjold is working on it, trying to recreate the issue.

**Comment by gskjold** [comment]
Got two issues regarding loosing data, both Sagemcom, do you know of any more cases @ArnieO  ?

**Comment by ArnieO** [comment]
> Got two issues regarding loosing data, both Sagemcom, do you know of any more cases @ArnieO ?

None other than those reported in issues here on Github.

**Comment by leakim1957** [comment]
It was a mistake, I am not used to work in github

**Comment by stigvi** [comment]
Some kind of issues with mine too. Uptime is 34 days, but only the last 19 have any data.

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/25978315/8d89371d-63e7-487c-bec4-106b752ba5dc)

**Comment by gskjold** [comment]
Interesting indeed, something definitely happened here

**Comment by stigvi** [comment]
> Interesting indeed, something definitely happened here

Hi. I see from my Tibber App that 8th of August was rather special because my energy cost that day was NOK -1.90. I don't have any entsoe prices downloaded to my unit, so I am not able to see any connection to the missing data. But maybe there is?

**Comment by gskjold** [comment]
Good to think outside the box here, thanks for that. I am not able to see a connection there either, but will keep it in mind

**Comment by gskjold** [comment]
I finally understand what is going on here now, will fix this for next patch

**Comment by leakim1957** [comment]
Can´t wait to test it :-)

**Comment by senspix** [comment]
Possibly the same issue but with month plot. Also Sagemcom T211 device in Sweden.
![Screenshot 2023-09-18 at 15 45 26](https://github.com/UtilitechAS/amsreader-firmware/assets/2562698/b8a0d935-0f90-4929-8d53-2cf699d46763)

**Comment by leakim1957** [comment]
Hi. Loading screen shot of system after installing latest version. Let´s see what happends with stored data as time goes by.
///Mikael

![Skärmbild 2023-09-29 142358](https://github.com/UtilitechAS/amsreader-firmware/assets/136789493/afed4297-bfeb-4a3b-aaa8-0fb2f9159cb6)

**Comment by leakim1957** [comment]
Hi, just when I hoped the problem was solved, it has appeared again. 
No problems since last update but tonight at 0200 it went blank and no update of prices either.
///Mikael
![Skärmbild 2023-10-12 093917](https://github.com/UtilitechAS/amsreader-firmware/assets/136789493/ada4c1b2-ecf9-4802-a2a3-83e5be070bd7)

**Comment by leakim1957** [comment]
![AMS reader 31 day ok](https://github.com/UtilitechAS/amsreader-firmware/assets/136789493/3abdf9d9-78eb-4d5e-bada-35ae728314a5)

31 days in a row without loosing data. Well done!!!
///Mikael

**Comment by ArnieO** [comment]
So - let us hope this bug is dead and gone for ever now!
