### ISSUE TITLE
sceurity problem? - "Swap to AP mode if WiFi psk is wrong"

### ISSUE THREAD

**Issue by bmork** [UtilitechAS/amsreader-firmware#600]
**Describe the bug**
Possible unauthenticated remote access

**To Reproduce**
- Configure a rogue AP with the SSID used by amsreader, 
- wait for the amsreader to attempt a connection and fail, 
- connect to the amsreader AP and reconfigure it

**Expected behavior**
physical access or authentication required for any amsreader management

**Note**
I've not actually tried this.  It's only based on assumed behaviour from the feature description and code.  But I'd really prefer not to have this feature. At least not by default. Pushing a button for AP mode is not a problem for the rare occasion where the password changed in the wrong order (AP before client).

**Comment by ArnieO** [comment]
You're making an interesting point! 
@gskjold : What do you think?

**Comment by gskjold** [comment]
Technically possible, good point. Will only default this feature for initial setup
