### ISSUE TITLE
Reboot several times a day

### ISSUE THREAD

**Issue by ma10as123** [UtilitechAS/amsreader-firmware#608]
**Describe the bug**
restarts anywhere from 2 to 10 times a day. Resets power used this hour.

**Relevant firmware information:**
 - Version: 2.2.21
 - MQTT: yes
 - MQTT payload type: homeassistan
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: yes
![
![Screenshot_20230711_114519_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/adb2f18e-934e-4a80-819a-1031bef96545)
![Screenshot_20230711_114456_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/e4f77efc-4f49-44fc-995f-5d83337e41b5)
![Screenshot_20230711_113427_Home Assistant](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/8eac2bf2-9ac6-4ade-85c5-f694bbcc6888)
![Screenshot_20230711_103039_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/0b13a0aa-3b68-46f8-b436-57e8f6092228)

**Additional context**

**Comment by ma10as123** [comment]
![Screenshot_20230711_120203_Home Assistant](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/bd86c565-b6ec-4a13-8e98-70fd30b3e180)
![Screenshot_20230711_120146_Home Assistant](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/ca28ae16-c535-4c93-94ad-e39aa78fc818)

**Comment by ma10as123** [comment]
![Screenshot_20230711_120457_Home Assistant](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/13318983-050d-4bb9-984e-7af2005a7c0e)

**Comment by ma10as123** [comment]
yes, always Vbat power on reset (1/0)

**Comment by ArnieO** [comment]
We are seeing this problem on (very) few boards, and have concluded there is a problem with the ESP32 microcontroller module on some boards that makes it reboot from time to time. 

@ma10as123 : You did not state which hardware you use, but I am guessing (from your SSID and your nickname) that this is a Pow-K board that you bought from us in June - is that right? In that case we would like to send you a replacement board. Please contact me on post@amsleser.no to arrange.

**Comment by ma10as123** [comment]
Yes. It is the pow-k i bought in june that have the problem. I also bought one in november 2022. And it is working ok, it reboots periodically (ca once per day) but i can live with that

**Comment by ma10as123** [comment]
New pow-k fixed the problem

**Comment by ArnieO** [comment]
> New pow-k fixed the problem

Good to hear - thank you for your feedback!
