### ISSUE TITLE
Smart config

### ISSUE THREAD

**Issue by gskjold** [UtilitechAS/amsreader-firmware#609]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_smartconfig.html

**Comment by henriklund** [comment]
Looks promising. It would appear that this then requires an app for [iPhone](https://apps.apple.com/us/app/espressif-esptouch/id1071176700) or [Android](https://play.google.com/store/apps/details?id=com.khoazero123.iot_esptouch_demo&hl=en_IN&gl=US)

**Comment by ArnieO** [comment]
> Looks promising. It would appear that this then requires an app for [iPhone](https://apps.apple.com/us/app/espressif-esptouch/id1071176700) or [Android](https://play.google.com/store/apps/details?id=com.khoazero123.iot_esptouch_demo&hl=en_IN&gl=US)

Yes, using Smart config will require using the Espressif app.

However, using the app will be optional. 
The current Wifi onboarding method (start Access point, connect to it, open web browser on http://192.168.4.1) will still be available. Those who are used to this method will in fact not notice any change.

**Comment by bardahlm** [comment]
Sounds a bit unsecure. The app broadcasts the wifi credentials so it should not be used where those credentials could be misused by rouge users.

**Comment by gskjold** [comment]
V2 uses encryption for this process

**Comment by gskjold** [comment]
Looking deeper into this, v2 only supports symetric encryptions, meaning it would need a pre-shared key. Any thoughts on this?
