### ISSUE TITLE
Correct configuration for wemos D1 mini & DLSM meter

### ISSUE THREAD

**Issue by TRIROG** [UtilitechAS/amsreader-firmware#614]
Read the entire readme but cant seem to find how to configure the Wemos D1 mini for reading of  AM550 meter that uses DLMS.

I see HAN sttus in web interface but i have DLSM meter with P1 port. Does that matter?

I know i need to invert the receive pin which i did using bc546 and some resistors. I confirmed the connection to be working by using raspberry pi and gurux dlsm python script to listen to output.

now what?

**Comment by TRIROG** [comment]
OK, so i got to the correct settings  by trial and error and using telnet debug (very nice!).

For hardware serial on wemos d1 mini clone port should be UART0 and not UART2 as indicated in wiki.
Furthermore the function of pullup on UART is not really clear, but i had to leave it on to work.

So for anyone reading this, definitely use telnet debug to find the correct settings.

**Comment by ArnieO** [comment]
We have not taken the time to write documentation for various DIY HW; it would be a large and "never ending" job.
Thank you for your (and other DIY'ers') understanding!
