### ISSUE TITLE
Improve scaling of graphs with very unequal import/export numbers?

### ISSUE THREAD

**Issue by ThorAlex87** [UtilitechAS/amsreader-firmware#628]
**Is your feature request related to a problem? Please describe.**
When graphs have both import and export they scale with zero in the middle and an equal scale over and under zero. With my new solar setup and home assistant moving loads to when there is high solar production I get a very large difference in the bars over and under zero, causing a lot of wasted space in the import graph in my case.

**Describe the solution you'd like**
Maybe allowing the zero line to move up and down would be better? Might have to make the zero line a little thicker too.

**Describe alternatives you've considered**
Dunno, that's my best idea. I can see the advantage of leaving it as is too, in that it shows off the difference in import/export more obviously. (Leaving zero in the middle and scaling differently for import and export is another option, but a bad one IMO.)

**Additional context**
Screenshot this morning, highest hourly import last 24 hours is 0,5kWh but graph scales to 6,2kWh due to the export numbers. In my case the export could potentially get close to 15kWh on a good day with import peaking as low as 0,2kWh in the same graph, resulting in the space above zero being almost completely empty.
![Untitled](https://github.com/UtilitechAS/amsreader-firmware/assets/111507745/7602113b-0148-4370-861f-abf9b25642af)

**Comment by ArnieO** [comment]
Thank you for your comment and proposed solution!
I think your idea of de-centering the zero line would be an improvement. 
Now let us hear what @gskjold thinks, and whether it is implementable in the graphics tool we're using.

**Comment by gskjold** [comment]
For next patch:
![Screenshot from 2023-09-05 11-38-02](https://github.com/UtilitechAS/amsreader-firmware/assets/4446828/095889f4-3a72-4703-8d26-d5ec8b6379b0)

**Comment by ThorAlex87** [comment]
That looks great, thanks! Is there an estimated ETA on the next patch?

**Comment by gskjold** [comment]
I would guess within a couple of weeks, as there are enough changes ready to go.

**Comment by spacecosmos** [comment]
Maybe an additional possible solution could be to have different colours on the graph for import and export? Green on import perhaps? Just my two cents.

**Comment by ArnieO** [comment]
> Maybe an additional possible solution could be to have different colours on the graph for import and export? Green on import perhaps? Just my two cents.

I definitively think that is an idea worth pursuing! 👍

**Comment by gskjold** [comment]
Final testing of this feature in issue #641 

Also see #544 regarding colors on graphs
