### ISSUE TITLE
Wrong current month peaks indexing

### ISSUE THREAD

**Issue by longer83** [UtilitechAS/amsreader-firmware#632]
**Describe the bug:**

Wrong current month peaks indexing. Current month peaks show incorrect values, peak 3 always "unknown".

**Screenshots:**

![Screenshot_2023-08-13-14-13-08-07_c3a231c25ed346e59462e84656a70e50](https://github.com/toreamun/amshan-homeassistant/assets/15156852/e9e3f53e-2621-4239-99dc-c35a112071f6)

![Screenshot_2023-08-13-14-13-29-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/toreamun/amshan-homeassistant/assets/15156852/cc5da33a-5b03-437f-bb8a-cb3fe5eab46b)

**Hardware information:**

 - Country: Norway
 - Meter: Kamstrup Omnipower (DK-8660)
 - Encryption enabled: no
 - AMS reader: Pow-K+

**Relevant firmware information:**

 - Version: 2.2.21
 - MQTT: yes
 - MQTT payload type: HomeAssistant
 - HAN baud and parity: 2400 8N1
 - ENTSO-E API enabled: yes

**Additional context:**

Debug log:
```text
name: Current month peak 3
state_topic: amsleser/realtime
unique_id: ams-xxxx_peaks3
object_id: ams-xxxx_peaks3
unit_of_measurement: kWh
value_template: '{{ value_json.peaks[3] | is_defined }}'
device:
  identifiers:
    - ams-xxxx
  name: AMS reader
  model: Pow-K+
  sw_version: v2.2.21
  manufacturer: amsleser.no
  configuration_url: http://ams-xxxx.local/
device_class: energy
platform: mqtt
```
```text
Received 15:43:32
QoS: 0
Payload: max: 3
peaks:
  - 3.57
  - 2.45
  - 3.06
threshold: 5
hour:
  use: 1.38
  cost: 0
  produced: 0
  income: 0
day:
  use: 21.9
  cost: 0
  produced: 0
  income: 0
month:
  use: 63.5
  cost: 0
  produced: 0
  income: 
```

Looks like the indexing is incorrect and peaks should have following indexes:

```text
value_json.peaks[0]
value_json.peaks[1]
value_json.peaks[2]
```
not
```text
value_json.peaks[1]
value_json.peaks[2]
value_json.peaks[3]
```

Issue has been also raised up on amshan-homeassistant GitHub: [#65](https://github.com/toreamun/amshan-homeassistant/issues/65).

**Comment by gskjold** [comment]
Nice catch, thanks!

**Comment by gskjold** [comment]
Final testing of this feature in issue #641
