### ISSUE TITLE
Tariff peaks missing a peak

### ISSUE THREAD

**Issue by wknutsen** [UtilitechAS/amsreader-firmware#640]
**Describe the bug**
Tariff peaks is missing a peak
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/47573481/d89dfaf2-992f-4ca3-8935-c31bfcf3c5c1)

I found the value in my timeseries from realtime accumulated hourly
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/47573481/4c0d9403-a667-4732-86e7-5031dc945b16)

This is the peaks from my grid company
Dato og tid | Døgnmaks
16.09.2023, kl 00:00 | 4,55 kW
15.09.2023, kl 23:00 | 4,49 kW
03.09.2023, kl 20:00 | 3,40 kW

Could it be that this peak was used on 16th instead of 15th ?

Update:
I did some more investigation and found another peak from 15th that should have been picked up
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/47573481/a97bb349-2114-4393-9acd-f4b64c609d65)

**Hardware information:**
 - Country: Norway
 - Meter: Aidon
 - Encryption enabled: No
 - AMS reader: 
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.2.21 (Test firmware)
 - MQTT: Yes
 - MQTT payload type: JSON
 - HAN GPIO: Unknown
 - HAN baud and parity: Unknown
 - Temperature sensors: No
 - ENTSO-E API enabled: Yes

**Comment by ArnieO** [comment]
Interesting. 
Which hardware are you running?

**Comment by wknutsen** [comment]
> Interesting. Which hardware are you running?

I forgot to mention :) ESP32S2 Pow-U+

**Comment by ArnieO** [comment]
OK, so I downloaded my own data from  https://elhub.no/elhub-for-sluttbruker/minside/ to check. 
And I confirm there seems to be an issue here:

My 3 highest-consumption hour-intervals according to Elhub are:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/a8965372-ca94-40d7-8f77-49f3a5850e6f)
(The CSV file from Elhub needs some "tinkering" in Excel to show it in this format.)

While my GUI shows:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/ee5f5a53-644b-46c8-b88c-421a8b04a8bc)

In my case, I use my meter for testing from time to time - so is a possibility that my amsreader may have not been plugged in or working on 12th sep (which is missing on the graph). 

Therefore:

**CALL FOR HELP**
Has anyone else have seen such discrepancy when comparing with "official data"? 
Norwegian users can log in to "Min side" on Elhub to find the registered data: https://elhub.no/elhub-for-sluttbruker/minside/
Then: 

- Select "Måleverdier" in the top menu
- Click "Last ned måleverdier"
- Select current month (CSV file)
- Import to e.g. Excel, and do whatever is needed to display the data in a sensible way (my Windows installation is in English, and the timestamp date from Elhub is formatted dd/mm/yyyy - which my Excel did not understand correctly)
- Compare with amsleser GUI peak hours

**Comment by gskjold** [comment]
This is interesting, I actually noticed on my setup that a peak was missing. Normally I don't see this, because I have a 4.95kwh peak many days in a month, but on this particular setup I knew there should have been two 10ish kwh peaks, but only one is recorded! Wasn't sure if it was a bug or me messing up the data from restore, but now I know

**Comment by gskjold** [comment]
Final testing of this feature in issue #641
