### ISSUE TITLE
PriceAPI: blank error

### ISSUE THREAD

**Issue by joachimtingvold** [UtilitechAS/amsreader-firmware#643]
**Describe the bug**

The PriceAPI shows up in the header as if it has some error, but it's blank (i.e. contains no error message/code).

<img width="1479" alt="image" src="https://github.com/UtilitechAS/amsreader-firmware/assets/359918/3a0884ff-da3b-43f1-b723-ead9528785e0">

**To Reproduce**
1. Boot it with ENTSO API enabled
2. Immediately see the PriceAPI error in the header, where it will stay indefinitely

**Expected behavior**
No error, or at least show what the problem is.

**Screenshots**
<img width="539" alt="image" src="https://github.com/UtilitechAS/amsreader-firmware/assets/359918/8129645d-2721-4094-be8b-de7b625b373f">

**Hardware information:**
 - Country: Norway
 - Meter: Kaifa
 - Encryption enabled: no
 - AMS reader: Pow-U+
 - M-bus adapter (if applicable): N/A

**Relevant firmware information:**
 - Version: 2.2.21
 - MQTT: yes
 - MQTT payload type: HomeAssistant
 - HAN GPIO: N/A
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: N/A
 - ENTSO-E API enabled: yes

**Additional context**
N/A

**Comment by joachimtingvold** [comment]
I also see the IPv6-DNS-interpreted-as-IPv4 issue (mentioned in #563), seeing as it reports "DNS: <ipv4> / <decimal IPv6>". It is not replaced, though (compared to what was seen in #563), but that might be due to the workaround mentioned in the same issue?

Both my readers are on IPv6-enabled networks, and the decimal-encoded IPv6-address it finds as DNS is probably related to RDNSS (which I also have enabled on both these networks).

I have no idea if these two are related (the decimal-encoded IPv6 DNS and ENTSO API).

**Comment by Jellybeanz1980** [comment]
I've been investigating this for some time now. I've got 2 custom-made boards running the same firmware. I've observed the issue on one of them, not on the other one. Resetting the board, even powering it down doesn't solve the issue. EntsoeAPI returns following during initiating the communication:

"(E) (EntsoeApi) Communication error, returned status: -1
(E) connection refused"

I'm not sure when the error began. Now the second board also fails. I've implemented a "ping" function in the firmware in order to check if it is a DNS issue, or a connection issue. No problem with the ping to google.com. When I copy the exact link that the board uses to connect to Entsoe, and try it in a browser of PC, it works as expected, thus no error on the API key.

**Comment by gskjold** [comment]
Are you using ENTSO-E API key? Also, is this a self compiled code or official binaries?

**Comment by joachimtingvold** [comment]
Not sure if you're asking me or @Jellybeanz1980, but I'll answer for my setup. Yes, using ENTSO-E API key. Using official firmware.

**Comment by gskjold** [comment]
Asking all involved :) Thanks. I will try to reproduce having dns1 as ipv4 and ipv6 as dns2, maybe there is something there although I would think it should work as long as dns1 is a valid dns server

**Comment by joachimtingvold** [comment]
PriceAPI used to work on both my amsreader devices. I've had DHCPv4 provided IPv4 DNS alongside RDNSS provided IPv6 DNS on my IoT VLAN since long before getting the amsreader. Not sure if it stopped working after a specific amsreader version, or if it's a combination of amsreader changes and ENTSO API changes... The ENTSO website required me to change my password when I started troubleshooting it, so I initially thought it was related to that. But even after changing the password and regenerating the API key, the result is the same.

**Comment by gskjold** [comment]
Could you please try this test firmware to check if it works for you?

[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12730899/esp32s2.zip)

**Comment by longer83** [comment]
Can you change primary and secondary DNS for AMS reader to 8.8.8.8 and 8.8.4.4 and check if it helped?

**Comment by joachimtingvold** [comment]
I have not touched my amsreader since creating this post, and still running 2.2.21. This is the dashboard right now;

<img width="1278" alt="image" src="https://github.com/UtilitechAS/amsreader-firmware/assets/359918/392cf322-8972-49be-ba5f-362e89f1f728">
<img width="787" alt="image" src="https://github.com/UtilitechAS/amsreader-firmware/assets/359918/166fc761-d0f1-4c94-ba75-e308d541f8a8">

Not sure why it "suddenly" works, and why it "suddenly" stopped working... maybe it was indeed intermittent problems in the ENTSO API?

**Comment by Jellybeanz1980** [comment]
In my case I use a custom ESP32 board and compile the binary file with small adjustment for my board. I've got the API key. It worked some time, and suddenly after a restart I got the error message, no matter what I do. I've tried with google DNS server IPs. I didn't change any network settings on my router, nor on the ESP32 board. Once it started failing, I can't get it work.

**Comment by ArnieO** [comment]
> Not sure why it "suddenly" works, and why it "suddenly" stopped working... maybe it was indeed intermittent problems in the ENTSO API?

We have at several occasions seen issues with shorter or longer duration with the ENTSO-E API. 
That was part of the reason why we set up an intermediary server: If you activate "Enable price fetch from remote server" and leave the API key field empty, data is read from our intermediary server.

**Comment by spacecosmos** [comment]
For some reason, I'm getting this today:

![SmartSelect_20230927_172749_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/93f21e05-a3d2-4750-b5e7-d682e905158a)

**Comment by spacecosmos** [comment]
For some reason, I'm getting this today:

![SmartSelect_20230927_172749_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/615929ad-d130-4199-a3bb-e435b7767913)

Here's the config:

![SmartSelect_20230927_173002_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/ade18373-2afb-4c8a-ad7b-a3d600df9ed1)

Any clues to what could be the problem?

**Comment by ArnieO** [comment]
> Any clues to what could be the problem?

I confirm; there is an issue. 
[Entso-E has not published data for tomorrow, 28th sep.](
https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=28.09.2023+00:00|CET|DAY&biddingZone.values=CTY|10YNO-0--------C!BZN|10YNO-2--------T&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))

**Comment by rogerthn2019** [comment]
> ... If you activate "Enable price fetch from remote server" and leave the API key field empty, data is read from our intermediary server.
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/57598997/1b6710b1-2a78-4c8e-837e-4fee6cf2f48d)
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/57598997/b030ec51-12be-43d8-9efd-1c021eebabda)

**Comment by OleG-DK3460** [comment]
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/146317274/711c4832-09dd-4184-83df-841fdb7c2574)
I have the same problem, last pricedata was sep 27th. Leaving the ENTSO-E key empty only gives "PriceAPI: Unspecified error 1". Both on PC and phone.

**Comment by ArnieO** [comment]
The link in my previous post takes you to the Entso-E website, which shows that they have still not published price data for 28th September (today).
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/2ceddf36-746a-4bee-8b2c-de9afec2bf6a)

**Comment by Jellybeanz1980** [comment]
Now the Entso-E website is up and running, but I'm still getting the same error message. How about you guys? Is it working for you now?

At Entsoe webpage they say "If the root CAs are different, ECP EP can reject the connection". Could it be something to do with the secure connection?

**Comment by spacecosmos** [comment]
Seems to be working now. 

I had to disable the "**Enable price fetch from remote server**" setting (untick the checkbox), save settings, then enable it and save settings again. Then the correct values appeared in the dashboard. (A reboot would probably also do the trick, I would imagine.)

**Comment by ArnieO** [comment]
> A reboot would probably also do the trick, I would imagine.

Yes, a reboot would have solved it after Entso-E had published the prices.

**Comment by spacecosmos** [comment]
Aaaand it's blank again... This time - no error though. Anyone else?

![SmartSelect_20230929_202323_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/223df2e3-d3e2-433f-bead-e7b5dfba983e)

**Comment by spacecosmos** [comment]
... Back again today...

![SmartSelect_20230930_072005_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/e8365242-4a94-42ab-9f47-3b188952a072)

PS! Nice touch with the different colours on import vs export in the new release btw. :)

**Comment by tronde-ams** [comment]
Something is weird.

Firefox 115.3.1
Generic ESP32 / Norway NO1 / own api key.

No prices in GUI.
![2023-09-30_181901](https://github.com/UtilitechAS/amsreader-firmware/assets/97398751/75f16d86-0ca3-44c5-a3e6-468c4f419f60)

but present at URL.
![2023-09-30_182024](https://github.com/UtilitechAS/amsreader-firmware/assets/97398751/b1b5fb31-ab42-4e32-89b9-c13fc9db3872)

**Comment by ArnieO** [comment]
> Something is weird.

A browser refresh (F5) did not fix it?

**Comment by tronde-ams** [comment]
No, it did not help with a refresh. Same on another PC. Tested with Firefox and Vivaldi.
The price graph re-appeared some hours later, but with at red error warning for price Api. The prices was correct.

Just now (15:35) no price graph is shown, but both Vivaldi and FF shows prices as http://192.168.1.41/energyprice.json.

This time I have tested with one PC and one Android phone.

Seems really strange too me.

**Comment by spacecosmos** [comment]
Yep - suddenly it went blank (again):

![SmartSelect_20231001_161230_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/18ba7915-0d9a-4746-a487-701e296f2db5)

**Comment by ArnieO** [comment]
Strange indeed, it could be the Entso-E server that struggles. 
One reason for setting up an intermediary server was that we had a period with a string of hickups. 
As long as our server gets a correct read-down, all our users will then be able to read prices from us. (But of course: If prices are not published, we too will be stuck.)
If you activate "Enable price fetch from remote server" without providing Entso-E API key, you will read from our intermediary server. 
What you could do next time you see such an issue is to check if Entso-E has published data, which they normally do somewhere around 13h each afternoon (for next day). [Use this URL](https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=01.10.2023+00:00|CET|DAY&biddingZone.values=CTY|10YNO-0--------C!BZN|10YNO-2--------T&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)), and change to the right date.

**Comment by tronde-ams** [comment]
Why do the prices exist as /energyprice.json if they are not fetched from ENTSO-E?

**Comment by gskjold** [comment]
Definitely something wrong in GUI here, considering that there is data in json

**Comment by gskjold** [comment]
I experienced the same this morning, fix attached:
[esp32solo.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799451/esp32solo.zip)
[esp32.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799453/esp32.zip)
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799454/esp8266.zip)
[esp32c3.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799455/esp32c3.zip)
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799456/esp32s2.zip)

**Comment by Jellybeanz1980** [comment]
Sorry for reopening this case, but I thought that an update would be in place. I've solved my issue on blank Entsoe price. I've found out that after the version 2003.07.00 of the platform-espressif32.zip the file ssl_client.cpp returns error 30592 (fatal error, connection refused) no matter which SSL site tried to be accessed. When running 2003.07.00 everything seems to be OK.

**Comment by gskjold** [comment]
Thanks, did you mean 2023.08.00 vs 2023.07.00 ?

**Comment by Jellybeanz1980** [comment]
Yes, exactly. I even tried later versions up to 2023.10.03, as after that the WifiClientSecure was removed. I had only luck with the version 2023.07.00
