### ISSUE TITLE
No HAN data recieved

### ISSUE THREAD

**Issue by Sommerdal-ufm** [UtilitechAS/amsreader-firmware#644]
HAN data has suddenly stopped working.
Reboot doesn't fix it.

**Hardware information:**
 - Country: DK
 - Meter: 
 - Encryption enabled yes
 - AMS reader: Pow-U
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.2.21
 - MQTT: yes
 - MQTT payload type: [e.g. JSON]
 - HAN GPIO: 5
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [yes/no]

**Comment by jladefoged** [comment]
Same here and also in Denmark. I suspect it's an issue at Radius.

**Comment by Sommerdal-ufm** [comment]
Thank you. I have nailed Radius

**Comment by jladefoged** [comment]
I got in contact with Radius and they have requested Kamstrup to reset the HAN port. I have no idea about the timeframe, but Kamstrup will contact me by email when I can re-insert the module (it's currently removed).

**Comment by Sommerdal-ufm** [comment]
I for a reply today 12:08 , that my HAN port would be reset. 12:47 I was informed by Kamstrup that the reset has been performed and it is working again.
I didn't remove it.
Problem solved.
@jladefoged Can I close the issue, or wait for you?

**Comment by jladefoged** [comment]
Just close the issue. I'll wait for Kamstrup to fix mine.

**Comment by Sommerdal-ufm** [comment]
Supplier problem

**Comment by ArnieO** [comment]
> * AMS reader: Pow-U

Just to be sure future readers of the thread are not confused: 
I assume you mean Pow-K.

Unfortunately, this seems to happen with some Kamstrup meters now and then: A reset is needed, can be done remotely by the grid company. We have so far never seen this on other meter brands.

**Comment by ArnieO** [comment]
We issued a blog post today with information on how the Kamstrup Omnipower issue ("No HAN data") can be remedied. 
https://www.amsleser.no/module/ets_blog/blog?id_post=33
