### ISSUE TITLE
Future energy price missing

### ISSUE THREAD

**Issue by PerBuch54** [UtilitechAS/amsreader-firmware#649]
Showing Future energy price (undefined/100)
What does that mean ?

**Comment by ArnieO** [comment]
What are your settings in this tile? 
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/2287c0cb-5bdd-4efb-a8a2-b38522ffc262)

**Comment by PerBuch54** [comment]
![Udklip](https://github.com/UtilitechAS/amsreader-firmware/assets/128969759/1ece47c0-cb3c-4dfd-8d0d-16290fc420cf)

**Comment by PerBuch54** [comment]
It has been working until yesterday

**Comment by gskjold** [comment]
I experienced the same this morning, fix attached:
[esp32solo.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799451/esp32solo.zip)
[esp32.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799453/esp32.zip)
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799454/esp8266.zip)
[esp32c3.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799455/esp32c3.zip)
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/12799456/esp32s2.zip)

**Comment by PerBuch54** [comment]
Thanks :-)

**Comment by nossaile** [comment]
I had the same issue for two days, but today it's back to normal without doing anything.
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/119525843/e7b8e763-0830-4c96-8691-f73038969be1)
