### ISSUE TITLE
PriceAPI: Internal server error after upgrade to V2.2.23

### ISSUE THREAD

**Issue by eireit** [UtilitechAS/amsreader-firmware#658]
After firmware update from v2.2.22 to the new 2.2.23 i have recieved the fault:  PriceAPI: Internal server error
Have tested new token from Enstoe. still smae error.

Device information
Chip: esp32s2 (160MHz)
Device: [Pow-U+]

Meter
Manufacturer: Kaifa
Model: MA304H3E

Mvh Eirik

**Comment by ArnieO** [comment]
There are occasional hickups with the price reading from Entso-E API. If you just remove the Entso-E token, prices are read from our intermediate server, which is usually more reliable (providing Entso-E has published prices at all).

This is the recommended setting:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/b11d44ad-90b1-4bd2-9bf2-90b1c7adde7d)

**Comment by Allan-Hoejberg** [comment]
I have the same issue after upgrading to 2.2.23
/Allan

Sent from my Nokia 6210

Den 17. okt. 2023 kl. 18.47 skrev eireit ***@***.***>:

﻿

After firmware update from v2.2.22 to the new 2.2.23 i have recieved the fault: PriceAPI: Internal server error
Have tested new token from Enstoe. still smae error.

Device information
Chip: esp32s2 (160MHz)
Device: [Pow-U+]

Meter
Manufacturer: Kaifa
Model: MA304H3E

Mvh Eirik

**Comment by gskjold** [comment]
Regarding running with API key, ENTSO-E is currently sending an error with message "Unexpected exception, please contact support and provide exception ID", I am not sure what their problem is.

Using the service without API key will pass though our servers which is most likely affected by the same problem for many price zones. I will try to get an overview.

**Comment by tb205gti** [comment]
> Regarding running with API key, ENTSO-E is currently sending an error with message "Unexpected exception, please contact support and provide exception ID", I am not sure what their problem is.
> 
> Using the service without API key will pass though our servers which is most likely affected by the same problem for many price zones. I will try to get an overview.

I have created a support ticket at entsoe for this issue.

**Comment by tb205gti** [comment]
Seems it is working again

**Comment by gskjold** [comment]
Indeed, it seems to work now. Painfully slow at times though

**Comment by tb205gti** [comment]
Got validation from entsoe - it was an error on their end. Hotfix have been deployed
