### ISSUE TITLE
Home Assistant / MQTT: AMSreader current hour used resets to 0 more than one time every hour.

### ISSUE THREAD

**Issue by offeloffen** [UtilitechAS/amsreader-firmware#679]
**Describe the bug**
AMSreader current hour used resets to 0 more than one time every hour.

**To Reproduce**
All the time. 
![Screenshot_20231121_082841_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/69957305/6701a431-1d95-4b0f-b3a5-9dce8eb35a37)

**Expected behavior**
Should reset to 0 every hour. 
Even If it should be interrupt in the Internet connection, it should go back to the accumulated value when reconnect? 🤔
(The accumulation works as expected in the WEB user interface) 
![Screenshot_20231122_162454_Home Assistant](https://github.com/UtilitechAS/amsreader-firmware/assets/69957305/05c9dd0e-a946-47b2-95d7-d02e598bf14a)

**Screenshots**
![Screenshot_20231122_153225_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/69957305/74d62460-46a4-4e9c-b251-dbe568e369e1)

**Hardware information:**
 - Country: Norway
 - Meter: Aidon
 - Encryption enabled [yes/no]
 - AMS reader: Pow-U+
 
**Relevant firmware information:**
 - Version: 2.2.23
 - MQTT: yes
 - MQTT payload type: Home Assistant
 - ENTSO-E API enabled: no

**Additional context**

**Comment by gskjold** [comment]
Sounds like your Pow-U reboots frequently. Is power saving set to "Maximum" in you config? Also, "Allow 802.11b modes" should be disabled.

**Comment by john-arvid** [comment]
I have the same issue as @offeloffen , power saving is set to "Maximum", testing now by disabling the "Allow 802.11b modes".

**Comment by offeloffen** [comment]
Thank you for quick answer!  

Power saving was in "Minimum" and "Allow 802.11b modes" was enabled.
I changed those two now and it seems like it fixed the problem.

I'll wait one more day before closing issue.

**Comment by ArnieO** [comment]
Disabling "Allow 802.11b modes" has cured reboot issues for many users.

**Comment by offeloffen** [comment]
So. After a day this is A LOT better, but still reboots some times... 
![bilde](https://github.com/UtilitechAS/amsreader-firmware/assets/69957305/9b60813a-7d22-4024-81e5-8c32c56df687)
Wonder why is still happends.. :/ 
![bilde](https://github.com/UtilitechAS/amsreader-firmware/assets/69957305/f8608b38-9f1b-4e22-9545-8ddb538d9752)

I will try to set the power saving to Minimum again and if it helps.

**Comment by john-arvid** [comment]
Same here, much less reboots but I have had atleast 1 the last 24 hours.
![Skjermbilde 2023-11-23 192933](https://github.com/UtilitechAS/amsreader-firmware/assets/10496003/c6d0248d-e06d-40c1-84f5-e68ceda7ca10)

**Comment by gskjold** [comment]
Obviously something is disturbing power saving on your devices. Are you pulling JSON from the device API or running a constant ping on the device or any other network related traffic?

**Comment by john-arvid** [comment]
I agree, there must be something causing the reboots.
In my case I don't have anything set up other than mqtt, no service/device is polling the amsreader.
I'm using unifi for my wireless network, but I only have one wifi AP.
No multicast device other than some google speakers, and I don't use them often (so not much user created traffic).

**Comment by offeloffen** [comment]
[FIXED]

After I've disabled the "Allow 802.11b legacy rates" it's stable. 
![Screenshot_20231201_085759_Chrome.jpg](https://github.com/UtilitechAS/amsreader-firmware/assets/69957305/3a3507eb-e73c-4a1c-ab99-ca91adf6efe4)
