### ISSUE TITLE
Total meeter consumption 

### ISSUE THREAD

**Issue by eireit** [UtilitechAS/amsreader-firmware#690]
**Describe the bug**
After updating to 2.2.24 the Accumulated import is swapping between total meeter consumption and 0. And then count upwards...
After some time it changes back to the total consumption. When reboot it starts from 0 again...

**To Reproduce**
Logg the value of "ic"

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Hardware information:**
 - Country: Norway
 - Meter: Kaifa MA304H3E
 - Encryption enabled: no
 - AMS reader: [e.g. Pow-U, esp32s2 (160MHz)
 
**Relevant firmware information:**
 - Version: 2.2.24
 - MQTT: yes
 - MQTT payload type: JSON
 - HAN baud and parity: 2400, 8E1
- ENTSO-E API enabled: yes

**Additional context**

**Comment by ArnieO** [comment]
Strange - and unexpected!
Can you try to roll back to v2.2.23 and check that this is indeed related to update from v2.2.23 to v2.2.24?

**Comment by gskjold** [comment]
The accumulated values will always start at 0 on a reboot, and since Norwegian meters only report accumulated values once per hour, it will keep doing so until it gets the correct data. If you see this happen during operation, my guess is that the device reboots.

**Comment by eireit** [comment]
@gskjold gskjold, I think thats the problem. It has started to do reboots, several times a day. 
This has happend after firmware update (2.2.24), any tips to fix this issue?

**Comment by ArnieO** [comment]
> @gskjold gskjold, I think thats the problem. It has started to do reboots, several times a day. This has happend after firmware update (2.2.24), any tips to fix this issue?

Which hardware are you running?

**Comment by eireit** [comment]
Meter: Kaifa MA304H3E
Encryption enabled: no
AMS reader: [e.g. Pow-U, esp32s2 (160MHz)

Downgraded to 2.2.23 and it has not rebooted for 12hours.

**Comment by ArnieO** [comment]
> Downgraded to 2.2.23 and it has not rebooted for 12hours.

Interesting, thank you for reporting!

**Comment by gskjold** [comment]
I am honestly not sure what is going on here, could you export a configuration file and send me? gunnar@amsleser.no

**Comment by gskjold** [comment]
Cant really see anything wrong with your config. Please try v2.2.25 and untick "Allow 802.11b legacy rates"

**Comment by eireit** [comment]
Hi
Upgraded to v2.2.28 and unchecked the allow 802.11b legacy. The it started to reboot again after approx 1 houer (Software reset). I have downgraded to v2.2.27 and will do a similar check.

BR eirik

Fra: Gunnar Skjold ***@***.***>
Sendt: lørdag 23. desember 2023 21:54
Til: UtilitechAS/amsreader-firmware ***@***.***>
Kopi: eireit ***@***.***>; Author ***@***.***>
Emne: Re: [UtilitechAS/amsreader-firmware] Total meeter consumption (Issue #690)


Cant really see anything wrong with your config. Please try v2.2.27 and untick "Allow 802.11b legacy rates"

**Comment by gskjold** [comment]
Any updates on this issue? How is 2.2.28 treating you?

**Comment by eireit** [comment]
Hi, has been stable for over 2 days. looks good...

Br Eirik

26. jan. 2024 kl. 19:51 skrev Gunnar Skjold ***@***.***>:

﻿

Any updates on this issue? How is 2.2.28 treating you?
