### ISSUE TITLE
How to get to GPIO config on AMS reader v2.2.24

### ISSUE THREAD

**Issue by ielthbe** [UtilitechAS/amsreader-firmware#693]
I want to use a temperature sensor connected to the POW-K
How to get to the GPIO config page?

**Comment by gskjold** [comment]
Go to the status page and back up your config for safety. Then click on "Device: Pow-K+". Then change Board Type to "Generic ESP32-S2" and HAN GPIO to GPIO16. DO NOT check the "Clear all other configuration" tickbox, as this will reset your configuration. Click save. You will now have full access to GPIO config on the configuration page.

**Comment by gskjold** [comment]
Interesting, definitely bug
