### ISSUE TITLE
Version v2.2.25 does not work on my Aidon 6534

### ISSUE THREAD

**Issue by niklaslj** [UtilitechAS/amsreader-firmware#702]
**Describe the bug**
Uppgrading from **v2.2.23** to **v2.2.23** this morning. Now it can not read my meter Aidon 6534.
Getting HAN-error. Singel red flash and various error messages indicating read error ie "Serial Parity Error", "Missing frame char..".

Reloaded **v2.2.23** and the amsreader works again.

**To Reproduce**
Upgrade to v2.2.25 and connect to an Aidon 6535 meter.

**Hardware information:**
 - Country: Sweden
 - Meter: Aidon 6534 (6484 RJ45 interface)
 - Encryption enabled no
 - AMS reader: Pow-U+, esp32s2 (160MHz)
 - M-bus adapter: no

**Relevant firmware information:**
 - Version: 2.2.25
 - MQTT: no
 - MQTT payload type: 
 - HAN GPIO: 
 - HAN baud and parity: 2400 8E1
 - ENTSO-E API enabled: no?

**Comment by niklaslj** [comment]
Uploading **v2.2.24** works fine!
Tried v2.2.25 again but same error.

**Comment by gskjold** [comment]
What is the buffer size set to?

**Comment by niklaslj** [comment]
256 (default value, not changed)

**Comment by gskjold** [comment]
Please test v2.2.26 
If you have any issues, try increasing buffer size. I'm guessing 768 should be a good fit for you

**Comment by niklaslj** [comment]
Changed  buffer size to 768 and upgraded to v2.2.28.
Works fine!!

God Jul!
/Niklas
