### ISSUE TITLE
Homeassistant missing some Sensors (MQTT values) from ESP32 with 2.2.27

### ISSUE THREAD

**Issue by gvenaas** [UtilitechAS/amsreader-firmware#704]
Some MQTT messages are lost in Homeassistant with 2.2.27. Reverted to 2.2.25 and all is OK

EX: AMS reader Active import

Chip: esp32 (160MHz)
Device: [Wemos LOLIN D32]

Manufacturer: Kamstrup
Model: 6841121BN243101040

ENTSOE : On

**Comment by daroc** [comment]
Also had MQTT issues with the new firmware, everything works when reverted back to 2.2.25. 

Device information
Chip: esp32s2 (160MHz)
Device: [Pow-K+]

Meter
Manufacturer: Kamstrup
Model: 6841121BN243101040

**Comment by cmock** [comment]
Same here. 2.2.26 and 2.2.27 seem to be affected, from what I see those are only sending the .../prices and .../state topics, .../power, .../realtime, .../energy are missing.

ESP32, MQTT type is HomeAssistant.

**Comment by gskjold** [comment]
Fixed in 2.2.28!

**Comment by cmock** [comment]
That fixed it for me, thanks! (And now go and enjoy the holidays :-)

**Comment by gvenaas** [comment]
Works for mee as well....
