### ISSUE TITLE
The green colour is too bright

### ISSUE THREAD

**Issue by hanche** [UtilitechAS/amsreader-firmware#708]
When voltages and currents are displayed as green bars with a number attached, the number is too hard to read because of too little contrast. This is so whether the number appears as white text on a green background or as green text on a white background (when the bar is too low to fit the text inside). I really have to squint to read it!

To fix this, the standard green, `#32d900`, should be replaced by a darker green. Even a modest reduction in brightness, as to `#32b000`, would probably help greatly.

Alternatively, perhaps using black for the text would solve the issue in a different way. I think the current green is bright enough for black text on that background to be legible.

Edit: It would be even better if that colour were settable by some custom CSS. Then the user could override the builtin colour with a user stylesheet.

**Comment by ArnieO** [comment]
So this regards the text in these bars:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/8617c183-88f2-4588-8a31-fb56c7cb9ed7)

I agree, the contrast is a bit weak. Black or grey text would probably be a better solution. What do you think, @gskjold ?
