### ISSUE TITLE
Expose tariff thresholds to MQTT

### ISSUE THREAD

**Issue by slippern1** [UtilitechAS/amsreader-firmware#716]
Is it possible to expose the configured tariff thresholds to MQTT?

**Comment by ArnieO** [comment]
Yes, technically possible - but it is a bit difficult to understand the need, as these values are static. If you need them in Home Assistance (for instance), you can just enter them there. 

What is the intended way to use that information, and why would it be useful to receive them over MQTT?

**Comment by slippern1** [comment]
I want to use the tariff thresholds in node-red flows without programming them manually.
My grid company recently changed the thresholds from a few to 20 steps.

**Comment by gskjold** [comment]
Here is a version with this feature:
[esp32s3.zip](https://github.com/user-attachments/files/15685394/esp32s3.zip)
[esp32solo.zip](https://github.com/user-attachments/files/15685395/esp32solo.zip)
[esp32.zip](https://github.com/user-attachments/files/15685396/esp32.zip)
[esp32c3.zip](https://github.com/user-attachments/files/15685400/esp32c3.zip)
[esp8266.zip](https://github.com/user-attachments/files/15685401/esp8266.zip)
[esp32s2.zip](https://github.com/user-attachments/files/15685402/esp32s2.zip)

**Comment by slippern1** [comment]
Thanks, i will test within this week!

**Comment by slippern1** [comment]
It sure does work :-)
From an automation / developer view, an array or something with the values in the same entity is probably easier to work with. 

<img width="215" alt="image" src="https://github.com/UtilitechAS/amsreader-firmware/assets/93949744/98d15d17-dc03-40ec-9025-a8bf253ffc04">
