### ISSUE TITLE
Pow-P1 can't connect to WiFi

### ISSUE THREAD

**Issue by Jerroder** [UtilitechAS/amsreader-firmware#721]
**Describe your problem**
When entering my SSID and password, it doesn't seem to connect. I don't see a DHCP lease for the device in my router's UI and when I set a static IP in the Pow-P1 interface, I can't ping it from other devices. Not sure if I did something wrong, it seems pretty simple. My wifi is 2.4GHz, there is no special character apart from _ in the SSID.

The HAN port isn't connected yet, I'm just trying to set it up while powering via USB before connecting it to the meter outside.

**Hardware information:**
 - Country: 
 - Meter: 
 - Encryption enabled: no
 - AMS reader: Pow-P1
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.2.28
 - MQTT: yes
 - MQTT payload type: JSON
 - HAN GPIO: 
 - HAN baud and parity: 
 - Temperature sensors
 - ENTSO-E API enabled: no

**Comment by Jerroder** [comment]
Yes I do have access to it when it's in Access point mode and it fails to connect to my wifi network. I forgot to mention the red LED blinks once and then 3 times, so it receives no data from HAN port (which is expected) and it fails to connect to my wifi access point, which is 3 meters away.

Here hare the config and info:
<img width="1532" alt="Screenshot 2024-01-25 at 11 39 51" src="https://github.com/UtilitechAS/amsreader-firmware/assets/29119296/1062e61b-e641-42a0-822f-7eb51bafdf72">
<img width="1532" alt="Screenshot 2024-01-25 at 11 38 58" src="https://github.com/UtilitechAS/amsreader-firmware/assets/29119296/46cd2816-2fdd-443b-b359-179285e4d437">

**Comment by ArnieO** [comment]
Strange, I don't see anything suspicious here. 

- Does your Wi-Fi password have any strange characters (other than letters and numbers and "normal" chaacters like §!#¤%& etc?
- Is your Wi-Fi password extremely long?
- What are the parameters you used when you tried Static IP? Are you sure you gave it an IP that is not already in use?

**Comment by Jerroder** [comment]
It is registered correctly in the backup

**Comment by gskjold** [comment]
I have a theory related to your long password. Please try the attached firmware, guide here: https://github.com/UtilitechAS/amsreader-firmware/wiki/Flashing-via-web-GUI

[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/14051374/esp32s2.zip)

**Comment by Jerroder** [comment]
Same problem with the new firmware, even after a factory reset

**Comment by ArnieO** [comment]
Could you temporarily change the password to something shorter - just so we can confirm whether it is the password that causes this issue?

**Comment by Jerroder** [comment]
Even an 11 characters long password doesn't work

**Comment by ArnieO** [comment]
OK, thank you! So we know that the password length is not the problem. 
This is a highly unusual situation, so please forgive a "stupid" question: Are you 100% certain there is not a spelling error in your AP name?

These two are not identical
loT-network
IoT-network
The first starts with a lowercase L, the second with uppercase I.

**Comment by Jerroder** [comment]
I understand, but just to be sure I copied and pasted the SSID and password from the AP's UI directly

**Comment by ArnieO** [comment]
@gskjold : Can he do a [Telnet debug](https://www.amsleser.no/module/ets_blog/blog?id_post=24) while in AP mode, and if so: Will there be any additional information that can help figuring out what is going on here?

**Comment by Jerroder** [comment]
Well I just restarted the AP and it now works, I have no idea what the problem could be. I hope it won't disconnect after a while though

Thank you for your help, I'm sorry I wasted your time :/

**Comment by ArnieO** [comment]
OK, good to hear that it works!
And I'll try to remember "Try restarting your router" in future debug sessions. 😄

**Comment by gskjold** [comment]
For reference you will be able to use telnet debugging in AP mode, but when it starts connecting to AP it will shut down AP mode. The only way to see what is going on during connect is to hook up a serial console.
