### ISSUE TITLE
Kaifa MA309 Parity even instead off non

### ISSUE THREAD

**Issue by tremichl** [UtilitechAS/amsreader-firmware#723]
Parity 8N1 as described in Known hardware configurations for Kaifa MA309 causes "Payload boundry flag missing". 8E1 is working fine at SalzburgNetz/Austria

**Comment by ArnieO** [comment]
Thank you for the feedback, [I have corrected it now](https://github.com/UtilitechAS/amsreader-firmware/wiki/Known-hardware-configurations)!

**Comment by tremichl** [comment]
Thanks!
