### ISSUE TITLE
Custom Price API endpoint

### ISSUE THREAD

**Issue by rpirsc13** [UtilitechAS/amsreader-firmware#724]
**Is your feature request related to a problem? Please describe.**
The problem with the provided price options is that they do not include tarrifs, so the end price calculation is far below the actual price I will be paying.

**Describe the solution you'd like**
Provide the option to input a custom API endpoint.

**Additional context**
Along with this, we would of course need some documentation on how to format the  request/response.

**Comment by gskjold** [comment]
Thanks for your input. This is something that would only benefit very few users, so we will not include this in the software. Regarding tariff, please see #252
