### ISSUE TITLE
Phase L2 shows as unavailable under Amperage

### ISSUE THREAD

**Issue by shadowano** [UtilitechAS/amsreader-firmware#729]
**Describe your problem**

Phase L2 shows as unavailable under Amperage
This happened some time after my basement was flooded. 

Any idea what this could be? Electrician has checked everything but haven't found any issues.

I live in Norway, Oslo. 

[
![Screenshot_20240208_111408_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/3582807/7af1c8d3-cec1-475d-bd72-c2979febd52c)
![Screenshot_20240208_111454_Chrome](https://github.com/UtilitechAS/amsreader-firmware/assets/3582807/ec2345fe-6a49-4d20-bd64-345cf6412a6f)
](url)

**Comment by ArnieO** [comment]
Yes we know exactly what this is, please see explanation in this blogpost: https://www.amsleser.no/module/ets_blog/blog?id_post=31
