### ISSUE TITLE
Rounding month max

### ISSUE THREAD

**Issue by SVH-Powel** [UtilitechAS/amsreader-firmware#730]
**Describe the solution you'd like**
I am looking at this code section in getmonthmax

for(uint8_t i = 0; i < 5; i++) {
        if(!included[i]) continue;
        maxHour += data.peaks[i].value;
    }
    return maxHour > 0 ? maxHour / count / 100.0 : 0.0;

As I understand it, you store integer values in data.peaks[i].value in kwh multiplied by 100.

When you do maxhour / count this will be an integer division and there will not be a "natural" rounding.

So if the month max is 9.9999 kwh, it will be reported as 9.99 and not 10.00. Or 9.79667 will be reported as 9.79 and not 9.80.

**Comment by gskjold** [comment]
Added natural rounding
