### ISSUE TITLE
Bug or what... MY AMS do miss 

### ISSUE THREAD

**Issue by LA5HJA** [UtilitechAS/amsreader-firmware#731]
**To Reproduce**
Like this all the time here.

**Screenshots**

**Hardware information:**
 - Country: Norway
 - Meter: Aidon Model 6525
 - Encryption enabled [yes/no]
 - AMS reader: [e.g. Pow-U, ESP32 etc]
 - M-bus adapter (if applicable):
![AMS-bug](https://github.com/UtilitechAS/amsreader-firmware/assets/57863859/16c968be-bac9-4c6a-a347-94395319aaec)

**Relevant firmware information:**
 - Version: 2.2.28
 - MQTT: yes
 - MQTT Raw
 - HAN GPIO: [15
![AMS-bug](https://github.com/UtilitechAS/amsreader-firmware/assets/57863859/80b823fc-2eb5-488f-8aca-03771772ff9f)

 - HAN baud and parity: [e.g. 2400 8E1]

 - ENTSO-E API enabled: yes

**Additional context**
Running 2 x ESP32 on the RS484 bus, both do miss Apmerage on L2, both run same SW and HW
![AMS-bug](https://github.com/UtilitechAS/amsreader-firmware/assets/57863859/57967bf9-1813-44fc-93dc-2c98b4563cae)

**Comment by tronde-ams** [comment]
Aidon 6525 does not give us the value for I2. It is impossible to calculate the value with the data available from the meter. Earlier FW tried to calculate it, but gave mostly useless values.

**Comment by tronde-ams** [comment]
I wrote something in Norwegian here
https://github.com/UtilitechAS/amsreader-firmware/issues/686

**Comment by ArnieO** [comment]
https://www.amsleser.no/module/ets_blog/blog?id_post=31
