### ISSUE TITLE
Login with URL including username and password

### ISSUE THREAD

**Issue by sm1oii** [UtilitechAS/amsreader-firmware#737]
Hi

I have my pow-p1 reader and other devices under subdomains. I would like to log into my pow-p1 reader like this : 

https://username:password@p1.mydomain.com

This is a standard format that works exellent on my IP-cameras and other devices but NOT on pow-p1 reader :-(
Can this feature be included in next release?

/Harri

**Comment by Noschvie** [comment]
Why not using a reverse proxy for that? Basic Auth and https

**Comment by ArnieO** [comment]
> Why not using a reverse proxy for that? Basic Auth and https

Can you elaborate on how to do that?

**Comment by sm1oii** [comment]
> Why not using a reverse proxy for that? Basic Auth and https

Sounds like a good idea but against company network policy and network restrictions.

**Comment by Noschvie** [comment]
Have a look for example to pfSense, HAProxy and basic auth
[User Authentication with HAProxy on pfSense](https://hochwald.net/user-authentication-with-haproxy-on-pfsense/)[](https://hochwald.net/user-authentication-with-haproxy-on-pfsense/)
But also supported by Traefik and NGINX

**Comment by gskjold** [comment]
Logging in with http://user:pass@mylocalip works fine, this must be related to your  proxy settings
