### ISSUE TITLE
Need help: UI translation to Danish

### ISSUE THREAD

**Issue by ArnieO** [UtilitechAS/amsreader-firmware#748]
The soon-to-be-released firmware version 2.3 will have a feature to change user interface language. 

So far we have the following languages ready:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/5c5efda2-04ea-4ed9-9687-2ef1bcf46344)

But we do not yet have a translation to Danish. 😐 
![th-2895587530](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/12d0909b-62cf-4ef3-8373-633312317ab8)

If you would like to help us with that, please go to https://localazy.com/p/amsleser and start translating!

**Comment by Saturate** [comment]
I started doing some of the translations, hope others will help as well!

**Comment by ArnieO** [comment]
> I started doing some of the translations, hope others will help as well!

Thank you for starting, it would be great to have this done before we release v2.3. There are in total a bit more than 300 terms to translate. Should not take more than 1/2 hour in total (took me around that time when I did the translation to French).
There are automatic translation suggestions - but they cannot always be used. On some of the terms there are screenshots attached to help out with showing the context.
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/ae34e6f9-4b66-442d-9a7f-09054da5a3ea)

**Comment by ArnieO** [comment]
Danish translation is now ready. Thank you very much for your help, @Saturate ! 🌹

**Comment by Saturate** [comment]
@ArnieO No problem :) actually came to see if I could help out with the web part.
