### ISSUE TITLE
Wrong DNS when DHCP is enabled

### ISSUE THREAD

**Issue by Bruners** [UtilitechAS/amsreader-firmware#752]
When DHCP is enabled the DNS value sometimes gets the wrong value, causing price fetching to fail. Took a while to figure this out since price fetching would work for a while and then randomly started to fail. 

This is the only device on the network that has this problem.

![Screenshot_20240325-235724](https://github.com/UtilitechAS/amsreader-firmware/assets/111137/fc4ace29-092d-4091-8668-622d57e5bc13)

**Comment by ArnieO** [comment]
Interesting observation, but there could be other reasons. 

1. Which setting do you use for price fetching (Entso-E or our server)?
2. I don't recognize that DNS you are using. Did you try one of the larger, public ones - like 1.1.1.1?

**Comment by Bruners** [comment]
Still getting issues now even with static ip settings. I have set static dns to 1.1.1.1/8.8.8.8. The DHCP (vendor locked) supplies rest of the network with 192.168.10.1 + fe80::becf:4fff:fe35:513d%wlan0

![Screenshot_20240327-094956](https://github.com/UtilitechAS/amsreader-firmware/assets/111137/0a3a3065-796b-48b0-a860-c6b5f5b82fa9)
![Screenshot_20240327-094944](https://github.com/UtilitechAS/amsreader-firmware/assets/111137/e2ed8dce-341f-4a92-be96-444ef2c4d8ea)

The settings for price fetching

![Screenshot_20240327-095029](https://github.com/UtilitechAS/amsreader-firmware/assets/111137/7f0224da-1fa6-4153-9f2a-310e86134adc)

**Comment by ArnieO** [comment]
OK, you're reading prices directly from Entso-E. 
We have experienced relatively frequent issues with getting response from their API, so we have established an intermediate server. If you delete the Entso-E API key (but leave "Enable price fetch" enabled), you will read from our server instead.

**Comment by Bruners** [comment]
Will give that a try

**Comment by gskjold** [comment]
This is a known issue, outside of our control. This is related to IPv6 DNS being applied as if it was IPv4, even if IPv6 is not enabled in firmware. See https://github.com/espressif/arduino-esp32/issues/8221

The firmware monitors the DNS and changes it back on interval. Also, IPv6 will be available in v2.3
