### ISSUE TITLE
Possible error in the export gauge

### ISSUE THREAD

**Issue by arnwik** [UtilitechAS/amsreader-firmware#753]
I have PV panels, and are producing approx 1700 watts at the moment, but the AMS reader web page shows exporting approx 3400 watts in the export gauge. It was not exactly 2x, but it was obviously wrong. 
I will monitor this further, and provide more info if available. 

**Expected behavior**
A clear description of what you expected to happen.

**Hardware information:**
 - Country:  Norway
 - Meter: Kamstrup
 - Encryption enabled: NO
 - AMS reader: ESP32 
 - M-bus adapter (if applicable): 

**Relevant firmware information:**
 - Version: 2.2.28
 - MQTT: yes
 - MQTT payload type: json
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [yes/no]

**Additional context**

**Comment by ArnieO** [comment]
That sounds strange. 
Can you run a Telnet debug when this happens - and post the output here?
https://www.amsleser.no/module/ets_blog/blog?id_post=24
It will enable us to see what the meter reports.
