### ISSUE TITLE
Weird price value today

### ISSUE THREAD

**Issue by spacecosmos** [UtilitechAS/amsreader-firmware#754]
**Describe the bug**
Not sure what happened, but I was looking at the price value for today's usage (from midnight to now 08:50) and it showed a negative value of approximately -640 NOK. 

Looking at the future energy price during the night, it hasn't been _that_ cheap. I then thought of restarting the unit to see if that would solve the glitch and did so, but now it shows even higher, 1323.3 NOK.

(Does this maybe has to do with the summer time correction during the night?)

**Expected behavior**
Calculate correct value depending on the price given.

**Screenshots**
![Screenshot_20240331_085106_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/4deb0caa-fd67-4139-8b6a-a9a42c9c82d3)

![Screenshot_20240331_090306_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/b70ff150-d654-4099-9c2d-1f3b8d25b29e)

**Hardware information:**
 - Country: Norway
 - Meter: Kamstrup
 - Chip: esp32s2 (160MHz)
 - Device: Pow-K+

**Additional context:**
Not sure if I want to try rebooting again, afraid it would keep increasing. I have PV panels btw, hence the export values.

**Comment by spacecosmos** [comment]
Update: Now it's down a bit again (?).

[Screenshot_20240331_092402_Opera](https://github.com/UtilitechAS/amsreader-firmware/assets/55928670/43c04226-f9b7-4362-9134-ebb45d7cb2ec)

**Comment by ArnieO** [comment]
@gskjold : Maybe some weird DST bug?

**Comment by gskjold** [comment]
I hate DST... Probably...
