### ISSUE TITLE
MQTT logging interval

### ISSUE THREAD

**Issue by atle85** [UtilitechAS/amsreader-firmware#756]
**Describe the bug**
My Home Assistant database which is created from MQTT data from PowU is growing out of control, mainly because of the PowU data.

**To Reproduce**
1.) Add Home Assistants MQTT broker as MQTT destination in PowU
2.) Open Home Assistants databse with addon "SQLite Web"
3.) Run the following command:
SELECT
  COUNT(*) AS cnt,
  COUNT(*) * 100 / (SELECT COUNT(*) FROM states) AS cnt_pct,
  states_meta.entity_id
FROM states
INNER JOIN states_meta ON states.metadata_id=states_meta.metadata_id
GROUP BY states_meta.entity_id
ORDER BY cnt DESC

**Expected behavior**
There should be a longer logging interval to avoid filling up the database. Add option to define MQTT minimum interval in seconds?

**Screenshots**

![image](https://github.com/UtilitechAS/amsreader-firmware/assets/35543861/5aea9cdc-15aa-4851-86d2-5de02cbc6652)
(The other large sensor (tesla_available_amps_new) is also large because it's reading from this sensor and triggered by sensor change. ams_powu_p is the largest, but other sensors are also taking up lots of space. )

**Hardware information:**
 - Country: Norway
 - Meter: Tensio TS (KAIFA?)
 - Encryption enabled no
 - AMS reader: Pow-U
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.2.19
 - MQTT: yes
 - MQTT payload type: Home Assistant
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]
 - Temperature sensors [e.g. 3xDS18B20]
 - ENTSO-E API enabled: [yes/no]

**Additional context**

**Comment by ArnieO** [comment]
It is not clear to me what your request or concern is.

Most users appreciate having real time information in HA, which means it needs to receive each measurement done by the meter. 
I am not HA user myself, but my impression is that smart home systems (at least some) will do some kind of data reduction on old measurements, to avoid the database from getting filled up with old data, while maintaining the ability to show long-term plots - while showing detailed information on the shorter, recent time span.
Doesn't Home Assistant do that? 
Is there maybe a setting for the sensor to do such data reduction?
Or maybe some other method must be used, for instance storing old data in InfluxDB, as suggested here: https://community.home-assistant.io/t/methods-of-historical-data-reduction/259891

HA users: Which strategies are you using?

**Comment by atle85** [comment]
Home assistant reads all data from the MQTT broker into its database. 

Database reduction is done by:
1.) a max days limit for storing data. 
2.) after day-limit the data is converted to long term graphs taking up less space. 

However the logging in the first days takes up lots of space, and PowU is the cause. Many users ignore logging of sensor data totally in cases like with PowU. Other noisy sensors are typically motion sensors etc. My request would be an option to add a minimum logging interval in seconds. This is standard for other software I have which logs via MQTT. Otherwise I would have to ignore the sensors for recordring or create custom new sensors reading the PowU sensor but implementing some kind of interval - which is a lot more messy than an interval from the source.

**Comment by ArnieO** [comment]
> My request would be an option to add a minimum logging interval in seconds. This is standard for other software I have which logs via MQTT.

OK, I understand. 
Thank you for the proposition, we will certainly take this under consideration. 

We are slowly but surely approaching the limit of the capacity of the microcontroller module, so IF we decide to implement this, I am not sure we'll be able to do averaging of the values between MQTT transmissions (which would surely be preferable).

**Comment by avandorp** [comment]
I appreciate the real time values from my meter (every 5 seconds) and my home assistant db is quite moderate. 

For the meters I know the totalized values are the important ones and  the current values are really just snapshots. So not having any averaged values would be completely ok and expected from my point of view. Another ESP32 based project for solar inverters has a setting for MQTT publishing frequency: https://github.com/tbnobody/OpenDTU/. No averaging is done as far as I know.

I do like the approach of some battery-powered Z-Wave sensors where you can define offsets. A temperature sensor running for 10 years on a small battery e.g. only sends an update whenever the temperature has changed half a degree celcius or more compared to the previously sent temperature. If no temperature change occurs, it sends an update after 24 hours. That saves both battery and db space. But it probably isn't the approach I would take with a utility power meter.

**Comment by atle85** [comment]
@avandorp Mine seems to be updating every second. So the interval seems to differ based upon the AMS meter. Right now sensor.ams_powu_p is eating 10% of the database (and another sensor based upon that additionally 10% more), even though I manually purge those sensors every night.

**Comment by ArnieO** [comment]
@atle85 : It is correct that the reporting interval differ between AMS meters. Kamstrup Omnipower is the slowest (10 seconds), some meters with P1 interface in used in Sweden and Denmark are at 1 second.

So I think the concern of "exploding" data base is a real issue that we need to address. 
Modifiable MQTT report rate sounds like a pragmatic solution.

**Comment by ArnieO** [comment]
Will be implemented in upcoming update.
Thank you for the suggestion!
