### ISSUE TITLE
2.3 live plot not working, causing browser tab crashes and freezes

### ISSUE THREAD

**Issue by ThorAlex87** [UtilitechAS/amsreader-firmware#759]
**Describe the bug**
When loading the web UI the browser tab slows down, freezes, crashes or has other issues. This happens only when realtime plot is active, if it's turned off everything seems to work fine. This happens in both firefox and chrome on my pc, but firefox on my android tablet seems to work fine except the realtime plot being completely empty. Problem also happens in /configuration and /status, so might be related to something happening in the background and not the visual plot itself.

**To Reproduce**
Go to the web UI in firefox or chrome on PC while realtime plot is set to auto or enabled.

**Expected behavior**
Everything works regardless of browser and device

**Screenshots**

**Hardware information:**
 - Country: Norway
 - Meter: Kaifa
 - Encryption enabled no
 - AMS reader: Pow-U+

**Relevant firmware information:**
 - Version: 2.3.0
 - MQTT: yes
 - MQTT payload type: Home-assistant
 - ENTSO-E API enabled: yes

**Additional context**
Could be something about my pc, but I don't have another to test with.

**Comment by gskjold** [comment]
Interesting issue, I have yet to see this myself, but I'm guessing there is something wrong here, and we'll definitely find it

**Comment by ThorAlex87** [comment]
> Interesting issue, I have yet to see this myself, but I'm guessing there is something wrong here, and we'll definitely find it

Let me know if there is anything I can do to help :)

**Comment by gskjold** [comment]
If you could try this build, that would be great:
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/14893223/esp32s2.zip)

Guide for flashing here: https://github.com/UtilitechAS/amsreader-firmware/wiki/Flashing-via-web-GUI

If there is still an issue, I'd like to see a screeshot of the debugger in Chrome (Press F12), in the console it will show some debugging:
![Screenshot from 2024-04-06 12-19-15](https://github.com/UtilitechAS/amsreader-firmware/assets/4446828/e4a50338-60ab-499d-ad05-d5a5e34aa2c4)

**Comment by ThorAlex87** [comment]
Thanks! No crashing or other performance issues wit the new build. The graph is still not working right, but it's not completely blank as before. 

![Untitled](https://github.com/UtilitechAS/amsreader-firmware/assets/111507745/6b594ba3-ce4e-4a29-847d-56c4c64251c3)

**Comment by gskjold** [comment]
You have production?

**Comment by ThorAlex87** [comment]
> You have production?

Yeah, 15kwp solar and the sun is out so the -13000w number is real. 

(BTW, should that not scale to 13kw like the other graphs?)

**Comment by gskjold** [comment]
This was the problem, scaling on that graph was broken :) Patch coming up soon
