### ISSUE TITLE
MQTT stopped working after upgrading to FW2.3.1

### ISSUE THREAD

**Issue by evhetlan** [UtilitechAS/amsreader-firmware#762]
MQTT stopped working after upgrading to FW 2.3.1, comes up with the message: Connection failed
Has worked perfectly for a few years until now, have restarted everything with no luck
![AMS feil](https://github.com/UtilitechAS/amsreader-firmware/assets/110242351/60718368-4200-41a7-aa01-dc8cb4668e46)

**Comment by damtjern** [comment]
Same issue here. Tried entering mqtt details again but no luck
Esp8266 Pow-U

**Comment by bjornsivertsen** [comment]
Same issue here

**Comment by gskjold** [comment]
Device type, payload type, ssl etc

**Comment by evhetlan** [comment]
![Skjermbilde 2024-04-07 113538](https://github.com/UtilitechAS/amsreader-firmware/assets/110242351/f7b84df6-42a0-4a32-88d3-0e0aed584a09)

**Comment by gskjold** [comment]
Please try attached firmware
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/14896670/esp8266.zip)
https://github.com/UtilitechAS/amsreader-firmware/wiki/Flashing-via-web-GUI

**Comment by evhetlan** [comment]
![Skjermbilde 2024-04-07 120323](https://github.com/UtilitechAS/amsreader-firmware/assets/110242351/219f4ab8-54a7-485b-b8e7-9b90d3f96aac)

**Comment by gskjold** [comment]
Please re-enter your credentials to double check that it is not that

**Comment by gskjold** [comment]
Since it changed from "connection failed" to "connection denied"

**Comment by evhetlan** [comment]
![Skjermbilde 2024-04-07 121821](https://github.com/UtilitechAS/amsreader-firmware/assets/110242351/422a44c4-0160-4011-addf-af97de706ec1)

**Comment by spacecosmos** [comment]
Same here but, I left it for a few minutes and it connected. So for everyone having this issue, I recommend just wait for while. (Approximately 5 minutes.)

It might if course be something wrong as well, but it may also work after a few minutes. Doesn't hurt to try waiting before starting other stuff.

**Comment by evhetlan** [comment]
Got it working now
![Skjermbilde 2024-04-07 123017](https://github.com/UtilitechAS/amsreader-firmware/assets/110242351/a4660a24-9e6a-4f19-81c2-cc1374904708)

**Comment by evhetlan** [comment]
After I got MQTT working again with the FW you posted here, I upgraded to FW 2.3.1 and everything stopped working. Waited 10 min, and restarted Homey without success. Then I updated with new FW again, now everything worked straight away.
