### ISSUE TITLE
Import value stuck

### ISSUE THREAD

**Issue by Cartoon-Dude** [UtilitechAS/amsreader-firmware#766]
Since the update to v2.3.1, the import value is stuck.

![Capture d’écran du 2024-04-09 17-10-10](https://github.com/UtilitechAS/amsreader-firmware/assets/133660601/64242714-698a-4328-b51c-e579de115569)
![Capture d’écran du 2024-04-09 17-19-40](https://github.com/UtilitechAS/amsreader-firmware/assets/133660601/995ecaf9-06a8-42f5-9890-2e2d68aa0d1c)

It's staying to the highest value, and also not logical to have both import and export at the same time.
With a reboot the import value is reseted, and back to displaying the highest.

ESP8266
Iskra AM550

**Comment by ArnieO** [comment]
Which of the values is stuck - Power or Energy?

**Comment by gskjold** [comment]
The power, this specific meter should only show import or export, not both. I just found the issue.
