### ISSUE TITLE
Real time plot and user interface settings disappear

### ISSUE THREAD

**Issue by ma10as123** [UtilitechAS/amsreader-firmware#767]
**Describe the bug**
Real time plot and user interface settings disappear when updating to 2.3.2
![Skjermbilde 2024-04-09 21 12 55](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/46713925-39b6-4641-831b-c70a383a6e1a)
![Skjermbilde 2024-04-09 21 13 02](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/1d6f7bc2-eae5-4826-9679-4a9c1d99bb9d)
![Skjermbilde 2024-04-09 21 14 38](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/f66bb941-b70a-4095-afdc-a4a84aa67675)
![Skjermbilde 2024-04-09 21 14 44](https://github.com/UtilitechAS/amsreader-firmware/assets/112497181/021824f1-32cf-4d95-9169-b6c4680c47b6)

**Comment by gskjold** [comment]
Thanks!
2.3.3. should fix your issue

**Comment by ma10as123** [comment]
Yes it works now :)
