### ISSUE TITLE
VCC Multiplier reverts to 1 after reboot

### ISSUE THREAD

**Issue by mrkaasa** [UtilitechAS/amsreader-firmware#768]
The voltage on my Pow-U (USB powered) is slightly high, 3.4V. I usually set it to 0.98, to get 3.33V, and this still works fine.

But when rebooting the device, the multiplier reverts back to 1.0
I belive this was working correctly on v2.2.28. But after upgrading to v2.3.3 it doesn't.

It's not urgent to fix this for me, the device still seems to run fine with multiplier at 1.0 and 3.4V. But others might be affected.

My setup:
Device information
Chip: esp8266 (80MHz)
Device: [Pow-U (GPIO12)](http://192.168.1.3/vendor)
Last boot: 10.04.2024 12:57
Reason: Software restart (4/0)
[Update consents](http://192.168.1.3/consent)Reboot
Meter
Manufacturer: Kamstrup

**Comment by ArnieO** [comment]
Thank you for reporting this!

The old ESP8266 need individual adjustment of the ADC (analog-to-digital converter), as you have noticed. 
The ESP32s we use on newer devices are factory calibrated, and do not need such individual adjustment. 

But apparently something has happened in the GUI here. @gskjold will look into it and if a bug is confirmed include a fix in next upgrade.

**Comment by gskjold** [comment]
Please try the attached firmware:
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/14936395/esp8266.zip)

https://github.com/UtilitechAS/amsreader-firmware/wiki/Flashing-via-web-GUI

**Comment by mrkaasa** [comment]
> Please try the attached firmware: [esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/14936395/esp8266.zip)
> 
> https://github.com/UtilitechAS/amsreader-firmware/wiki/Flashing-via-web-GUI

Thanks! It works now with the attached firmware.
