### ISSUE TITLE
Possible bug while importing real time calculations from FW 2.2.8

### ISSUE THREAD

**Issue by tronde-ams** [UtilitechAS/amsreader-firmware#775]
Generic Esp32

I did not pay attention to this before I got my electricity bill today, but something got wrong between 2.2.8 and 2.3x. I have some memory about it being present before 2.3.4, but can't say for sure.

My other unit was not active before 2.3.1, so I can't compare.

I did not save config, so I do only have a screenshot.

This is 2.2.8 and is correct.

![ok](https://github.com/UtilitechAS/amsreader-firmware/assets/97398751/1ef2657a-a24c-477f-9996-ab204cd7d3f3)

This is 2.3.4 and the value for last month kWh is wrong. It is the same value as last month cost. Can it be a mix-up there?

![wrong](https://github.com/UtilitechAS/amsreader-firmware/assets/97398751/1942310f-f58c-467b-97b9-d86fd6cee8ce)

**Comment by tronde-ams** [comment]
I am certain it is a mix-up in the GUI.

This is from the saved config of 2.3.4 which shows wrong values just now. 

energyaccounting 6 4 6.02 385.35 **1246.35** 0.00 0.00 0.00 10 3.34 2 4.16 3 3.37 4 3.58 5 3.92 **1872.46** 0.00

1872 is present there, but not in the GUI.

**Comment by gskjold** [comment]
You are absolutely right about that, thanks!

**Comment by ArnieO** [comment]
We received message by email from an other customer who has an issue that seems related. 
- Older Pow-U with ESP8266
- Upgrade from v2.2.28 to 2.3.4

This is shown in GUI, 1868 kWh last month:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/f4fdb689-2621-43db-9ac3-d334c76200b0)

While energy company website says 2819 kWh. 

Also: 
During first 3 hours after upgrade, hourly readings were averaged, while this error message was observed: 
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/a5dc5249-ea62-4a32-8b3f-f1e5fb3f3cfb)
After that, hourly messages no longer averaged, error message disappeared.
