### ISSUE TITLE
Javascript error in the web interface

### ISSUE THREAD

**Issue by Cartoon-Dude** [UtilitechAS/amsreader-firmware#777]
After the update to version 2.3.4, the web interface is staying white and has some javascript error in the console.
![Capture d’écran du 2024-04-15 13-13-57](https://github.com/UtilitechAS/amsreader-firmware/assets/133660601/704f8989-4078-47ad-8866-325d7875a124)

**Comment by gskjold** [comment]
It looks like the js file was ended prematurely on download. This should not happen, still a problem?

**Comment by Cartoon-Dude** [comment]
Not having any problem since the update to 2.3.5
