### ISSUE TITLE
MQTT JSON price data is sometimes malformed

### ISSUE THREAD

**Issue by olupton** [UtilitechAS/amsreader-firmware#784]
**Describe the bug**
With 2.3.5, my Pow-U now supports configuring and publishing price schedule data.
Unfortunately this seems to be malformed:
```
{"id":...,"prices":{"0":0.2427,"1":0.2427,"2":0.2427,"3":0.2427,"4":0.2427,"5":0.2427,"6":0.2427,"7":0.2427,"8":0.3479,"9":0.3479,"10":0.3479,"11":0.3479,"12":0.3479,"13":0.3479,"14":0.3479,"15":0.3479,"16":0.3479,"17":0.3479,"18":0.3479,"19":0.3479,"20":0.3479,"21":0.3479,"22":0.3479,"23":0.3479,"24":0.2427,"25":0.2427,"26":0.2427,"27":0.2427,"28":0.2427,"29":0.2427,"30":0.2427,"31":0.2427,"32":0.3479,"33":0.3479,"34":0.3479,"35":0.3479,"36":0.3479,"37":0.3479,"min":0.2427,"max":0.3479,"cheapest1hr":"2024-04-21T20:00:00Z","cheapest3hr":"2024-04-21T20:00:00Z","cheapest6hr":"2024-04-21T20:00:00Z"}}":1713730047,"a":true}
```

From a quick look at the code, it looks like an off-by-one error here is overwriting the null terminator: https://github.com/UtilitechAS/amsreader-firmware/blob/05506cdc9fa4002b925713101e1422b60776c29e/lib/JsonMqttHandler/src/JsonMqttHandler.cpp#L385

**To Reproduce**
Configure MQTT output in JSON (Classic) format and configure a price schedule.
In my case, the schedule is static (it just varies with the time of day).
The output is sometimes well-formed, perhaps depending on the last usage of the buffer.

**Expected behavior**
Valid JSON should be produced.

**Hardware information:**
 - Country: Switzerland
 - Meter: Landis+Gyr E450
 - Encryption enabled: no
 - AMS reader: Pow-U

**Relevant firmware information:**
 - Version: 2.3.5
 - MQTT: yes
 - MQTT payload type: JSON (Classic)

**Comment by gskjold** [comment]
Thank you for the thorough report!
Please try the attached firmware
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15059070/esp32s2.zip)
