### ISSUE TITLE
Real time hour export calculations using import price

### ISSUE THREAD

**Issue by wknutsen** [UtilitechAS/amsreader-firmware#788]
Realtime hour export calculations is using import price instead of export price. Day and month calculations is adjusted every hour using export price. Seems like the problem is only related to hour.

**Expected behavior**
Realtime hour export calculation should use export price.

**Screenshots**
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/47573481/37a4a658-5d74-486c-9389-817ccea00169)
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/47573481/ad4a4ccd-b0d4-4164-ad9b-221684c181f5)

Hardware information:

Country: Norway
Meter: Aidon
Encryption enabled: No
AMS reader:
M-bus adapter (if applicable):
Relevant firmware information:

Version: 2.3.5
MQTT: Yes
MQTT payload type: JSON
HAN GPIO: Unknown
HAN baud and parity: Unknown
Temperature sensors: No
ENTSO-E API enabled: Yes

**Comment by ArnieO** [comment]
Good catch - thank you for reporting!
