### ISSUE TITLE
Allow reordering of price configuration entries

### ISSUE THREAD

**Issue by MrAdam** [UtilitechAS/amsreader-firmware#795]
At the moment it is not possible to change the ordering of the price configuration entries.

This means that if I have to add a new price configuration entry before the "tax" one that I have at the end, I would have to remove the tax configuration first, and readd it in the end.

Some way of changing the order through the UI would be nice.

**Comment by gskjold** [comment]
Test version that allows this:
[esp32s3.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15499732/esp32s3.zip)
[esp32solo.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15499734/esp32solo.zip)
[esp32.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15499735/esp32.zip)
[esp8266.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15499736/esp8266.zip)
[esp32c3.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15499737/esp32c3.zip)
[esp32s2.zip](https://github.com/UtilitechAS/amsreader-firmware/files/15499738/esp32s2.zip)
