### ISSUE TITLE
Unable to upgrade to 2.3.6

### ISSUE THREAD

**Issue by gskjold** [UtilitechAS/amsreader-firmware#808]
ESP32 and ESP32-C3 devices may experience upgrade issues. We are currently working on solving this issue for the next patch

**Comment by avandorp** [comment]
Interesting. OTA (via locally downloaded bin file) from 2.3.4 to 2.3.6 worked flawlessly for my C3.

**Comment by ArnieO** [comment]
> Interesting. OTA (via locally downloaded bin file) from 2.3.4 to 2.3.6 worked flawlessly for my C3.

Is that a 4MB device?

**Comment by avandorp** [comment]
> Is that a 4MB device?
Yes, should be. But I'm not sure how to check remotely.
