### ISSUE TITLE
Price current hour sent to MQTT randomly during one hour

### ISSUE THREAD

**Issue by Cartoon-Dude** [UtilitechAS/amsreader-firmware#810]
I noticed the current hour price is sent only during an hour randomly every few days to homeassistant MQTT.
![Capture d’écran du 2024-06-17 14-36-00](https://github.com/UtilitechAS/amsreader-firmware/assets/133660601/13bfe2ee-9002-4143-870e-b06f6f57b4be)
Everything related to price is marked in homeassistant as "unavailable" most of the time.
![Capture d’écran du 2024-06-17 14-46-08](https://github.com/UtilitechAS/amsreader-firmware/assets/133660601/082b67f2-6e05-4ac5-bda5-a591b2fdecd3)
Unfortunately only this value can be use to calculate the cost with the homeassistant energy stuff.

v2.3.6

**Comment by ArnieO** [comment]
Are you reading data directly from Entso-E (using API key), or are you reading from our intermediary server (no API key)?

Experience shows that reading from Entso-E is sometimes not so reliable, which is why we set up the intermediary server (with an API that is far easier for the device).

**Comment by ArnieO** [comment]
Can you show your configuration for reading prices?
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/eb2ea3c3-0ba5-482a-ae14-94d4f13bc5be)

**Comment by Cartoon-Dude** [comment]
![Capture d’écran du 2024-06-17 15-46-01](https://github.com/UtilitechAS/amsreader-firmware/assets/133660601/53211699-4c1d-4df4-97f3-993e895e55b7)

**Comment by gskjold** [comment]
Do you have a fixed energy price? There could be some issue if fetch is not enabled and you rely on a fully fixed price

**Comment by ArnieO** [comment]
> Do you have a fixed energy price? There could be some issue if fetch is not enabled and you rely on a fully fixed price

His screenclip above confirms that he has fixed prices, which is why he has not activated "Enable price fetch" (and should not need to). Maybe a snag related to that then?

**Comment by ArnieO** [comment]
Seems to be a bug. We'll look into it.
Thank you for reporting!

**Comment by NiteCrwlr** [comment]
Hello. I can confirm this, same problem here.

**Comment by gskjold** [comment]
@NiteCrwlr do you also have "Enable price fetch from server" disabled?

Also, check that your device is not rebooting randomly, just to rule out this as a cause

**Comment by gskjold** [comment]
The attached build should fix this issue:

[esp32s3.zip](https://github.com/user-attachments/files/16039336/esp32s3.zip)
[esp32solo.zip](https://github.com/user-attachments/files/16039337/esp32solo.zip)
[esp32.zip](https://github.com/user-attachments/files/16039338/esp32.zip)
[esp32c3.zip](https://github.com/user-attachments/files/16039339/esp32c3.zip)
[esp32s2.zip](https://github.com/user-attachments/files/16039340/esp32s2.zip)
[esp8266.zip](https://github.com/user-attachments/files/16039341/esp8266.zip)

**Comment by NiteCrwlr** [comment]
> @NiteCrwlr do you also have "Enable price fetch from server" disabled?
> 
> Also, check that your device is not rebooting randomly, just to rule out this as a cause

Yes, "Enable price fetch from server" is disabled.
Device does not reboot, it has a stable uptime.
I will try the fixed firmware, thank you for your effort!

**Comment by NiteCrwlr** [comment]
Looks good! Price sensors all available since the update yesterday evening! 👍🏼

**Comment by Cartoon-Dude** [comment]
It is now perfect, and the switch to day/night tariff is working.
