### ISSUE TITLE
Editing hourly data doesn't change tariff peaks

### ISSUE THREAD

**Issue by SVH-Powel** [UtilitechAS/amsreader-firmware#812]
**Describe the bug**
The title says it all. When editing hourly data because it has missed one hour (one hour is zero and the next one is twice as much), the tariff peaks is not changed and is from now on not related to actual data at all.

Version is 2.3.6

**Comment by ArnieO** [comment]
I tried to reproduce this, by editing one hour to 8000:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/55cca4fb-ed29-4cf9-a1c2-b39c9fc7de90)

Can you retry, and document step by step what you did?

**Comment by SVH-Powel** [comment]
I don't have access to the amsreader at the moment. I am able to edit the data as you show, but after setting the value to 8kW, what is your monthly tariff peak?

**Comment by ArnieO** [comment]
Ah - right. Sorry, I misunderstood. 
This is an enhancement point.

It is possible to fix the incorrect peak by editing the cfg file. I will make a "tips & tricks" article on how to do it later today.

**Comment by ArnieO** [comment]
Until we get an "Edit data" also on "Tariff peaks": This article is now edited to indicate how to edit Tarrif peaks by using the config file: https://www.amsleser.no/module/ets_blog/blog?id_post=28
