### ISSUE TITLE
Less stable HAN parsing lately

### ISSUE THREAD

**Issue by StarkJohan** [UtilitechAS/amsreader-firmware#816]
Recently, I can't say exactly after what version update, I've noticed a lot more errors in the data parsing. 
I'm constantly seeing "Footer checksum error" and "Unknown data received, check meter config". Sometimes it's just one "red" error until the next 10s update, sometimes it takes multiple updates to clear the error, say 3-5 x 10s updates in a row is erroneous.
I have not changed anything in my config and the parsing has been very consistent previously, say 99% hit ratio. Now it's more like 75% correct readouts.
Not a big issue but I wanted to inform you in case there's been any recent software changes that might cause more errors than before.

Kamstrup Omnipower without adapter
HAN-NVE configuration, DLMS output, no encryption
Pow-K (old kit version). Currently on software v2.3.6
2400 / 8N1 / Buffer 256

Any idea on what might cause the increase in errors? Hardware/software issue?

**Comment by ArnieO** [comment]
We have received other feedback over the last week on issues with ESP8266-based devices, what you're seeing could be related.

A bug surfaced yesterday; please try the test firmware in this thread and give us your feedback!
https://github.com/UtilitechAS/amsreader-firmware/issues/815#issuecomment-2199477693

**Comment by gskjold** [comment]
Please try the attached firmware to check if that makes any difference for you:
[esp8266.zip](https://github.com/user-attachments/files/16078570/esp8266.zip)

**Comment by StarkJohan** [comment]
Thanks, currently testing. First 5 minutes looks promising. Will keep an eye on it and report back.

**Comment by StarkJohan** [comment]
Issue not completely solved but a lot better. It's at least not affecting the functionality too much. Once in a while I get 2 or 3 errors consecutively but most of the time it's just one and that's not too serious.

**Comment by ArnieO** [comment]
> Issue not completely solved but a lot better. It's at least not affecting the functionality too much. Once in a while I get 2 or 3 errors consecutively but most of the time it's just one and that's not too serious.

Thank you for the update!

**Comment by rogerjak** [comment]
I'm getting this almost every other reading on 2.3.8 :(

**Comment by ArnieO** [comment]
> I'm getting this almost every other reading on 2.3.8 :(

This is not normal; I will assist you.

- Please provide screenshot(s) of the error message(s) you see.
- Please provide screenshot of your config page.
- Please run a [Telnet debug](https://www.amsleser.no/module/ets_blog/blog?id_post=24) and post the output file. 

(Note to self: @rogerjak runs a Pow-K purchased in October -24)

**Comment by rogerjak** [comment]
Sorry, my Wifi to the meter is really bad, almost 50m away :(
Trying to improve the coverage before doing some debugging.
But anyway, during the hour it did had connection, I got the checksum errrors a lot, and that shouldn't be connected to the bad Wifi, right?

**Comment by ArnieO** [comment]
> Sorry, my Wifi to the meter is really bad, almost 50m away :( Trying to improve the coverage before doing some debugging. But anyway, during the hour it did had connection, I got the checksum errors a lot, and that shouldn't be connected to the bad Wifi, right?

I agree. Bad Wi-Fi should lead to connection issues but not checksum errors (which happens locally on the device, before Wi-Fi transmission).

I believe you are in Sweden, where the meters are often place outdoors, in a metal cabinet? That is a challenge for Pow-K. One solution could be to place a Wi-Fi extender on the indoor side of the wall where the cabinet is located.

**Comment by rogerjak** [comment]
Yes, I'm trying to extend my wifi mesh, but it's not that easy, since the meter is outside a barn almost 50 m away..
But as you said; the HAN parsing is locally, so still an issue :(

**Comment by ArnieO** [comment]
> But as you said; the HAN parsing is locally, so still an issue :(

Exactly. Which is why I am curious to see some payloads, while you have connection and get those HAN errors - as this is highly unusual. 

What you *could* check is whether the Pow-K is properly seated in your meter. We have seen some very few times that the 3D printed holder does not properly take into account production tolerances in the meter. The consequence being that the board is not properly seated inside the meter. The usual consequence is that the unit does not fire up - but if you are really unlucky, the data pin could have an imperfect connection. 

You can check this by pulling the board out of the holder (bend a bit the notched part that holds the board and pull board out), then insert it while taking care to hit the 6 pins inside the meter. If bad contact due to the holder is your issue, we will send you a new holder that has an adjusted design to take care of it.

**Comment by rogerjak** [comment]
Strange, suddenly I don't get any checksum errors at all.
Nothing's really changed, just me trying to improve the wifi, to no avail btw, still -90dBm...
Will report back here if it should happen again.
Thanks for the pointers!

**Comment by ArnieO** [comment]
No problem; contact me if you see the issues again - because that shall not happen. 
You can also reach me on post@amsleser.no.
