### ISSUE TITLE
Real time calculation Exporting

### ISSUE THREAD

**Issue by arnwik** [UtilitechAS/amsreader-firmware#829]
Real time calculation for production/exporting is only showing when the system actually are Exporting. The instance the system don't export anymore, no data for exporting is showing (like it does on the Consumption).
There should be a toggle to have production/export permanently on.

**Comment by ThorAlex87** [comment]
There is, third to last section "user interface" on the configuration page has "enabled", "disabled" and "auto" settings for everything on the main page.

**Comment by gskjold** [comment]
Also, if you configure "Production capacity", it will always show

**Comment by ThorAlex87** [comment]
> Also, if you configure "Production capacity", it will always show

Hey I had not noticed production could be set, cool! But i prefer having both import and export meters set to auto, as they are mutually exclusive so there is no point in showing both?

**Comment by ArnieO** [comment]
> > Also, if you configure "Production capacity", it will always show
> 
> Hey I had not noticed production could be set, cool! But i prefer having both import and export meters set to auto, as they are mutually exclusive so there is no point in showing both?

The choice is yours! 😁

**Comment by ThorAlex87** [comment]
But if I understand you correctly I cannot choose to configure production and have the export meter only show when there is export?

(I'm currently testing this, so I will find out by the end of the day)

**Comment by ArnieO** [comment]
> But if I understand you correctly I cannot choose to configure production and have the export meter only show when there is export?

Passing the question to @gskjold :  
If production is configured in Config/Meter; does that override an "Auto" setting in **User interface / Export gauge** so that Export gauge is always shown?

**Comment by gskjold** [comment]
Correct, if production capacity is configured, gauge is always showing if set to auto
