### ISSUE TITLE
MQTT status switches to offline imediately after appearing online

### ISSUE THREAD

**Issue by shaohme** [UtilitechAS/amsreader-firmware#842]
**Describe the bug**
The AMS reader appears offline immediately after appearing online when connecting to MQTT.

**To Reproduce**
1. Setup to publish to MQTT broker
2. Observe the MQTT topic configured for new messages
3. Reboot AMR reader
4. Observe that the topic <name>/status initially sets to 'online' after which it changes to 'offline'

**Expected behavior**
It should be kept in 'online' state as long as the device is running.

**Screenshots**
![screenshot-1726137823](https://github.com/user-attachments/assets/d2062dc9-049d-4bd2-a1a0-ee7d062519e5)
![screenshot-1726138247](https://github.com/user-attachments/assets/227dce94-4ed6-4c6e-834c-f24bc38fe622)

**Hardware information:**
 - Country: Denmark
 - Meter: Kamstrup Omnipower
 - Encryption enabled yes
 - AMS reader: Pow-K+
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.3.8
 - MQTT: yes
 - MQTT payload type: Raw (full)
 - HAN GPIO:
 - HAN baud and parity: 2400 8E1
 - Temperature sensors:
 - ENTSO-E API enabled: yes

**Comment by ArnieO** [comment]
Just to be sure what you experiencing: 
Does the device not transmit payloads? 
Or is it the problem that the transmitted status is set to "offline"?

**Comment by shaohme** [comment]
> Just to be sure what you experiencing: Does the device not transmit payloads? 

I assume by 'payloads' you mean MQTT messages to the broker. If so, it does. 

> Or is it the problem that the transmitted status is set to "offline"?

Yes. It starts by setting the value 'online' but shortly after sets it to 'offline' and stays there, as show in the screenshot.

**Comment by ArnieO** [comment]
> It starts by setting the value 'online' but shortly after sets it to 'offline' and stays there, as show in the screenshot.

And continues to send MQTT messages to the broker after that?

**Comment by shaohme** [comment]
I have not setup a "Client ID" in my MQTT config before. When I set it, and reboot the reader, the problem disappeared :face_with_diagonal_mouth:

**Comment by ArnieO** [comment]
I think each client has to "present itself" to the broker with an ID (that must not be the same as any other client). 
I guess that explains it!

If your setup now works as expected, I invite you to close this thread.

**Comment by shaohme** [comment]
> I think each client has to "present itself" to the broker with an ID (that must not be the same as any other client). I guess that explains it!
> 
> If your setup now works as expected, I invite you to close this thread.

I guess, but should AMS not inform the user of this? Either by recommending or demand a client id?

**Comment by ArnieO** [comment]
> I guess, but should AMS not inform the user of this? Either by recommending or demand a client id?

That is actually a good idea! This field could be auto populated with Hostname as default value. I will update [the Wiki](https://wiki.amsleser.no/e/en/HomeAutomation/Home-Assistant) now to remind that Client ID cannot be empty.

I mark this as an enhancement proposition for @gskjold to consider.

**Comment by gskjold** [comment]
Making this field required when MQTT is enabled
