### ISSUE TITLE
Price service unavailable 

### ISSUE THREAD

**Issue by ojessie** [UtilitechAS/amsreader-firmware#851]
Since the update to 2.3.8 the price service for Austria is not available. 

- Country: Austria
- Meter: Sagemcom
- Encryption: yes
- AMS Reader: Chip: esp32s2 (160MHz)
Version: 2.3.8
- MQTT: yes

The exact error message is: "Price service: Price unavailable, not found"

**Comment by ArnieO** [comment]
This seems to be an issue with Entso-E (where we get the prices): 
[This link ](https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=false&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=05.10.2024+00:00|CET|DAY&biddingZone.values=CTY|10YAT-APG------L!BZN|10YAT-APG------L&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2))should show today's price graph in Austria. 

What I get is this:
![image](https://github.com/user-attachments/assets/311a6049-ce07-40e7-9250-e313333c5351)

Unfortunately, Entso-E has data outages sometimes. You just have to wait for it to be restored.

**Comment by ojessie** [comment]
Thanks for clarification.

Br


------ Originalnachricht ------
Von "ArnieO" ***@***.***>
An "UtilitechAS/amsreader-firmware" 
***@***.***>
Cc "ojessie" ***@***.***>; "Author" 
***@***.***>
Datum 05.10.2024 16:33:14
Betreff Re: [UtilitechAS/amsreader-firmware] Price service unavailable 
(Issue #851)

**Comment by cmock** [comment]
I'm gonna reopen this as the "old" ENTSO-E api seems to be deprecated, visiting the above link now shows:
![Screenshot_20241018_214042](https://github.com/user-attachments/assets/8f47e483-68ae-4bca-8350-8f8d16e8ead9)

**Comment by ArnieO** [comment]
Thank you for the heads-up; we will look into this.

**Comment by gskjold** [comment]
This is just the web view, API is not affected by tihs
