### ISSUE TITLE
GUI does not always show all available prices

### ISSUE THREAD

**Issue by tronde-ams** [UtilitechAS/amsreader-firmware#860]
Generic ESP32, Aidon 3p IT, MQTT, NO1

Sometimes the GUI does not always show all prices availble as json. I have seen this a couple of times before. This time it seems like it has become stuck at 03:00 as the last price, other times it has been somehing else.

Today 14:53

![1453](https://github.com/user-attachments/assets/24fd3a35-9984-4797-8db4-2a339f4f7700)
![1453-price](https://github.com/user-attachments/assets/a8a9dcee-2e1c-4d78-8a05-59c69b0ceebd)

Today 15:01

![1501](https://github.com/user-attachments/assets/d04b6e55-20a4-46ee-a1e7-ab90968b7e1a)

![1501-price](https://github.com/user-attachments/assets/9521f639-606c-4170-a661-1eca71686316)

Today 16:05

![1605](https://github.com/user-attachments/assets/d7fabc8c-d7d3-424d-a9b1-c9759b6076eb)

<img width="200" alt="1605-price" src="https://github.com/user-attachments/assets/2afe1c23-4d53-4c01-b0ce-c6fa0e1c010e">

**Comment by ArnieO** [comment]
This is now fixed on our intermediate server, for all users reading price data there (not using Entso-E API token). 
Users that prefer reading directly from Entso-E (using API token) must wait for a fix in upcoming v2.3.9.
