### ISSUE TITLE
Missing data in HA (2.3.9)

### ISSUE THREAD

**Issue by rogerjak** [UtilitechAS/amsreader-firmware#865]
After upgrading to 2.3.9 I don't get "current day usage" and "current day cost" in MQTT in HA anymore.

**Comment by rogerjak** [comment]
And suddenly it came back just a few minutes ago 😲

**Comment by ArnieO** [comment]
> And suddenly it came back just a few minutes ago 😲

The sensors are defined in a separate MQTT message that is sent with a quite long time interval. When there is an upgrade, HA needs to receive the new message before things start "behaving".
