### ISSUE TITLE
AMS reader v2.3.9 - Keeps Restarting - 1 to 3 times a hour

### ISSUE THREAD

**Issue by A-Wangen** [UtilitechAS/amsreader-firmware#868]
**Describe the bug**
After updating from v2.3.6 to v2.3.9 the AMS reader peeps rebooting 1-3 times a hour. 

**To Reproduce**
Nothing special needs to be done; it happens when I look at it in the web browser and other random times. 

**Expected behavior**

**Screenshots**
NA

**Hardware information:**
 - Country: Norway
 - Meter: Aidon
 - Encryption enabled [yes/no]
 - AMS reader: Pow-U+, esp32s2
 - M-bus adapter (if applicable): NA

**Relevant firmware information:**
 - Version: v2.3.9
 - MQTT: yes
 - MQTT payload type: RAW
 - HAN GPIO: N/A
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: No
 - ENTSO-E API enabled: no

**Additional context**
NA

**Comment by catohagen** [comment]
I had similar issues a few months ago, turned out to be the wifi power saving, if its on, try to set it to off or minimum

**Comment by A-Wangen** [comment]
> Can you show me your config screen?


![image](https://github.com/user-attachments/assets/2e4cebe2-11d6-4459-84b9-ebcb715234d3)


> I had similar issues a few months ago, turned out to be the wifi power saving, if its on, try to set it to off or minimum

Will try this

**Comment by ArnieO** [comment]
Unless you have a really old router, you should deactivate 802.11.b compatibility. It might contribute to causing issues.

**Comment by A-Wangen** [comment]
I have updated this now. removing the check on 802.11.b
The enable debugging, I did turn on after issues started. but turned of now. 
 
Per now this is the last time of reboot: 

  **Last boot: 18.11.2024 08:54
  Reason: 3 (3/0)**

Where can I see description for the reason?

**Comment by ArnieO** [comment]
> Where can I see description for the reason?

There should be a description next to the code, like this: 
![image](https://github.com/user-attachments/assets/e21c96de-c33d-4aaf-b336-fecb354e9cf1)

@gskjold: Can you help identify the reboot reason here?

**Comment by A-Wangen** [comment]
> There should be a description next to the code, like this:

This is what I see: only a number 

![image](https://github.com/user-attachments/assets/f3b8414d-75e6-4c27-b0b0-5ec13e5b096c)

**Comment by ArnieO** [comment]
> This is what I see: only a number

I can see that - and you have an other code now: "1 (1/0)"
We need help from @gskjold to understand this.

**Comment by A-Wangen** [comment]
@gskjold are you able to have a look at this? Do to down time of the ams in some critical times of the hour I now have the issue that I have gone from  10 KW to just over 15kw in "effektledd"

**Comment by ArnieO** [comment]
OK - thank you. I'm puzzled that the clock goes red in periods - indicating an internet issue. 
I do not have any experience with this DNS server you're using:
![image](https://github.com/user-attachments/assets/3dcc3ad1-6193-416f-89ca-52ee05c90a08)
Can you change it to **1.1.1.1** - which is one that we use as default, to see if that fixes the internet issue?

But let us try first to address the language issue. 
This should not show "Unknown", so there is something in your configuration that has been messed up:
![image](https://github.com/user-attachments/assets/a365d89d-1457-47ef-9fc2-431bebf8e3bc)
Do you see "Load from server" in the pulldown?
![image](https://github.com/user-attachments/assets/b6add662-0ef8-45a8-9599-c5dd58a9c1d3)
If so: Click it. 
Then click it again and select the language you prefer:
![image](https://github.com/user-attachments/assets/297f9378-3aba-4425-84dc-bfb97cf068b7)

You should then see some more information in the MQTT error messages.

**Comment by A-Wangen** [comment]
Hi, I am not sure why I have set static IP in the AMS hence I have also put this in the rooter.  So, after updating this from static to DHCP. Everything looks to be working as it should, even the language came instant. 

Now I also see the message for a reboot, are there any wiki links for background for the different reasons? 
last was:  vbat power on reset (1/0) 



![image](https://github.com/user-attachments/assets/cc0c7705-d3aa-41fa-8c7d-5f0eb09b6b91)

**Comment by ArnieO** [comment]
> Hi, I am not sure why I have set static IP in the AMS hence I have also put this in the rooter. So, after updating this from static to DHCP. Everything looks to be working as it should, even the language came instant.
> 
> Now I also see the message for a reboot, are there any wiki links for background for the different reasons? last was: vbat power on reset (1/0)
> 
> ![image](https://private-user-images.githubusercontent.com/43532832/390360986-cc0c7705-d3aa-41fa-8c7d-5f0eb09b6b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDY0NDUsIm5iZiI6MTczMjcwNjE0NSwicGF0aCI6Ii80MzUzMjgzMi8zOTAzNjA5ODYtY2MwYzc3MDUtZDNhYS00MWZhLThjN2QtNWYwZWIwOWI2YjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDExMTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5MWUzYWYxMzFiNDFiZTYwMzkwOTJlNmJhYmU5ZTZhYjE0NDYxNTJhMWIxMWY0MTFkNDdlOGFjYWQ2MmIxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TAtUDOokP8YEK8g2h7O4ANb3iLQJjCkN2OjDulO3Rvc)

Wi-Fi connection is faster if you use Static IP. That will work great if you use:
- A local IP address that is not managed by router DHCP
- A valid DNS (for instance 1.1.1.1)

But DHCP works fine too - so you can just stay with that. 

No wiki on "Årsak", but "Vbat power on reset (1/0)" is normal for a startup "from scratch", or if the device has rebooted due to low voltage (can happen from time to time on Pow-U, but should be very infrequent). The indication is mainly used for debugging - if specific issues arise.

**Comment by A-Wangen** [comment]
closed resolved with fix to WIFI settings.
