### ISSUE TITLE
No HAN data received last 30s, single blink - continuously.

### ISSUE THREAD

**Issue by Aberen** [UtilitechAS/amsreader-firmware#871]
So, I've had a Pow-K+ since october 2022. It's been running with no issues after I got my DLMS/COSEM keys from Kamstrup (Am located in Denmark). But about 2 weeks ago, I noticed that my home assistant instance didn't receive any data from the Pow-K+. I checked the amsreader interface, and yep. No data being received. I also noticed it was running a very old firmware (2.1.7). So I updated it (To 2.3.9), new interface and everything, in the same move, I had to reset everything. Chose Pow-K+ as device during the setup and started putting in all the relevant info. Wifi, Meter (Keys), MQTT, etc.

Now, I have double-checked the wiki for Baud-rates, and checked other issues here on Github, I've tried basically everything at this point, even got new keys sent from Kamstrup (In case they would have changed or something). But I cannot get any HAN data. When I telnet in to the unit, I just keep getting '(W) No HAN data received last 30s, single blink'. I've even tried downgrading to no avail. MQTT connects perfectly fine and everything, I'm just not getting anything from the meter. 

Anybody has any ideas what to try at this point? It's really odd. It's been working with no issues for about 2 years.

**Hardware information:**
 - Country: Denmark
 - Meter: Kamstrup Omnipower - Three Phase Meter. (684-11-31B-N24-5101-013)
 - Encryption enabled: yes.
 - AMS reader: Pow-K+

**Relevant firmware information:**
 - Version: 2.3.9
 - MQTT: Yes
 - MQTT payload type: Home-assistant
 - Communication: Passive (Push) 
 - HAN baud and parity: 2400 8N1
 - Buffer size: 256
 - Voltage: 400V (TN)
 - Main Fuse: 40A

**Comment by ArnieO** [comment]
If you have no blue blinking on the Pow-K LED, I suspect that you have run into the "Omnipower stops sending data" issue - as described here: https://www.amsleser.no/module/ets_blog/blog?id_post=33

**Comment by Aberen** [comment]
Interesting, I've tried contacting Radius and see if they are able to give it a reboot. Thanks for the info. Hopefully they can fix it on their end.

**Comment by ArnieO** [comment]
> Interesting, I've tried contacting Radius and see if they are able to give it a reboot. Thanks for the info. Hopefully they can fix it on their end.

Remote reboot is a bit tricky with some smaller grid companies, but Radius outsources some of the meter management to Kamstrup (at least they used to 1-2 years ago) - so this should not be a problem. Those of our Radius-customers that have experienced this issue have all been helped. 🤞

**Comment by Aberen** [comment]
Alright, after a few emails and few days of waiting, a reboot did manage to fix everything, they sent me an email stating to take it out, and not have it in until I receive a reboot confirmation from kamstrup. After plugging it in, i immediately got a a lot of blue lights, and the reader works flawlessly. Thanks for the insight and the nudge in the right direction.

**Comment by ArnieO** [comment]
> Alright, after a few emails and few days of waiting, a reboot did manage to fix everything, they sent me an email stating to take it out, and not have it in until I receive a reboot confirmation from kamstrup. After plugging it in, i immediately got a a lot of blue lights, and the reader works flawlessly. Thanks for the insight and the nudge in the right direction.

Our understanding is that the process is a bit elaborate, but at least it is easier with Radius that (as far as we understand) has outsourced parts of the meter management to Kamstrup. We have heard one cases where a smaller grid company in Denmark requested a fee from the end user for doing a reset - maybe because Kamstrup charges them for the "service". I do not find that logical - to say the least. An other small grid company in Denmark had no idea how to get a reset done - so the end user had to call (and pay!) an electrician to come and disconnect / reconnect the meter.
