### ISSUE TITLE
Realtime plot not showing

### ISSUE THREAD

**Issue by obidobi** [UtilitechAS/amsreader-firmware#872]
Finally received my Pow-K!
Everything is working fine I have it up and running and have been running it for +1 hour.
Have MQTT working and getting my grafs in HomeAssistant.

Just one thing tho. The realtime plot on the devices webpage don't show any data.
Looking at the HTML  code:
<polyline opacity="0.9" fill="#5c2da5" stroke="#5c2da5" stroke-width="1" points="34,NaN 38,NaN 42,NaN 46,NaN 50,NaN 54,NaN 58,NaN 62,NaN 66,NaN 70,NaN 74,NaN 78,NaN 82,NaN 86,NaN 90,NaN 94,NaN 98,NaN 102 ..... </polyline>

I checked the debug function and only messages I see are (every 10s)
(D) Received valid DLMS at 29
(D) READY to update (internal clock 14:41:52 UTC, meter clock: 00:00:00, list type 2, est: 1, using clock: 1)

I don't mind it not showing since I use HomeAssistant anyways. Just wanted to report it :)

I only connected the Pow-K to internet for firmware update. Now it is running on a local network. NTP still works since my router handle that.

**Hardware information:**
 - Country: Sweden
 - Meter: Kamstrup
 - Encryption enabled: no
 - AMS reader: Pow-K

**Relevant firmware information:**
 - Free mem: 109.2kb
 - Version: 2.3.9
 - MQTT: yes
 - MQTT payload type: JSON
 - HAN GPIO: ?
 - HAN baud and parity: 2400 8N1
 - ENTSO-E API enabled: no

**Comment by ArnieO** [comment]
Strange. 

A seemingly random question: **Are you with Sollentuna Energi?** 

We have had some very particular issues lately with their meters, see https://github.com/UtilitechAS/amsreader-firmware/issues/861

**Comment by obidobi** [comment]
No I am using Borlänge Energi

**Comment by obidobi** [comment]
Wierd I just got home and logged in an now the graph is showing! 

Just one suggestion I feel the graph should not start at 0W but the lowest value for the last hour to show more detail!

**Comment by obidobi** [comment]
Just a note. Now when I logged in for the first time and the graph was showing up. For one or two seconds it seemed to slide from left to right while it was filling in values before settling down and showing the values on the correct times.

**Comment by ArnieO** [comment]
> Just a note. When I logged in for the first time and the graph was showing up. For one or two seconds it seemed to slide from left to right while it was filling in values before settling down and showing the values on the correct times.

Yes, this is the way it works. There are so many points on the full graph that it has to be transferred in "chunks".
