### ISSUE TITLE
POW-U Lost L2 Current measurement upgrading from v2.2.21 to v2.3.9

### ISSUE THREAD

**Issue by sigvind** [UtilitechAS/amsreader-firmware#877]
**Describe the bug**
After upgrading FW on POW-U (esp8266) from v2.2.21 to 2.3.9 I lost the L2 current measurement, L1 and L3 currents have values.
The GUI shows tool tip "L2 current is not reported by your meter" and a not available in the graph.
L2 is reported as 0 on MQTT.
The L2 current was being reported up till the upgrade. 
Aidon 6525 meter.

**To Reproduce**
1. Had 2.2.21 running for long time. It was rebooting, so checked for new FW.
2. Upgraded to 2.3.9 latest and checked around
3. L2 doesn't show

**Expected behavior**
I expected the measurement to continue showing, since the fact it was there before the update indicates it is reported by the meter  
If it's not a bug, maybe a work-around exists?

**Screenshots**
Screen shot from Home assistant - upgrade at 21:18.
Screen shot from AMSReader GUI 
Screen shot of config

**Hardware information:**
 - Country: Norway
 - Meter: Aidon 6525
 - Encryption enabled [no]
 - AMS reader: [e.g. Pow-U, esp8266]
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: upgrade from 2.2.21 to 2.3.9
 - MQTT: [yes]
 - MQTT payload type: [, JSON classic]
 - HAN GPIO: don't know
 - HAN baud and parity: [e 2400 8E1 buffe 192]
 - Temperature sensors [no]
 - ENTSO-E API enabled: [yes]

**Additional context**
![2024-11-27_AMSLeser_v2 2 21_til_2 3 9_L2_borte](https://github.com/user-attachments/assets/bebb6e15-b543-4370-983e-d954ab1a80fd)
![2024-11-27_AMSLeser_v2 3 9_config](https://github.com/user-attachments/assets/81c79757-8de8-4ee5-b57c-b69cbc0c4feb)
![2024-11-27_AMSLeser_v2 3 9_ingen_L2](https://github.com/user-attachments/assets/663f3695-c671-4c71-a1af-0ca6408840d2)

**Comment by sigvind** [comment]
Is this related to comment in https://github.com/UtilitechAS/amsreader-firmware/releases/tag/v2.2.27  ?

**Comment by ArnieO** [comment]
It is fully explained here: https://www.amsleser.no/module/ets_blog/blog?id_post=31
