### ISSUE TITLE
Future energy prices missing

### ISSUE THREAD

**Issue by nossaile** [UtilitechAS/amsreader-firmware#880]
Time is well after 1700 and future energy prices missing independently of ENTSO-E key, but with different error messages: 
if ENTSO-E key is blank then error message=”Price service: Exceeded API rate limit” and 
with correct ENTSO-E key then error message=”Price service: 503”.
I have not seen the "503"-message before!
Chip: esp32s2 (160MHz)
Device: Pow-P1
Installed version: v2.3.9

**Comment by GaupeLnx** [comment]
Had the same with api key (503) and got Price service internal server error when removing the api key.
But it seems to work now again with the api key . Maybe a hick-up at entso-e

**Comment by nossaile** [comment]
Still the same problem for Sweden SE4 at 1908.

**Comment by gskjold** [comment]
Server is unable to get exchange rates for an upstream service. I have added a backup service for exchange rates, so most price areas should work again now. When the primary source is back on line, everything will work again. Guessing tomorrow morning.

**Comment by mortenm22** [comment]
Is this related to the problem?
![Entso-e](https://github.com/user-attachments/assets/7559300b-c420-497c-a3a9-61774efd9a3a)

**Comment by gskjold** [comment]
No, the API is still very much updated still

**Comment by nossaile** [comment]
Prices for Sweden SE4 were back before midnight last night, but it looks like prices for all price regions were not back simultaneously. Why?

**Comment by gskjold** [comment]
Actually not sure, it could be that it failed to load some of the exchange rates from the backup api
