### ISSUE TITLE
AMS reader and HomeAssistant

### ISSUE THREAD

**Issue by obidobi** [UtilitechAS/amsreader-firmware#884]
I have an issue with accumulated data sent one time each hour.

Take Accumulated active import for example. It accumulates data between 13-14. In the AMS web interface it correctly shows this consumption for the hourly bar at 13.00

When sent to HA this data have a timestamp of 14.00+. So in HA graphs it will be displayed as an hourly bar for 14. Since data collected between 14-15 show up in the 14.00 bar. But this data should actually show up in the 13.00 bar since it was collected between 13-14 in AMS.

AMS should really send hourly data with a timestamp of 13:59.59 for HA to show it correctly. Have anyone got a suggestion on how I get HA to show this data not shifted forward one hour?

**Comment by gskjold** [comment]
This issue have been raised several times. I have looked at it before and have not found a way around this. If there is anyone out there who has the answer for this, please let me know and I will implement it.

**Comment by gskjold** [comment]
Also mentioned here: https://github.com/UtilitechAS/amsreader-firmware/wiki/How-to-add-to-Home-Assistant#notes

**Comment by ArnieO** [comment]
Short story: HA used the time of arrival of the message, and meters configured for HAN-NVE (Norway + some Swedish and Finnish meters) send accumulated energy only once per hour - shortly after whole hour. So HA registers the data in the wrong time slot.

**Comment by obidobi** [comment]
Ah. Didn't realize the timestamp is not sent with the data but that HA uses the time the message arrive.
Need to figure out if this can be solved in HA.
Should be able to use the "AMS reader Current hour used" field. Going to try using a utility meter helper with hourly resets and see if that works.

**Comment by ArnieO** [comment]
> Ah. Didn't realize the timestamp is not sent with the data but that HA uses the time the message arrive. Need to figure out if this can be solved in HA. Should be able to use the "AMS reader Current day used" field. Going to try using a utility meter helper with resets and see if that works.

It is only an issue in the countries I mentioned, when the meter only reports kWh once per hour (HAN-NVE configuration). In other countries, where kWh is reported in each telegram, this works as intended.

If you find a solution, please tell us. 
We have a large number of HA users in Norway and Sweden that would love to get this solved!

**Comment by obidobi** [comment]
Just wanna report on how I got around this issue in HA.
HA has a helper called [Integral](https://www.home-assistant.io/integrations/integration/)
So I compute accumulated data directly from the Active import instead of using Accumulated active import

**Comment by obidobi** [comment]
Yeah planned to use those values first, but was not sure exactly how. When I found the Integral helper in HA that was so easy just plug and play the active effect and get accumulated energy usage. Since the effect is updated with high freq. the integral calculation should be precise.

**Comment by joachimtingvold** [comment]
> Just wanna report on how I got around this issue in HA. HA has a helper called [Integral](https://www.home-assistant.io/integrations/integration/) So I compute accumulated data directly from the Active import instead of using Accumulated active import

@obidobi, what settings/values did you use for the Integral sensor that worked for you?

- Metric prefix (kilo, mega, giga, tera). Assuming kilo?
- Time unit (seconds, minutes, hours, days). Assuming hours?
- Integration method (trapezoidal, left Riemann sum, right Riemann sum)
- Max sub-interval

**Comment by joachimtingvold** [comment]
Answering my own question, but seems like these values are the most "sane". This assumes that the input sensor is in "watts", and that it updates often.

- Metric prefix: kilo
- Time unit: hours (default)
- Integration method: Trapezoidal (default)
- Max sub-interval: 0 (default)
